
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken',
  Company: 'Company',
  Department: 'Department',
  JobPosition: 'JobPosition',
  Employee: 'Employee',
  Subscription: 'Subscription',
  AddonFeature: 'AddonFeature',
  Customer: 'Customer',
  Property: 'Property',
  Building: 'Building',
  UnitOccupancy: 'UnitOccupancy',
  BuildingFile: 'BuildingFile',
  InfraPoint: 'InfraPoint',
  Contact: 'Contact',
  RecurringTask: 'RecurringTask',
  BuildingExpense: 'BuildingExpense',
  UnitPayment: 'UnitPayment',
  ManagementAssignment: 'ManagementAssignment',
  CommonArea: 'CommonArea',
  Unit: 'Unit',
  Service: 'Service',
  PropertyService: 'PropertyService',
  ServiceInvoice: 'ServiceInvoice',
  ServiceInvoiceLine: 'ServiceInvoiceLine',
  UserCompanyRole: 'UserCompanyRole',
  MenuConfig: 'MenuConfig',
  Announcement: 'Announcement',
  Announcement_User: 'Announcement_User',
  APIUsageLog: 'APIUsageLog',
  APICostConfig: 'APICostConfig',
  MonthlyCostSummary: 'MonthlyCostSummary',
  MaintenanceRequest: 'MaintenanceRequest',
  CMSPage: 'CMSPage',
  FAQ: 'FAQ',
  PricingTier: 'PricingTier',
  ContactMessage: 'ContactMessage',
  CookieConsent: 'CookieConsent',
  AppSettings: 'AppSettings'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  phone: 'phone',
  mobile: 'mobile',
  passwordHash: 'passwordHash',
  role: 'role',
  status: 'status',
  companyId: 'companyId',
  customerId: 'customerId',
  buildingId: 'buildingId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastLoginAt: 'lastLoginAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const VerificationTokenScalarFieldEnum = {
  id: 'id',
  email: 'email',
  token: 'token',
  expires: 'expires',
  type: 'type'
} as const

export type VerificationTokenScalarFieldEnum = (typeof VerificationTokenScalarFieldEnum)[keyof typeof VerificationTokenScalarFieldEnum]


export const CompanyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  logoUrl: 'logoUrl',
  subscriptionTier: 'subscriptionTier',
  maxProperties: 'maxProperties',
  maxUsers: 'maxUsers',
  maxStorage: 'maxStorage',
  status: 'status',
  trialEndsAt: 'trialEndsAt',
  afm: 'afm',
  taxOffice: 'taxOffice',
  legalName: 'legalName',
  legalForm: 'legalForm',
  activity: 'activity',
  title: 'title',
  address: 'address',
  district: 'district',
  city: 'city',
  postalCode: 'postalCode',
  country: 'country',
  lat: 'lat',
  lng: 'lng',
  phone1: 'phone1',
  phone2: 'phone2',
  phone3: 'phone3',
  fax: 'fax',
  email: 'email',
  website: 'website',
  glnCode: 'glnCode',
  registryNumber: 'registryNumber',
  vatStatus: 'vatStatus',
  distStats: 'distStats',
  gemhNumber: 'gemhNumber',
  ikaNumber: 'ikaNumber',
  ikaRegistry: 'ikaRegistry',
  folderNumber: 'folderNumber',
  kadCode: 'kadCode',
  foundedAt: 'foundedAt',
  dissolutionDate: 'dissolutionDate',
  iban: 'iban',
  bank: 'bank',
  initialCapital: 'initialCapital',
  paidCapital: 'paidCapital',
  legalRep: 'legalRep',
  legalRepId: 'legalRepId',
  tpte: 'tpte',
  tpteteka: 'tpteteka',
  employmentOrg: 'employmentOrg',
  remarks: 'remarks',
  softoneCompanyCode: 'softoneCompanyCode',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CompanyScalarFieldEnum = (typeof CompanyScalarFieldEnum)[keyof typeof CompanyScalarFieldEnum]


export const DepartmentScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  name: 'name',
  description: 'description',
  isActive: 'isActive',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DepartmentScalarFieldEnum = (typeof DepartmentScalarFieldEnum)[keyof typeof DepartmentScalarFieldEnum]


export const JobPositionScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  departmentId: 'departmentId',
  title: 'title',
  description: 'description',
  level: 'level',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type JobPositionScalarFieldEnum = (typeof JobPositionScalarFieldEnum)[keyof typeof JobPositionScalarFieldEnum]


export const EmployeeScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  departmentId: 'departmentId',
  jobPositionId: 'jobPositionId',
  userId: 'userId',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  phone: 'phone',
  mobile: 'mobile',
  employeeCode: 'employeeCode',
  hireDate: 'hireDate',
  terminationDate: 'terminationDate',
  status: 'status',
  afm: 'afm',
  amka: 'amka',
  ikaNumber: 'ikaNumber',
  address: 'address',
  city: 'city',
  postalCode: 'postalCode',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type EmployeeScalarFieldEnum = (typeof EmployeeScalarFieldEnum)[keyof typeof EmployeeScalarFieldEnum]


export const SubscriptionScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  vivaBatchId: 'vivaBatchId',
  tier: 'tier',
  billingCycle: 'billingCycle',
  amount: 'amount',
  currency: 'currency',
  status: 'status',
  startDate: 'startDate',
  endDate: 'endDate',
  renewalDate: 'renewalDate',
  trialDays: 'trialDays',
  trialUsed: 'trialUsed',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SubscriptionScalarFieldEnum = (typeof SubscriptionScalarFieldEnum)[keyof typeof SubscriptionScalarFieldEnum]


export const AddonFeatureScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  buildingId: 'buildingId',
  featureKey: 'featureKey',
  featureName: 'featureName',
  description: 'description',
  monthlyPrice: 'monthlyPrice',
  billingCycle: 'billingCycle',
  active: 'active',
  activatedAt: 'activatedAt',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AddonFeatureScalarFieldEnum = (typeof AddonFeatureScalarFieldEnum)[keyof typeof AddonFeatureScalarFieldEnum]


export const CustomerScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  type: 'type',
  sodType: 'sodType',
  softoneTrdr: 'softoneTrdr',
  code: 'code',
  name: 'name',
  afm: 'afm',
  doy: 'doy',
  email: 'email',
  phone: 'phone',
  phone2: 'phone2',
  fax: 'fax',
  webpage: 'webpage',
  address: 'address',
  city: 'city',
  district: 'district',
  postalCode: 'postalCode',
  country: 'country',
  isActive: 'isActive',
  remarks: 'remarks',
  lat: 'lat',
  lng: 'lng',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CustomerScalarFieldEnum = (typeof CustomerScalarFieldEnum)[keyof typeof CustomerScalarFieldEnum]


export const PropertyScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  customerId: 'customerId',
  name: 'name',
  notes: 'notes',
  address: 'address',
  city: 'city',
  postalCode: 'postalCode',
  country: 'country',
  lat: 'lat',
  lng: 'lng',
  vivaEnabled: 'vivaEnabled',
  vivaMerchantId: 'vivaMerchantId',
  vivaApiKeyEnc: 'vivaApiKeyEnc',
  vivaSourceCode: 'vivaSourceCode',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PropertyScalarFieldEnum = (typeof PropertyScalarFieldEnum)[keyof typeof PropertyScalarFieldEnum]


export const BuildingScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  propertyId: 'propertyId',
  name: 'name',
  address: 'address',
  city: 'city',
  postalCode: 'postalCode',
  country: 'country',
  imageUrl: 'imageUrl',
  floors: 'floors',
  basements: 'basements',
  unitsCount: 'unitsCount',
  hasElevator: 'hasElevator',
  hasBoiler: 'hasBoiler',
  hasFireSafety: 'hasFireSafety',
  technicalNotes: 'technicalNotes',
  lat: 'lat',
  lng: 'lng',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BuildingScalarFieldEnum = (typeof BuildingScalarFieldEnum)[keyof typeof BuildingScalarFieldEnum]


export const UnitOccupancyScalarFieldEnum = {
  id: 'id',
  unitId: 'unitId',
  userId: 'userId',
  role: 'role',
  startDate: 'startDate',
  endDate: 'endDate',
  notes: 'notes',
  createdAt: 'createdAt'
} as const

export type UnitOccupancyScalarFieldEnum = (typeof UnitOccupancyScalarFieldEnum)[keyof typeof UnitOccupancyScalarFieldEnum]


export const BuildingFileScalarFieldEnum = {
  id: 'id',
  buildingId: 'buildingId',
  category: 'category',
  name: 'name',
  cdnPath: 'cdnPath',
  url: 'url',
  mimeType: 'mimeType',
  sizeBytes: 'sizeBytes',
  uploadedById: 'uploadedById',
  createdAt: 'createdAt'
} as const

export type BuildingFileScalarFieldEnum = (typeof BuildingFileScalarFieldEnum)[keyof typeof BuildingFileScalarFieldEnum]


export const InfraPointScalarFieldEnum = {
  id: 'id',
  buildingId: 'buildingId',
  name: 'name',
  type: 'type',
  floorLabel: 'floorLabel',
  location: 'location',
  locked: 'locked',
  accessNotes: 'accessNotes',
  keyHolder: 'keyHolder',
  photoUrl: 'photoUrl',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type InfraPointScalarFieldEnum = (typeof InfraPointScalarFieldEnum)[keyof typeof InfraPointScalarFieldEnum]


export const ContactScalarFieldEnum = {
  id: 'id',
  buildingId: 'buildingId',
  name: 'name',
  category: 'category',
  phone: 'phone',
  email: 'email',
  notes: 'notes',
  createdAt: 'createdAt'
} as const

export type ContactScalarFieldEnum = (typeof ContactScalarFieldEnum)[keyof typeof ContactScalarFieldEnum]


export const RecurringTaskScalarFieldEnum = {
  id: 'id',
  buildingId: 'buildingId',
  title: 'title',
  frequency: 'frequency',
  nextDueDate: 'nextDueDate',
  lastDoneDate: 'lastDoneDate',
  vendor: 'vendor',
  notes: 'notes',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RecurringTaskScalarFieldEnum = (typeof RecurringTaskScalarFieldEnum)[keyof typeof RecurringTaskScalarFieldEnum]


export const BuildingExpenseScalarFieldEnum = {
  id: 'id',
  buildingId: 'buildingId',
  month: 'month',
  category: 'category',
  amount: 'amount',
  description: 'description',
  receiptFileId: 'receiptFileId',
  createdAt: 'createdAt'
} as const

export type BuildingExpenseScalarFieldEnum = (typeof BuildingExpenseScalarFieldEnum)[keyof typeof BuildingExpenseScalarFieldEnum]


export const UnitPaymentScalarFieldEnum = {
  id: 'id',
  unitId: 'unitId',
  month: 'month',
  amount: 'amount',
  status: 'status',
  paidAt: 'paidAt',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UnitPaymentScalarFieldEnum = (typeof UnitPaymentScalarFieldEnum)[keyof typeof UnitPaymentScalarFieldEnum]


export const ManagementAssignmentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  propertyId: 'propertyId',
  buildingId: 'buildingId',
  role: 'role',
  createdAt: 'createdAt'
} as const

export type ManagementAssignmentScalarFieldEnum = (typeof ManagementAssignmentScalarFieldEnum)[keyof typeof ManagementAssignmentScalarFieldEnum]


export const CommonAreaScalarFieldEnum = {
  id: 'id',
  buildingId: 'buildingId',
  name: 'name',
  type: 'type',
  floor: 'floor',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CommonAreaScalarFieldEnum = (typeof CommonAreaScalarFieldEnum)[keyof typeof CommonAreaScalarFieldEnum]


export const UnitScalarFieldEnum = {
  id: 'id',
  buildingId: 'buildingId',
  unitNumber: 'unitNumber',
  unitType: 'unitType',
  floor: 'floor',
  areaSqm: 'areaSqm',
  millesimes: 'millesimes',
  ownerId: 'ownerId',
  residentId: 'residentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UnitScalarFieldEnum = (typeof UnitScalarFieldEnum)[keyof typeof UnitScalarFieldEnum]


export const ServiceScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  name: 'name',
  code: 'code',
  description: 'description',
  isCore: 'isCore',
  pricingModel: 'pricingModel',
  price: 'price',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ServiceScalarFieldEnum = (typeof ServiceScalarFieldEnum)[keyof typeof ServiceScalarFieldEnum]


export const PropertyServiceScalarFieldEnum = {
  id: 'id',
  propertyId: 'propertyId',
  serviceId: 'serviceId',
  active: 'active',
  startedAt: 'startedAt',
  endedAt: 'endedAt',
  prepaidPersonMinutes: 'prepaidPersonMinutes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PropertyServiceScalarFieldEnum = (typeof PropertyServiceScalarFieldEnum)[keyof typeof PropertyServiceScalarFieldEnum]


export const ServiceInvoiceScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  period: 'period',
  amount: 'amount',
  status: 'status',
  issuedAt: 'issuedAt',
  dueDate: 'dueDate',
  paidAt: 'paidAt',
  vivaOrderRef: 'vivaOrderRef',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ServiceInvoiceScalarFieldEnum = (typeof ServiceInvoiceScalarFieldEnum)[keyof typeof ServiceInvoiceScalarFieldEnum]


export const ServiceInvoiceLineScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  description: 'description',
  qty: 'qty',
  unitPrice: 'unitPrice',
  amount: 'amount'
} as const

export type ServiceInvoiceLineScalarFieldEnum = (typeof ServiceInvoiceLineScalarFieldEnum)[keyof typeof ServiceInvoiceLineScalarFieldEnum]


export const UserCompanyRoleScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  companyId: 'companyId',
  role: 'role',
  department: 'department',
  position: 'position',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserCompanyRoleScalarFieldEnum = (typeof UserCompanyRoleScalarFieldEnum)[keyof typeof UserCompanyRoleScalarFieldEnum]


export const MenuConfigScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  role: 'role',
  menuItems: 'menuItems',
  isDefault: 'isDefault',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MenuConfigScalarFieldEnum = (typeof MenuConfigScalarFieldEnum)[keyof typeof MenuConfigScalarFieldEnum]


export const AnnouncementScalarFieldEnum = {
  id: 'id',
  buildingId: 'buildingId',
  title: 'title',
  content: 'content',
  imageUrl: 'imageUrl',
  status: 'status',
  publishedAt: 'publishedAt',
  expiresAt: 'expiresAt',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AnnouncementScalarFieldEnum = (typeof AnnouncementScalarFieldEnum)[keyof typeof AnnouncementScalarFieldEnum]


export const Announcement_UserScalarFieldEnum = {
  id: 'id',
  announcementId: 'announcementId',
  userId: 'userId',
  readAt: 'readAt'
} as const

export type Announcement_UserScalarFieldEnum = (typeof Announcement_UserScalarFieldEnum)[keyof typeof Announcement_UserScalarFieldEnum]


export const APIUsageLogScalarFieldEnum = {
  id: 'id',
  apiName: 'apiName',
  endpoint: 'endpoint',
  model: 'model',
  requestCount: 'requestCount',
  tokensUsed: 'tokensUsed',
  bytesProcessed: 'bytesProcessed',
  costPerUnit: 'costPerUnit',
  totalCost: 'totalCost',
  currency: 'currency',
  companyId: 'companyId',
  userId: 'userId',
  status: 'status',
  errorMessage: 'errorMessage',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type APIUsageLogScalarFieldEnum = (typeof APIUsageLogScalarFieldEnum)[keyof typeof APIUsageLogScalarFieldEnum]


export const APICostConfigScalarFieldEnum = {
  id: 'id',
  apiName: 'apiName',
  displayName: 'displayName',
  costModel: 'costModel',
  basePrice: 'basePrice',
  freeQuota: 'freeQuota',
  quotaResetDay: 'quotaResetDay',
  monthlyBudgetLimit: 'monthlyBudgetLimit',
  enabled: 'enabled',
  notes: 'notes',
  documentationUrl: 'documentationUrl',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
} as const

export type APICostConfigScalarFieldEnum = (typeof APICostConfigScalarFieldEnum)[keyof typeof APICostConfigScalarFieldEnum]


export const MonthlyCostSummaryScalarFieldEnum = {
  id: 'id',
  year: 'year',
  month: 'month',
  apiName: 'apiName',
  requestCount: 'requestCount',
  tokensUsed: 'tokensUsed',
  bytesProcessed: 'bytesProcessed',
  totalCost: 'totalCost',
  companyId: 'companyId',
  createdAt: 'createdAt'
} as const

export type MonthlyCostSummaryScalarFieldEnum = (typeof MonthlyCostSummaryScalarFieldEnum)[keyof typeof MonthlyCostSummaryScalarFieldEnum]


export const MaintenanceRequestScalarFieldEnum = {
  id: 'id',
  buildingId: 'buildingId',
  unitId: 'unitId',
  title: 'title',
  description: 'description',
  category: 'category',
  priority: 'priority',
  status: 'status',
  reportedById: 'reportedById',
  assignedToId: 'assignedToId',
  attachmentUrl: 'attachmentUrl',
  scheduledDate: 'scheduledDate',
  completedAt: 'completedAt',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MaintenanceRequestScalarFieldEnum = (typeof MaintenanceRequestScalarFieldEnum)[keyof typeof MaintenanceRequestScalarFieldEnum]


export const CMSPageScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  content: 'content',
  metaDescription: 'metaDescription',
  metaKeywords: 'metaKeywords',
  publishedAt: 'publishedAt',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CMSPageScalarFieldEnum = (typeof CMSPageScalarFieldEnum)[keyof typeof CMSPageScalarFieldEnum]


export const FAQScalarFieldEnum = {
  id: 'id',
  question: 'question',
  answer: 'answer',
  category: 'category',
  order: 'order',
  published: 'published',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type FAQScalarFieldEnum = (typeof FAQScalarFieldEnum)[keyof typeof FAQScalarFieldEnum]


export const PricingTierScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  monthlyPrice: 'monthlyPrice',
  annualPrice: 'annualPrice',
  features: 'features',
  highlighted: 'highlighted',
  order: 'order',
  published: 'published',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PricingTierScalarFieldEnum = (typeof PricingTierScalarFieldEnum)[keyof typeof PricingTierScalarFieldEnum]


export const ContactMessageScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  subject: 'subject',
  message: 'message',
  status: 'status',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ContactMessageScalarFieldEnum = (typeof ContactMessageScalarFieldEnum)[keyof typeof ContactMessageScalarFieldEnum]


export const CookieConsentScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  analytics: 'analytics',
  marketing: 'marketing',
  functional: 'functional',
  essential: 'essential',
  consentedAt: 'consentedAt',
  expiresAt: 'expiresAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CookieConsentScalarFieldEnum = (typeof CookieConsentScalarFieldEnum)[keyof typeof CookieConsentScalarFieldEnum]


export const AppSettingsScalarFieldEnum = {
  id: 'id',
  companyName: 'companyName',
  logoUrl: 'logoUrl',
  logoSquareUrl: 'logoSquareUrl',
  colorPrimary: 'colorPrimary',
  colorPrimaryDk: 'colorPrimaryDk',
  colorAccent: 'colorAccent',
  colorSuccess: 'colorSuccess',
  colorWarning: 'colorWarning',
  colorDanger: 'colorDanger',
  colorPurple: 'colorPurple',
  colorTeal: 'colorTeal',
  contactEmail: 'contactEmail',
  contactPhone: 'contactPhone',
  contactAddress: 'contactAddress',
  websiteUrl: 'websiteUrl',
  updatedAt: 'updatedAt',
  updatedById: 'updatedById'
} as const

export type AppSettingsScalarFieldEnum = (typeof AppSettingsScalarFieldEnum)[keyof typeof AppSettingsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

