
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BuildingFile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BuildingFile
 * 
 */
export type BuildingFileModel = runtime.Types.Result.DefaultSelection<Prisma.$BuildingFilePayload>

export type AggregateBuildingFile = {
  _count: BuildingFileCountAggregateOutputType | null
  _avg: BuildingFileAvgAggregateOutputType | null
  _sum: BuildingFileSumAggregateOutputType | null
  _min: BuildingFileMinAggregateOutputType | null
  _max: BuildingFileMaxAggregateOutputType | null
}

export type BuildingFileAvgAggregateOutputType = {
  sizeBytes: number | null
}

export type BuildingFileSumAggregateOutputType = {
  sizeBytes: number | null
}

export type BuildingFileMinAggregateOutputType = {
  id: string | null
  buildingId: string | null
  category: $Enums.BuildingFileCategory | null
  name: string | null
  cdnPath: string | null
  url: string | null
  mimeType: string | null
  sizeBytes: number | null
  uploadedById: string | null
  createdAt: Date | null
}

export type BuildingFileMaxAggregateOutputType = {
  id: string | null
  buildingId: string | null
  category: $Enums.BuildingFileCategory | null
  name: string | null
  cdnPath: string | null
  url: string | null
  mimeType: string | null
  sizeBytes: number | null
  uploadedById: string | null
  createdAt: Date | null
}

export type BuildingFileCountAggregateOutputType = {
  id: number
  buildingId: number
  category: number
  name: number
  cdnPath: number
  url: number
  mimeType: number
  sizeBytes: number
  uploadedById: number
  createdAt: number
  _all: number
}


export type BuildingFileAvgAggregateInputType = {
  sizeBytes?: true
}

export type BuildingFileSumAggregateInputType = {
  sizeBytes?: true
}

export type BuildingFileMinAggregateInputType = {
  id?: true
  buildingId?: true
  category?: true
  name?: true
  cdnPath?: true
  url?: true
  mimeType?: true
  sizeBytes?: true
  uploadedById?: true
  createdAt?: true
}

export type BuildingFileMaxAggregateInputType = {
  id?: true
  buildingId?: true
  category?: true
  name?: true
  cdnPath?: true
  url?: true
  mimeType?: true
  sizeBytes?: true
  uploadedById?: true
  createdAt?: true
}

export type BuildingFileCountAggregateInputType = {
  id?: true
  buildingId?: true
  category?: true
  name?: true
  cdnPath?: true
  url?: true
  mimeType?: true
  sizeBytes?: true
  uploadedById?: true
  createdAt?: true
  _all?: true
}

export type BuildingFileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BuildingFile to aggregate.
   */
  where?: Prisma.BuildingFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuildingFiles to fetch.
   */
  orderBy?: Prisma.BuildingFileOrderByWithRelationInput | Prisma.BuildingFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BuildingFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuildingFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuildingFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BuildingFiles
  **/
  _count?: true | BuildingFileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BuildingFileAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BuildingFileSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BuildingFileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BuildingFileMaxAggregateInputType
}

export type GetBuildingFileAggregateType<T extends BuildingFileAggregateArgs> = {
      [P in keyof T & keyof AggregateBuildingFile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBuildingFile[P]>
    : Prisma.GetScalarType<T[P], AggregateBuildingFile[P]>
}




export type BuildingFileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BuildingFileWhereInput
  orderBy?: Prisma.BuildingFileOrderByWithAggregationInput | Prisma.BuildingFileOrderByWithAggregationInput[]
  by: Prisma.BuildingFileScalarFieldEnum[] | Prisma.BuildingFileScalarFieldEnum
  having?: Prisma.BuildingFileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BuildingFileCountAggregateInputType | true
  _avg?: BuildingFileAvgAggregateInputType
  _sum?: BuildingFileSumAggregateInputType
  _min?: BuildingFileMinAggregateInputType
  _max?: BuildingFileMaxAggregateInputType
}

export type BuildingFileGroupByOutputType = {
  id: string
  buildingId: string
  category: $Enums.BuildingFileCategory
  name: string
  cdnPath: string
  url: string
  mimeType: string | null
  sizeBytes: number | null
  uploadedById: string | null
  createdAt: Date
  _count: BuildingFileCountAggregateOutputType | null
  _avg: BuildingFileAvgAggregateOutputType | null
  _sum: BuildingFileSumAggregateOutputType | null
  _min: BuildingFileMinAggregateOutputType | null
  _max: BuildingFileMaxAggregateOutputType | null
}

export type GetBuildingFileGroupByPayload<T extends BuildingFileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BuildingFileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BuildingFileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BuildingFileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BuildingFileGroupByOutputType[P]>
      }
    >
  >



export type BuildingFileWhereInput = {
  AND?: Prisma.BuildingFileWhereInput | Prisma.BuildingFileWhereInput[]
  OR?: Prisma.BuildingFileWhereInput[]
  NOT?: Prisma.BuildingFileWhereInput | Prisma.BuildingFileWhereInput[]
  id?: Prisma.StringFilter<"BuildingFile"> | string
  buildingId?: Prisma.StringFilter<"BuildingFile"> | string
  category?: Prisma.EnumBuildingFileCategoryFilter<"BuildingFile"> | $Enums.BuildingFileCategory
  name?: Prisma.StringFilter<"BuildingFile"> | string
  cdnPath?: Prisma.StringFilter<"BuildingFile"> | string
  url?: Prisma.StringFilter<"BuildingFile"> | string
  mimeType?: Prisma.StringNullableFilter<"BuildingFile"> | string | null
  sizeBytes?: Prisma.IntNullableFilter<"BuildingFile"> | number | null
  uploadedById?: Prisma.StringNullableFilter<"BuildingFile"> | string | null
  createdAt?: Prisma.DateTimeFilter<"BuildingFile"> | Date | string
  building?: Prisma.XOR<Prisma.BuildingScalarRelationFilter, Prisma.BuildingWhereInput>
  expenseLinks?: Prisma.BuildingExpenseListRelationFilter
}

export type BuildingFileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  name?: Prisma.SortOrder
  cdnPath?: Prisma.SortOrder
  url?: Prisma.SortOrder
  mimeType?: Prisma.SortOrderInput | Prisma.SortOrder
  sizeBytes?: Prisma.SortOrderInput | Prisma.SortOrder
  uploadedById?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  building?: Prisma.BuildingOrderByWithRelationInput
  expenseLinks?: Prisma.BuildingExpenseOrderByRelationAggregateInput
}

export type BuildingFileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BuildingFileWhereInput | Prisma.BuildingFileWhereInput[]
  OR?: Prisma.BuildingFileWhereInput[]
  NOT?: Prisma.BuildingFileWhereInput | Prisma.BuildingFileWhereInput[]
  buildingId?: Prisma.StringFilter<"BuildingFile"> | string
  category?: Prisma.EnumBuildingFileCategoryFilter<"BuildingFile"> | $Enums.BuildingFileCategory
  name?: Prisma.StringFilter<"BuildingFile"> | string
  cdnPath?: Prisma.StringFilter<"BuildingFile"> | string
  url?: Prisma.StringFilter<"BuildingFile"> | string
  mimeType?: Prisma.StringNullableFilter<"BuildingFile"> | string | null
  sizeBytes?: Prisma.IntNullableFilter<"BuildingFile"> | number | null
  uploadedById?: Prisma.StringNullableFilter<"BuildingFile"> | string | null
  createdAt?: Prisma.DateTimeFilter<"BuildingFile"> | Date | string
  building?: Prisma.XOR<Prisma.BuildingScalarRelationFilter, Prisma.BuildingWhereInput>
  expenseLinks?: Prisma.BuildingExpenseListRelationFilter
}, "id">

export type BuildingFileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  name?: Prisma.SortOrder
  cdnPath?: Prisma.SortOrder
  url?: Prisma.SortOrder
  mimeType?: Prisma.SortOrderInput | Prisma.SortOrder
  sizeBytes?: Prisma.SortOrderInput | Prisma.SortOrder
  uploadedById?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.BuildingFileCountOrderByAggregateInput
  _avg?: Prisma.BuildingFileAvgOrderByAggregateInput
  _max?: Prisma.BuildingFileMaxOrderByAggregateInput
  _min?: Prisma.BuildingFileMinOrderByAggregateInput
  _sum?: Prisma.BuildingFileSumOrderByAggregateInput
}

export type BuildingFileScalarWhereWithAggregatesInput = {
  AND?: Prisma.BuildingFileScalarWhereWithAggregatesInput | Prisma.BuildingFileScalarWhereWithAggregatesInput[]
  OR?: Prisma.BuildingFileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BuildingFileScalarWhereWithAggregatesInput | Prisma.BuildingFileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BuildingFile"> | string
  buildingId?: Prisma.StringWithAggregatesFilter<"BuildingFile"> | string
  category?: Prisma.EnumBuildingFileCategoryWithAggregatesFilter<"BuildingFile"> | $Enums.BuildingFileCategory
  name?: Prisma.StringWithAggregatesFilter<"BuildingFile"> | string
  cdnPath?: Prisma.StringWithAggregatesFilter<"BuildingFile"> | string
  url?: Prisma.StringWithAggregatesFilter<"BuildingFile"> | string
  mimeType?: Prisma.StringNullableWithAggregatesFilter<"BuildingFile"> | string | null
  sizeBytes?: Prisma.IntNullableWithAggregatesFilter<"BuildingFile"> | number | null
  uploadedById?: Prisma.StringNullableWithAggregatesFilter<"BuildingFile"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BuildingFile"> | Date | string
}

export type BuildingFileCreateInput = {
  id?: string
  category?: $Enums.BuildingFileCategory
  name: string
  cdnPath: string
  url: string
  mimeType?: string | null
  sizeBytes?: number | null
  uploadedById?: string | null
  createdAt?: Date | string
  building: Prisma.BuildingCreateNestedOneWithoutFilesInput
  expenseLinks?: Prisma.BuildingExpenseCreateNestedManyWithoutReceiptFileInput
}

export type BuildingFileUncheckedCreateInput = {
  id?: string
  buildingId: string
  category?: $Enums.BuildingFileCategory
  name: string
  cdnPath: string
  url: string
  mimeType?: string | null
  sizeBytes?: number | null
  uploadedById?: string | null
  createdAt?: Date | string
  expenseLinks?: Prisma.BuildingExpenseUncheckedCreateNestedManyWithoutReceiptFileInput
}

export type BuildingFileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBuildingFileCategoryFieldUpdateOperationsInput | $Enums.BuildingFileCategory
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  building?: Prisma.BuildingUpdateOneRequiredWithoutFilesNestedInput
  expenseLinks?: Prisma.BuildingExpenseUpdateManyWithoutReceiptFileNestedInput
}

export type BuildingFileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBuildingFileCategoryFieldUpdateOperationsInput | $Enums.BuildingFileCategory
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expenseLinks?: Prisma.BuildingExpenseUncheckedUpdateManyWithoutReceiptFileNestedInput
}

export type BuildingFileCreateManyInput = {
  id?: string
  buildingId: string
  category?: $Enums.BuildingFileCategory
  name: string
  cdnPath: string
  url: string
  mimeType?: string | null
  sizeBytes?: number | null
  uploadedById?: string | null
  createdAt?: Date | string
}

export type BuildingFileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBuildingFileCategoryFieldUpdateOperationsInput | $Enums.BuildingFileCategory
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BuildingFileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBuildingFileCategoryFieldUpdateOperationsInput | $Enums.BuildingFileCategory
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BuildingFileListRelationFilter = {
  every?: Prisma.BuildingFileWhereInput
  some?: Prisma.BuildingFileWhereInput
  none?: Prisma.BuildingFileWhereInput
}

export type BuildingFileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BuildingFileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  name?: Prisma.SortOrder
  cdnPath?: Prisma.SortOrder
  url?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  uploadedById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BuildingFileAvgOrderByAggregateInput = {
  sizeBytes?: Prisma.SortOrder
}

export type BuildingFileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  name?: Prisma.SortOrder
  cdnPath?: Prisma.SortOrder
  url?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  uploadedById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BuildingFileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  name?: Prisma.SortOrder
  cdnPath?: Prisma.SortOrder
  url?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  uploadedById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BuildingFileSumOrderByAggregateInput = {
  sizeBytes?: Prisma.SortOrder
}

export type BuildingFileNullableScalarRelationFilter = {
  is?: Prisma.BuildingFileWhereInput | null
  isNot?: Prisma.BuildingFileWhereInput | null
}

export type BuildingFileCreateNestedManyWithoutBuildingInput = {
  create?: Prisma.XOR<Prisma.BuildingFileCreateWithoutBuildingInput, Prisma.BuildingFileUncheckedCreateWithoutBuildingInput> | Prisma.BuildingFileCreateWithoutBuildingInput[] | Prisma.BuildingFileUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.BuildingFileCreateOrConnectWithoutBuildingInput | Prisma.BuildingFileCreateOrConnectWithoutBuildingInput[]
  createMany?: Prisma.BuildingFileCreateManyBuildingInputEnvelope
  connect?: Prisma.BuildingFileWhereUniqueInput | Prisma.BuildingFileWhereUniqueInput[]
}

export type BuildingFileUncheckedCreateNestedManyWithoutBuildingInput = {
  create?: Prisma.XOR<Prisma.BuildingFileCreateWithoutBuildingInput, Prisma.BuildingFileUncheckedCreateWithoutBuildingInput> | Prisma.BuildingFileCreateWithoutBuildingInput[] | Prisma.BuildingFileUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.BuildingFileCreateOrConnectWithoutBuildingInput | Prisma.BuildingFileCreateOrConnectWithoutBuildingInput[]
  createMany?: Prisma.BuildingFileCreateManyBuildingInputEnvelope
  connect?: Prisma.BuildingFileWhereUniqueInput | Prisma.BuildingFileWhereUniqueInput[]
}

export type BuildingFileUpdateManyWithoutBuildingNestedInput = {
  create?: Prisma.XOR<Prisma.BuildingFileCreateWithoutBuildingInput, Prisma.BuildingFileUncheckedCreateWithoutBuildingInput> | Prisma.BuildingFileCreateWithoutBuildingInput[] | Prisma.BuildingFileUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.BuildingFileCreateOrConnectWithoutBuildingInput | Prisma.BuildingFileCreateOrConnectWithoutBuildingInput[]
  upsert?: Prisma.BuildingFileUpsertWithWhereUniqueWithoutBuildingInput | Prisma.BuildingFileUpsertWithWhereUniqueWithoutBuildingInput[]
  createMany?: Prisma.BuildingFileCreateManyBuildingInputEnvelope
  set?: Prisma.BuildingFileWhereUniqueInput | Prisma.BuildingFileWhereUniqueInput[]
  disconnect?: Prisma.BuildingFileWhereUniqueInput | Prisma.BuildingFileWhereUniqueInput[]
  delete?: Prisma.BuildingFileWhereUniqueInput | Prisma.BuildingFileWhereUniqueInput[]
  connect?: Prisma.BuildingFileWhereUniqueInput | Prisma.BuildingFileWhereUniqueInput[]
  update?: Prisma.BuildingFileUpdateWithWhereUniqueWithoutBuildingInput | Prisma.BuildingFileUpdateWithWhereUniqueWithoutBuildingInput[]
  updateMany?: Prisma.BuildingFileUpdateManyWithWhereWithoutBuildingInput | Prisma.BuildingFileUpdateManyWithWhereWithoutBuildingInput[]
  deleteMany?: Prisma.BuildingFileScalarWhereInput | Prisma.BuildingFileScalarWhereInput[]
}

export type BuildingFileUncheckedUpdateManyWithoutBuildingNestedInput = {
  create?: Prisma.XOR<Prisma.BuildingFileCreateWithoutBuildingInput, Prisma.BuildingFileUncheckedCreateWithoutBuildingInput> | Prisma.BuildingFileCreateWithoutBuildingInput[] | Prisma.BuildingFileUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.BuildingFileCreateOrConnectWithoutBuildingInput | Prisma.BuildingFileCreateOrConnectWithoutBuildingInput[]
  upsert?: Prisma.BuildingFileUpsertWithWhereUniqueWithoutBuildingInput | Prisma.BuildingFileUpsertWithWhereUniqueWithoutBuildingInput[]
  createMany?: Prisma.BuildingFileCreateManyBuildingInputEnvelope
  set?: Prisma.BuildingFileWhereUniqueInput | Prisma.BuildingFileWhereUniqueInput[]
  disconnect?: Prisma.BuildingFileWhereUniqueInput | Prisma.BuildingFileWhereUniqueInput[]
  delete?: Prisma.BuildingFileWhereUniqueInput | Prisma.BuildingFileWhereUniqueInput[]
  connect?: Prisma.BuildingFileWhereUniqueInput | Prisma.BuildingFileWhereUniqueInput[]
  update?: Prisma.BuildingFileUpdateWithWhereUniqueWithoutBuildingInput | Prisma.BuildingFileUpdateWithWhereUniqueWithoutBuildingInput[]
  updateMany?: Prisma.BuildingFileUpdateManyWithWhereWithoutBuildingInput | Prisma.BuildingFileUpdateManyWithWhereWithoutBuildingInput[]
  deleteMany?: Prisma.BuildingFileScalarWhereInput | Prisma.BuildingFileScalarWhereInput[]
}

export type EnumBuildingFileCategoryFieldUpdateOperationsInput = {
  set?: $Enums.BuildingFileCategory
}

export type BuildingFileCreateNestedOneWithoutExpenseLinksInput = {
  create?: Prisma.XOR<Prisma.BuildingFileCreateWithoutExpenseLinksInput, Prisma.BuildingFileUncheckedCreateWithoutExpenseLinksInput>
  connectOrCreate?: Prisma.BuildingFileCreateOrConnectWithoutExpenseLinksInput
  connect?: Prisma.BuildingFileWhereUniqueInput
}

export type BuildingFileUpdateOneWithoutExpenseLinksNestedInput = {
  create?: Prisma.XOR<Prisma.BuildingFileCreateWithoutExpenseLinksInput, Prisma.BuildingFileUncheckedCreateWithoutExpenseLinksInput>
  connectOrCreate?: Prisma.BuildingFileCreateOrConnectWithoutExpenseLinksInput
  upsert?: Prisma.BuildingFileUpsertWithoutExpenseLinksInput
  disconnect?: Prisma.BuildingFileWhereInput | boolean
  delete?: Prisma.BuildingFileWhereInput | boolean
  connect?: Prisma.BuildingFileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BuildingFileUpdateToOneWithWhereWithoutExpenseLinksInput, Prisma.BuildingFileUpdateWithoutExpenseLinksInput>, Prisma.BuildingFileUncheckedUpdateWithoutExpenseLinksInput>
}

export type BuildingFileCreateWithoutBuildingInput = {
  id?: string
  category?: $Enums.BuildingFileCategory
  name: string
  cdnPath: string
  url: string
  mimeType?: string | null
  sizeBytes?: number | null
  uploadedById?: string | null
  createdAt?: Date | string
  expenseLinks?: Prisma.BuildingExpenseCreateNestedManyWithoutReceiptFileInput
}

export type BuildingFileUncheckedCreateWithoutBuildingInput = {
  id?: string
  category?: $Enums.BuildingFileCategory
  name: string
  cdnPath: string
  url: string
  mimeType?: string | null
  sizeBytes?: number | null
  uploadedById?: string | null
  createdAt?: Date | string
  expenseLinks?: Prisma.BuildingExpenseUncheckedCreateNestedManyWithoutReceiptFileInput
}

export type BuildingFileCreateOrConnectWithoutBuildingInput = {
  where: Prisma.BuildingFileWhereUniqueInput
  create: Prisma.XOR<Prisma.BuildingFileCreateWithoutBuildingInput, Prisma.BuildingFileUncheckedCreateWithoutBuildingInput>
}

export type BuildingFileCreateManyBuildingInputEnvelope = {
  data: Prisma.BuildingFileCreateManyBuildingInput | Prisma.BuildingFileCreateManyBuildingInput[]
  skipDuplicates?: boolean
}

export type BuildingFileUpsertWithWhereUniqueWithoutBuildingInput = {
  where: Prisma.BuildingFileWhereUniqueInput
  update: Prisma.XOR<Prisma.BuildingFileUpdateWithoutBuildingInput, Prisma.BuildingFileUncheckedUpdateWithoutBuildingInput>
  create: Prisma.XOR<Prisma.BuildingFileCreateWithoutBuildingInput, Prisma.BuildingFileUncheckedCreateWithoutBuildingInput>
}

export type BuildingFileUpdateWithWhereUniqueWithoutBuildingInput = {
  where: Prisma.BuildingFileWhereUniqueInput
  data: Prisma.XOR<Prisma.BuildingFileUpdateWithoutBuildingInput, Prisma.BuildingFileUncheckedUpdateWithoutBuildingInput>
}

export type BuildingFileUpdateManyWithWhereWithoutBuildingInput = {
  where: Prisma.BuildingFileScalarWhereInput
  data: Prisma.XOR<Prisma.BuildingFileUpdateManyMutationInput, Prisma.BuildingFileUncheckedUpdateManyWithoutBuildingInput>
}

export type BuildingFileScalarWhereInput = {
  AND?: Prisma.BuildingFileScalarWhereInput | Prisma.BuildingFileScalarWhereInput[]
  OR?: Prisma.BuildingFileScalarWhereInput[]
  NOT?: Prisma.BuildingFileScalarWhereInput | Prisma.BuildingFileScalarWhereInput[]
  id?: Prisma.StringFilter<"BuildingFile"> | string
  buildingId?: Prisma.StringFilter<"BuildingFile"> | string
  category?: Prisma.EnumBuildingFileCategoryFilter<"BuildingFile"> | $Enums.BuildingFileCategory
  name?: Prisma.StringFilter<"BuildingFile"> | string
  cdnPath?: Prisma.StringFilter<"BuildingFile"> | string
  url?: Prisma.StringFilter<"BuildingFile"> | string
  mimeType?: Prisma.StringNullableFilter<"BuildingFile"> | string | null
  sizeBytes?: Prisma.IntNullableFilter<"BuildingFile"> | number | null
  uploadedById?: Prisma.StringNullableFilter<"BuildingFile"> | string | null
  createdAt?: Prisma.DateTimeFilter<"BuildingFile"> | Date | string
}

export type BuildingFileCreateWithoutExpenseLinksInput = {
  id?: string
  category?: $Enums.BuildingFileCategory
  name: string
  cdnPath: string
  url: string
  mimeType?: string | null
  sizeBytes?: number | null
  uploadedById?: string | null
  createdAt?: Date | string
  building: Prisma.BuildingCreateNestedOneWithoutFilesInput
}

export type BuildingFileUncheckedCreateWithoutExpenseLinksInput = {
  id?: string
  buildingId: string
  category?: $Enums.BuildingFileCategory
  name: string
  cdnPath: string
  url: string
  mimeType?: string | null
  sizeBytes?: number | null
  uploadedById?: string | null
  createdAt?: Date | string
}

export type BuildingFileCreateOrConnectWithoutExpenseLinksInput = {
  where: Prisma.BuildingFileWhereUniqueInput
  create: Prisma.XOR<Prisma.BuildingFileCreateWithoutExpenseLinksInput, Prisma.BuildingFileUncheckedCreateWithoutExpenseLinksInput>
}

export type BuildingFileUpsertWithoutExpenseLinksInput = {
  update: Prisma.XOR<Prisma.BuildingFileUpdateWithoutExpenseLinksInput, Prisma.BuildingFileUncheckedUpdateWithoutExpenseLinksInput>
  create: Prisma.XOR<Prisma.BuildingFileCreateWithoutExpenseLinksInput, Prisma.BuildingFileUncheckedCreateWithoutExpenseLinksInput>
  where?: Prisma.BuildingFileWhereInput
}

export type BuildingFileUpdateToOneWithWhereWithoutExpenseLinksInput = {
  where?: Prisma.BuildingFileWhereInput
  data: Prisma.XOR<Prisma.BuildingFileUpdateWithoutExpenseLinksInput, Prisma.BuildingFileUncheckedUpdateWithoutExpenseLinksInput>
}

export type BuildingFileUpdateWithoutExpenseLinksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBuildingFileCategoryFieldUpdateOperationsInput | $Enums.BuildingFileCategory
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  building?: Prisma.BuildingUpdateOneRequiredWithoutFilesNestedInput
}

export type BuildingFileUncheckedUpdateWithoutExpenseLinksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBuildingFileCategoryFieldUpdateOperationsInput | $Enums.BuildingFileCategory
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BuildingFileCreateManyBuildingInput = {
  id?: string
  category?: $Enums.BuildingFileCategory
  name: string
  cdnPath: string
  url: string
  mimeType?: string | null
  sizeBytes?: number | null
  uploadedById?: string | null
  createdAt?: Date | string
}

export type BuildingFileUpdateWithoutBuildingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBuildingFileCategoryFieldUpdateOperationsInput | $Enums.BuildingFileCategory
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expenseLinks?: Prisma.BuildingExpenseUpdateManyWithoutReceiptFileNestedInput
}

export type BuildingFileUncheckedUpdateWithoutBuildingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBuildingFileCategoryFieldUpdateOperationsInput | $Enums.BuildingFileCategory
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expenseLinks?: Prisma.BuildingExpenseUncheckedUpdateManyWithoutReceiptFileNestedInput
}

export type BuildingFileUncheckedUpdateManyWithoutBuildingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBuildingFileCategoryFieldUpdateOperationsInput | $Enums.BuildingFileCategory
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type BuildingFileCountOutputType
 */

export type BuildingFileCountOutputType = {
  expenseLinks: number
}

export type BuildingFileCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  expenseLinks?: boolean | BuildingFileCountOutputTypeCountExpenseLinksArgs
}

/**
 * BuildingFileCountOutputType without action
 */
export type BuildingFileCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildingFileCountOutputType
   */
  select?: Prisma.BuildingFileCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BuildingFileCountOutputType without action
 */
export type BuildingFileCountOutputTypeCountExpenseLinksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BuildingExpenseWhereInput
}


export type BuildingFileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buildingId?: boolean
  category?: boolean
  name?: boolean
  cdnPath?: boolean
  url?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  uploadedById?: boolean
  createdAt?: boolean
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
  expenseLinks?: boolean | Prisma.BuildingFile$expenseLinksArgs<ExtArgs>
  _count?: boolean | Prisma.BuildingFileCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buildingFile"]>

export type BuildingFileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buildingId?: boolean
  category?: boolean
  name?: boolean
  cdnPath?: boolean
  url?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  uploadedById?: boolean
  createdAt?: boolean
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buildingFile"]>

export type BuildingFileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buildingId?: boolean
  category?: boolean
  name?: boolean
  cdnPath?: boolean
  url?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  uploadedById?: boolean
  createdAt?: boolean
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buildingFile"]>

export type BuildingFileSelectScalar = {
  id?: boolean
  buildingId?: boolean
  category?: boolean
  name?: boolean
  cdnPath?: boolean
  url?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  uploadedById?: boolean
  createdAt?: boolean
}

export type BuildingFileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "buildingId" | "category" | "name" | "cdnPath" | "url" | "mimeType" | "sizeBytes" | "uploadedById" | "createdAt", ExtArgs["result"]["buildingFile"]>
export type BuildingFileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
  expenseLinks?: boolean | Prisma.BuildingFile$expenseLinksArgs<ExtArgs>
  _count?: boolean | Prisma.BuildingFileCountOutputTypeDefaultArgs<ExtArgs>
}
export type BuildingFileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
}
export type BuildingFileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
}

export type $BuildingFilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BuildingFile"
  objects: {
    building: Prisma.$BuildingPayload<ExtArgs>
    expenseLinks: Prisma.$BuildingExpensePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    buildingId: string
    category: $Enums.BuildingFileCategory
    name: string
    cdnPath: string
    url: string
    mimeType: string | null
    sizeBytes: number | null
    uploadedById: string | null
    createdAt: Date
  }, ExtArgs["result"]["buildingFile"]>
  composites: {}
}

export type BuildingFileGetPayload<S extends boolean | null | undefined | BuildingFileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BuildingFilePayload, S>

export type BuildingFileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BuildingFileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BuildingFileCountAggregateInputType | true
  }

export interface BuildingFileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BuildingFile'], meta: { name: 'BuildingFile' } }
  /**
   * Find zero or one BuildingFile that matches the filter.
   * @param {BuildingFileFindUniqueArgs} args - Arguments to find a BuildingFile
   * @example
   * // Get one BuildingFile
   * const buildingFile = await prisma.buildingFile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BuildingFileFindUniqueArgs>(args: Prisma.SelectSubset<T, BuildingFileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BuildingFileClient<runtime.Types.Result.GetResult<Prisma.$BuildingFilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BuildingFile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BuildingFileFindUniqueOrThrowArgs} args - Arguments to find a BuildingFile
   * @example
   * // Get one BuildingFile
   * const buildingFile = await prisma.buildingFile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BuildingFileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BuildingFileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BuildingFileClient<runtime.Types.Result.GetResult<Prisma.$BuildingFilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BuildingFile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuildingFileFindFirstArgs} args - Arguments to find a BuildingFile
   * @example
   * // Get one BuildingFile
   * const buildingFile = await prisma.buildingFile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BuildingFileFindFirstArgs>(args?: Prisma.SelectSubset<T, BuildingFileFindFirstArgs<ExtArgs>>): Prisma.Prisma__BuildingFileClient<runtime.Types.Result.GetResult<Prisma.$BuildingFilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BuildingFile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuildingFileFindFirstOrThrowArgs} args - Arguments to find a BuildingFile
   * @example
   * // Get one BuildingFile
   * const buildingFile = await prisma.buildingFile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BuildingFileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BuildingFileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BuildingFileClient<runtime.Types.Result.GetResult<Prisma.$BuildingFilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BuildingFiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuildingFileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BuildingFiles
   * const buildingFiles = await prisma.buildingFile.findMany()
   * 
   * // Get first 10 BuildingFiles
   * const buildingFiles = await prisma.buildingFile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const buildingFileWithIdOnly = await prisma.buildingFile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BuildingFileFindManyArgs>(args?: Prisma.SelectSubset<T, BuildingFileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuildingFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BuildingFile.
   * @param {BuildingFileCreateArgs} args - Arguments to create a BuildingFile.
   * @example
   * // Create one BuildingFile
   * const BuildingFile = await prisma.buildingFile.create({
   *   data: {
   *     // ... data to create a BuildingFile
   *   }
   * })
   * 
   */
  create<T extends BuildingFileCreateArgs>(args: Prisma.SelectSubset<T, BuildingFileCreateArgs<ExtArgs>>): Prisma.Prisma__BuildingFileClient<runtime.Types.Result.GetResult<Prisma.$BuildingFilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BuildingFiles.
   * @param {BuildingFileCreateManyArgs} args - Arguments to create many BuildingFiles.
   * @example
   * // Create many BuildingFiles
   * const buildingFile = await prisma.buildingFile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BuildingFileCreateManyArgs>(args?: Prisma.SelectSubset<T, BuildingFileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BuildingFiles and returns the data saved in the database.
   * @param {BuildingFileCreateManyAndReturnArgs} args - Arguments to create many BuildingFiles.
   * @example
   * // Create many BuildingFiles
   * const buildingFile = await prisma.buildingFile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BuildingFiles and only return the `id`
   * const buildingFileWithIdOnly = await prisma.buildingFile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BuildingFileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BuildingFileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuildingFilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BuildingFile.
   * @param {BuildingFileDeleteArgs} args - Arguments to delete one BuildingFile.
   * @example
   * // Delete one BuildingFile
   * const BuildingFile = await prisma.buildingFile.delete({
   *   where: {
   *     // ... filter to delete one BuildingFile
   *   }
   * })
   * 
   */
  delete<T extends BuildingFileDeleteArgs>(args: Prisma.SelectSubset<T, BuildingFileDeleteArgs<ExtArgs>>): Prisma.Prisma__BuildingFileClient<runtime.Types.Result.GetResult<Prisma.$BuildingFilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BuildingFile.
   * @param {BuildingFileUpdateArgs} args - Arguments to update one BuildingFile.
   * @example
   * // Update one BuildingFile
   * const buildingFile = await prisma.buildingFile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BuildingFileUpdateArgs>(args: Prisma.SelectSubset<T, BuildingFileUpdateArgs<ExtArgs>>): Prisma.Prisma__BuildingFileClient<runtime.Types.Result.GetResult<Prisma.$BuildingFilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BuildingFiles.
   * @param {BuildingFileDeleteManyArgs} args - Arguments to filter BuildingFiles to delete.
   * @example
   * // Delete a few BuildingFiles
   * const { count } = await prisma.buildingFile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BuildingFileDeleteManyArgs>(args?: Prisma.SelectSubset<T, BuildingFileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BuildingFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuildingFileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BuildingFiles
   * const buildingFile = await prisma.buildingFile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BuildingFileUpdateManyArgs>(args: Prisma.SelectSubset<T, BuildingFileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BuildingFiles and returns the data updated in the database.
   * @param {BuildingFileUpdateManyAndReturnArgs} args - Arguments to update many BuildingFiles.
   * @example
   * // Update many BuildingFiles
   * const buildingFile = await prisma.buildingFile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BuildingFiles and only return the `id`
   * const buildingFileWithIdOnly = await prisma.buildingFile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BuildingFileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BuildingFileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuildingFilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BuildingFile.
   * @param {BuildingFileUpsertArgs} args - Arguments to update or create a BuildingFile.
   * @example
   * // Update or create a BuildingFile
   * const buildingFile = await prisma.buildingFile.upsert({
   *   create: {
   *     // ... data to create a BuildingFile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BuildingFile we want to update
   *   }
   * })
   */
  upsert<T extends BuildingFileUpsertArgs>(args: Prisma.SelectSubset<T, BuildingFileUpsertArgs<ExtArgs>>): Prisma.Prisma__BuildingFileClient<runtime.Types.Result.GetResult<Prisma.$BuildingFilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BuildingFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuildingFileCountArgs} args - Arguments to filter BuildingFiles to count.
   * @example
   * // Count the number of BuildingFiles
   * const count = await prisma.buildingFile.count({
   *   where: {
   *     // ... the filter for the BuildingFiles we want to count
   *   }
   * })
  **/
  count<T extends BuildingFileCountArgs>(
    args?: Prisma.Subset<T, BuildingFileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BuildingFileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BuildingFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuildingFileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BuildingFileAggregateArgs>(args: Prisma.Subset<T, BuildingFileAggregateArgs>): Prisma.PrismaPromise<GetBuildingFileAggregateType<T>>

  /**
   * Group by BuildingFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuildingFileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BuildingFileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BuildingFileGroupByArgs['orderBy'] }
      : { orderBy?: BuildingFileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BuildingFileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBuildingFileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BuildingFile model
 */
readonly fields: BuildingFileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BuildingFile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BuildingFileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  building<T extends Prisma.BuildingDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BuildingDefaultArgs<ExtArgs>>): Prisma.Prisma__BuildingClient<runtime.Types.Result.GetResult<Prisma.$BuildingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  expenseLinks<T extends Prisma.BuildingFile$expenseLinksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BuildingFile$expenseLinksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuildingExpensePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BuildingFile model
 */
export interface BuildingFileFieldRefs {
  readonly id: Prisma.FieldRef<"BuildingFile", 'String'>
  readonly buildingId: Prisma.FieldRef<"BuildingFile", 'String'>
  readonly category: Prisma.FieldRef<"BuildingFile", 'BuildingFileCategory'>
  readonly name: Prisma.FieldRef<"BuildingFile", 'String'>
  readonly cdnPath: Prisma.FieldRef<"BuildingFile", 'String'>
  readonly url: Prisma.FieldRef<"BuildingFile", 'String'>
  readonly mimeType: Prisma.FieldRef<"BuildingFile", 'String'>
  readonly sizeBytes: Prisma.FieldRef<"BuildingFile", 'Int'>
  readonly uploadedById: Prisma.FieldRef<"BuildingFile", 'String'>
  readonly createdAt: Prisma.FieldRef<"BuildingFile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BuildingFile findUnique
 */
export type BuildingFileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildingFile
   */
  select?: Prisma.BuildingFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildingFile
   */
  omit?: Prisma.BuildingFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildingFileInclude<ExtArgs> | null
  /**
   * Filter, which BuildingFile to fetch.
   */
  where: Prisma.BuildingFileWhereUniqueInput
}

/**
 * BuildingFile findUniqueOrThrow
 */
export type BuildingFileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildingFile
   */
  select?: Prisma.BuildingFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildingFile
   */
  omit?: Prisma.BuildingFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildingFileInclude<ExtArgs> | null
  /**
   * Filter, which BuildingFile to fetch.
   */
  where: Prisma.BuildingFileWhereUniqueInput
}

/**
 * BuildingFile findFirst
 */
export type BuildingFileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildingFile
   */
  select?: Prisma.BuildingFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildingFile
   */
  omit?: Prisma.BuildingFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildingFileInclude<ExtArgs> | null
  /**
   * Filter, which BuildingFile to fetch.
   */
  where?: Prisma.BuildingFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuildingFiles to fetch.
   */
  orderBy?: Prisma.BuildingFileOrderByWithRelationInput | Prisma.BuildingFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BuildingFiles.
   */
  cursor?: Prisma.BuildingFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuildingFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuildingFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BuildingFiles.
   */
  distinct?: Prisma.BuildingFileScalarFieldEnum | Prisma.BuildingFileScalarFieldEnum[]
}

/**
 * BuildingFile findFirstOrThrow
 */
export type BuildingFileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildingFile
   */
  select?: Prisma.BuildingFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildingFile
   */
  omit?: Prisma.BuildingFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildingFileInclude<ExtArgs> | null
  /**
   * Filter, which BuildingFile to fetch.
   */
  where?: Prisma.BuildingFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuildingFiles to fetch.
   */
  orderBy?: Prisma.BuildingFileOrderByWithRelationInput | Prisma.BuildingFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BuildingFiles.
   */
  cursor?: Prisma.BuildingFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuildingFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuildingFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BuildingFiles.
   */
  distinct?: Prisma.BuildingFileScalarFieldEnum | Prisma.BuildingFileScalarFieldEnum[]
}

/**
 * BuildingFile findMany
 */
export type BuildingFileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildingFile
   */
  select?: Prisma.BuildingFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildingFile
   */
  omit?: Prisma.BuildingFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildingFileInclude<ExtArgs> | null
  /**
   * Filter, which BuildingFiles to fetch.
   */
  where?: Prisma.BuildingFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuildingFiles to fetch.
   */
  orderBy?: Prisma.BuildingFileOrderByWithRelationInput | Prisma.BuildingFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BuildingFiles.
   */
  cursor?: Prisma.BuildingFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuildingFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuildingFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BuildingFiles.
   */
  distinct?: Prisma.BuildingFileScalarFieldEnum | Prisma.BuildingFileScalarFieldEnum[]
}

/**
 * BuildingFile create
 */
export type BuildingFileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildingFile
   */
  select?: Prisma.BuildingFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildingFile
   */
  omit?: Prisma.BuildingFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildingFileInclude<ExtArgs> | null
  /**
   * The data needed to create a BuildingFile.
   */
  data: Prisma.XOR<Prisma.BuildingFileCreateInput, Prisma.BuildingFileUncheckedCreateInput>
}

/**
 * BuildingFile createMany
 */
export type BuildingFileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BuildingFiles.
   */
  data: Prisma.BuildingFileCreateManyInput | Prisma.BuildingFileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BuildingFile createManyAndReturn
 */
export type BuildingFileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildingFile
   */
  select?: Prisma.BuildingFileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BuildingFile
   */
  omit?: Prisma.BuildingFileOmit<ExtArgs> | null
  /**
   * The data used to create many BuildingFiles.
   */
  data: Prisma.BuildingFileCreateManyInput | Prisma.BuildingFileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildingFileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BuildingFile update
 */
export type BuildingFileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildingFile
   */
  select?: Prisma.BuildingFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildingFile
   */
  omit?: Prisma.BuildingFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildingFileInclude<ExtArgs> | null
  /**
   * The data needed to update a BuildingFile.
   */
  data: Prisma.XOR<Prisma.BuildingFileUpdateInput, Prisma.BuildingFileUncheckedUpdateInput>
  /**
   * Choose, which BuildingFile to update.
   */
  where: Prisma.BuildingFileWhereUniqueInput
}

/**
 * BuildingFile updateMany
 */
export type BuildingFileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BuildingFiles.
   */
  data: Prisma.XOR<Prisma.BuildingFileUpdateManyMutationInput, Prisma.BuildingFileUncheckedUpdateManyInput>
  /**
   * Filter which BuildingFiles to update
   */
  where?: Prisma.BuildingFileWhereInput
  /**
   * Limit how many BuildingFiles to update.
   */
  limit?: number
}

/**
 * BuildingFile updateManyAndReturn
 */
export type BuildingFileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildingFile
   */
  select?: Prisma.BuildingFileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BuildingFile
   */
  omit?: Prisma.BuildingFileOmit<ExtArgs> | null
  /**
   * The data used to update BuildingFiles.
   */
  data: Prisma.XOR<Prisma.BuildingFileUpdateManyMutationInput, Prisma.BuildingFileUncheckedUpdateManyInput>
  /**
   * Filter which BuildingFiles to update
   */
  where?: Prisma.BuildingFileWhereInput
  /**
   * Limit how many BuildingFiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildingFileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BuildingFile upsert
 */
export type BuildingFileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildingFile
   */
  select?: Prisma.BuildingFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildingFile
   */
  omit?: Prisma.BuildingFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildingFileInclude<ExtArgs> | null
  /**
   * The filter to search for the BuildingFile to update in case it exists.
   */
  where: Prisma.BuildingFileWhereUniqueInput
  /**
   * In case the BuildingFile found by the `where` argument doesn't exist, create a new BuildingFile with this data.
   */
  create: Prisma.XOR<Prisma.BuildingFileCreateInput, Prisma.BuildingFileUncheckedCreateInput>
  /**
   * In case the BuildingFile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BuildingFileUpdateInput, Prisma.BuildingFileUncheckedUpdateInput>
}

/**
 * BuildingFile delete
 */
export type BuildingFileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildingFile
   */
  select?: Prisma.BuildingFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildingFile
   */
  omit?: Prisma.BuildingFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildingFileInclude<ExtArgs> | null
  /**
   * Filter which BuildingFile to delete.
   */
  where: Prisma.BuildingFileWhereUniqueInput
}

/**
 * BuildingFile deleteMany
 */
export type BuildingFileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BuildingFiles to delete
   */
  where?: Prisma.BuildingFileWhereInput
  /**
   * Limit how many BuildingFiles to delete.
   */
  limit?: number
}

/**
 * BuildingFile.expenseLinks
 */
export type BuildingFile$expenseLinksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildingExpense
   */
  select?: Prisma.BuildingExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildingExpense
   */
  omit?: Prisma.BuildingExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildingExpenseInclude<ExtArgs> | null
  where?: Prisma.BuildingExpenseWhereInput
  orderBy?: Prisma.BuildingExpenseOrderByWithRelationInput | Prisma.BuildingExpenseOrderByWithRelationInput[]
  cursor?: Prisma.BuildingExpenseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BuildingExpenseScalarFieldEnum | Prisma.BuildingExpenseScalarFieldEnum[]
}

/**
 * BuildingFile without action
 */
export type BuildingFileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildingFile
   */
  select?: Prisma.BuildingFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildingFile
   */
  omit?: Prisma.BuildingFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildingFileInclude<ExtArgs> | null
}
