
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CommonArea` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CommonArea
 * 
 */
export type CommonAreaModel = runtime.Types.Result.DefaultSelection<Prisma.$CommonAreaPayload>

export type AggregateCommonArea = {
  _count: CommonAreaCountAggregateOutputType | null
  _avg: CommonAreaAvgAggregateOutputType | null
  _sum: CommonAreaSumAggregateOutputType | null
  _min: CommonAreaMinAggregateOutputType | null
  _max: CommonAreaMaxAggregateOutputType | null
}

export type CommonAreaAvgAggregateOutputType = {
  floor: number | null
}

export type CommonAreaSumAggregateOutputType = {
  floor: number | null
}

export type CommonAreaMinAggregateOutputType = {
  id: string | null
  buildingId: string | null
  name: string | null
  type: string | null
  floor: number | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CommonAreaMaxAggregateOutputType = {
  id: string | null
  buildingId: string | null
  name: string | null
  type: string | null
  floor: number | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CommonAreaCountAggregateOutputType = {
  id: number
  buildingId: number
  name: number
  type: number
  floor: number
  notes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CommonAreaAvgAggregateInputType = {
  floor?: true
}

export type CommonAreaSumAggregateInputType = {
  floor?: true
}

export type CommonAreaMinAggregateInputType = {
  id?: true
  buildingId?: true
  name?: true
  type?: true
  floor?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type CommonAreaMaxAggregateInputType = {
  id?: true
  buildingId?: true
  name?: true
  type?: true
  floor?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type CommonAreaCountAggregateInputType = {
  id?: true
  buildingId?: true
  name?: true
  type?: true
  floor?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CommonAreaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CommonArea to aggregate.
   */
  where?: Prisma.CommonAreaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommonAreas to fetch.
   */
  orderBy?: Prisma.CommonAreaOrderByWithRelationInput | Prisma.CommonAreaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CommonAreaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommonAreas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommonAreas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CommonAreas
  **/
  _count?: true | CommonAreaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CommonAreaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CommonAreaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CommonAreaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CommonAreaMaxAggregateInputType
}

export type GetCommonAreaAggregateType<T extends CommonAreaAggregateArgs> = {
      [P in keyof T & keyof AggregateCommonArea]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCommonArea[P]>
    : Prisma.GetScalarType<T[P], AggregateCommonArea[P]>
}




export type CommonAreaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CommonAreaWhereInput
  orderBy?: Prisma.CommonAreaOrderByWithAggregationInput | Prisma.CommonAreaOrderByWithAggregationInput[]
  by: Prisma.CommonAreaScalarFieldEnum[] | Prisma.CommonAreaScalarFieldEnum
  having?: Prisma.CommonAreaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CommonAreaCountAggregateInputType | true
  _avg?: CommonAreaAvgAggregateInputType
  _sum?: CommonAreaSumAggregateInputType
  _min?: CommonAreaMinAggregateInputType
  _max?: CommonAreaMaxAggregateInputType
}

export type CommonAreaGroupByOutputType = {
  id: string
  buildingId: string
  name: string
  type: string | null
  floor: number | null
  notes: string | null
  createdAt: Date
  updatedAt: Date
  _count: CommonAreaCountAggregateOutputType | null
  _avg: CommonAreaAvgAggregateOutputType | null
  _sum: CommonAreaSumAggregateOutputType | null
  _min: CommonAreaMinAggregateOutputType | null
  _max: CommonAreaMaxAggregateOutputType | null
}

export type GetCommonAreaGroupByPayload<T extends CommonAreaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CommonAreaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CommonAreaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CommonAreaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CommonAreaGroupByOutputType[P]>
      }
    >
  >



export type CommonAreaWhereInput = {
  AND?: Prisma.CommonAreaWhereInput | Prisma.CommonAreaWhereInput[]
  OR?: Prisma.CommonAreaWhereInput[]
  NOT?: Prisma.CommonAreaWhereInput | Prisma.CommonAreaWhereInput[]
  id?: Prisma.StringFilter<"CommonArea"> | string
  buildingId?: Prisma.StringFilter<"CommonArea"> | string
  name?: Prisma.StringFilter<"CommonArea"> | string
  type?: Prisma.StringNullableFilter<"CommonArea"> | string | null
  floor?: Prisma.IntNullableFilter<"CommonArea"> | number | null
  notes?: Prisma.StringNullableFilter<"CommonArea"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CommonArea"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CommonArea"> | Date | string
  building?: Prisma.XOR<Prisma.BuildingScalarRelationFilter, Prisma.BuildingWhereInput>
}

export type CommonAreaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  floor?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  building?: Prisma.BuildingOrderByWithRelationInput
}

export type CommonAreaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CommonAreaWhereInput | Prisma.CommonAreaWhereInput[]
  OR?: Prisma.CommonAreaWhereInput[]
  NOT?: Prisma.CommonAreaWhereInput | Prisma.CommonAreaWhereInput[]
  buildingId?: Prisma.StringFilter<"CommonArea"> | string
  name?: Prisma.StringFilter<"CommonArea"> | string
  type?: Prisma.StringNullableFilter<"CommonArea"> | string | null
  floor?: Prisma.IntNullableFilter<"CommonArea"> | number | null
  notes?: Prisma.StringNullableFilter<"CommonArea"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CommonArea"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CommonArea"> | Date | string
  building?: Prisma.XOR<Prisma.BuildingScalarRelationFilter, Prisma.BuildingWhereInput>
}, "id">

export type CommonAreaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  floor?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CommonAreaCountOrderByAggregateInput
  _avg?: Prisma.CommonAreaAvgOrderByAggregateInput
  _max?: Prisma.CommonAreaMaxOrderByAggregateInput
  _min?: Prisma.CommonAreaMinOrderByAggregateInput
  _sum?: Prisma.CommonAreaSumOrderByAggregateInput
}

export type CommonAreaScalarWhereWithAggregatesInput = {
  AND?: Prisma.CommonAreaScalarWhereWithAggregatesInput | Prisma.CommonAreaScalarWhereWithAggregatesInput[]
  OR?: Prisma.CommonAreaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CommonAreaScalarWhereWithAggregatesInput | Prisma.CommonAreaScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CommonArea"> | string
  buildingId?: Prisma.StringWithAggregatesFilter<"CommonArea"> | string
  name?: Prisma.StringWithAggregatesFilter<"CommonArea"> | string
  type?: Prisma.StringNullableWithAggregatesFilter<"CommonArea"> | string | null
  floor?: Prisma.IntNullableWithAggregatesFilter<"CommonArea"> | number | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"CommonArea"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CommonArea"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CommonArea"> | Date | string
}

export type CommonAreaCreateInput = {
  id?: string
  name: string
  type?: string | null
  floor?: number | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  building: Prisma.BuildingCreateNestedOneWithoutCommonAreasInput
}

export type CommonAreaUncheckedCreateInput = {
  id?: string
  buildingId: string
  name: string
  type?: string | null
  floor?: number | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommonAreaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  building?: Prisma.BuildingUpdateOneRequiredWithoutCommonAreasNestedInput
}

export type CommonAreaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommonAreaCreateManyInput = {
  id?: string
  buildingId: string
  name: string
  type?: string | null
  floor?: number | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommonAreaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommonAreaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommonAreaListRelationFilter = {
  every?: Prisma.CommonAreaWhereInput
  some?: Prisma.CommonAreaWhereInput
  none?: Prisma.CommonAreaWhereInput
}

export type CommonAreaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CommonAreaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  floor?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CommonAreaAvgOrderByAggregateInput = {
  floor?: Prisma.SortOrder
}

export type CommonAreaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  floor?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CommonAreaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  floor?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CommonAreaSumOrderByAggregateInput = {
  floor?: Prisma.SortOrder
}

export type CommonAreaCreateNestedManyWithoutBuildingInput = {
  create?: Prisma.XOR<Prisma.CommonAreaCreateWithoutBuildingInput, Prisma.CommonAreaUncheckedCreateWithoutBuildingInput> | Prisma.CommonAreaCreateWithoutBuildingInput[] | Prisma.CommonAreaUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.CommonAreaCreateOrConnectWithoutBuildingInput | Prisma.CommonAreaCreateOrConnectWithoutBuildingInput[]
  createMany?: Prisma.CommonAreaCreateManyBuildingInputEnvelope
  connect?: Prisma.CommonAreaWhereUniqueInput | Prisma.CommonAreaWhereUniqueInput[]
}

export type CommonAreaUncheckedCreateNestedManyWithoutBuildingInput = {
  create?: Prisma.XOR<Prisma.CommonAreaCreateWithoutBuildingInput, Prisma.CommonAreaUncheckedCreateWithoutBuildingInput> | Prisma.CommonAreaCreateWithoutBuildingInput[] | Prisma.CommonAreaUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.CommonAreaCreateOrConnectWithoutBuildingInput | Prisma.CommonAreaCreateOrConnectWithoutBuildingInput[]
  createMany?: Prisma.CommonAreaCreateManyBuildingInputEnvelope
  connect?: Prisma.CommonAreaWhereUniqueInput | Prisma.CommonAreaWhereUniqueInput[]
}

export type CommonAreaUpdateManyWithoutBuildingNestedInput = {
  create?: Prisma.XOR<Prisma.CommonAreaCreateWithoutBuildingInput, Prisma.CommonAreaUncheckedCreateWithoutBuildingInput> | Prisma.CommonAreaCreateWithoutBuildingInput[] | Prisma.CommonAreaUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.CommonAreaCreateOrConnectWithoutBuildingInput | Prisma.CommonAreaCreateOrConnectWithoutBuildingInput[]
  upsert?: Prisma.CommonAreaUpsertWithWhereUniqueWithoutBuildingInput | Prisma.CommonAreaUpsertWithWhereUniqueWithoutBuildingInput[]
  createMany?: Prisma.CommonAreaCreateManyBuildingInputEnvelope
  set?: Prisma.CommonAreaWhereUniqueInput | Prisma.CommonAreaWhereUniqueInput[]
  disconnect?: Prisma.CommonAreaWhereUniqueInput | Prisma.CommonAreaWhereUniqueInput[]
  delete?: Prisma.CommonAreaWhereUniqueInput | Prisma.CommonAreaWhereUniqueInput[]
  connect?: Prisma.CommonAreaWhereUniqueInput | Prisma.CommonAreaWhereUniqueInput[]
  update?: Prisma.CommonAreaUpdateWithWhereUniqueWithoutBuildingInput | Prisma.CommonAreaUpdateWithWhereUniqueWithoutBuildingInput[]
  updateMany?: Prisma.CommonAreaUpdateManyWithWhereWithoutBuildingInput | Prisma.CommonAreaUpdateManyWithWhereWithoutBuildingInput[]
  deleteMany?: Prisma.CommonAreaScalarWhereInput | Prisma.CommonAreaScalarWhereInput[]
}

export type CommonAreaUncheckedUpdateManyWithoutBuildingNestedInput = {
  create?: Prisma.XOR<Prisma.CommonAreaCreateWithoutBuildingInput, Prisma.CommonAreaUncheckedCreateWithoutBuildingInput> | Prisma.CommonAreaCreateWithoutBuildingInput[] | Prisma.CommonAreaUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.CommonAreaCreateOrConnectWithoutBuildingInput | Prisma.CommonAreaCreateOrConnectWithoutBuildingInput[]
  upsert?: Prisma.CommonAreaUpsertWithWhereUniqueWithoutBuildingInput | Prisma.CommonAreaUpsertWithWhereUniqueWithoutBuildingInput[]
  createMany?: Prisma.CommonAreaCreateManyBuildingInputEnvelope
  set?: Prisma.CommonAreaWhereUniqueInput | Prisma.CommonAreaWhereUniqueInput[]
  disconnect?: Prisma.CommonAreaWhereUniqueInput | Prisma.CommonAreaWhereUniqueInput[]
  delete?: Prisma.CommonAreaWhereUniqueInput | Prisma.CommonAreaWhereUniqueInput[]
  connect?: Prisma.CommonAreaWhereUniqueInput | Prisma.CommonAreaWhereUniqueInput[]
  update?: Prisma.CommonAreaUpdateWithWhereUniqueWithoutBuildingInput | Prisma.CommonAreaUpdateWithWhereUniqueWithoutBuildingInput[]
  updateMany?: Prisma.CommonAreaUpdateManyWithWhereWithoutBuildingInput | Prisma.CommonAreaUpdateManyWithWhereWithoutBuildingInput[]
  deleteMany?: Prisma.CommonAreaScalarWhereInput | Prisma.CommonAreaScalarWhereInput[]
}

export type CommonAreaCreateWithoutBuildingInput = {
  id?: string
  name: string
  type?: string | null
  floor?: number | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommonAreaUncheckedCreateWithoutBuildingInput = {
  id?: string
  name: string
  type?: string | null
  floor?: number | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommonAreaCreateOrConnectWithoutBuildingInput = {
  where: Prisma.CommonAreaWhereUniqueInput
  create: Prisma.XOR<Prisma.CommonAreaCreateWithoutBuildingInput, Prisma.CommonAreaUncheckedCreateWithoutBuildingInput>
}

export type CommonAreaCreateManyBuildingInputEnvelope = {
  data: Prisma.CommonAreaCreateManyBuildingInput | Prisma.CommonAreaCreateManyBuildingInput[]
  skipDuplicates?: boolean
}

export type CommonAreaUpsertWithWhereUniqueWithoutBuildingInput = {
  where: Prisma.CommonAreaWhereUniqueInput
  update: Prisma.XOR<Prisma.CommonAreaUpdateWithoutBuildingInput, Prisma.CommonAreaUncheckedUpdateWithoutBuildingInput>
  create: Prisma.XOR<Prisma.CommonAreaCreateWithoutBuildingInput, Prisma.CommonAreaUncheckedCreateWithoutBuildingInput>
}

export type CommonAreaUpdateWithWhereUniqueWithoutBuildingInput = {
  where: Prisma.CommonAreaWhereUniqueInput
  data: Prisma.XOR<Prisma.CommonAreaUpdateWithoutBuildingInput, Prisma.CommonAreaUncheckedUpdateWithoutBuildingInput>
}

export type CommonAreaUpdateManyWithWhereWithoutBuildingInput = {
  where: Prisma.CommonAreaScalarWhereInput
  data: Prisma.XOR<Prisma.CommonAreaUpdateManyMutationInput, Prisma.CommonAreaUncheckedUpdateManyWithoutBuildingInput>
}

export type CommonAreaScalarWhereInput = {
  AND?: Prisma.CommonAreaScalarWhereInput | Prisma.CommonAreaScalarWhereInput[]
  OR?: Prisma.CommonAreaScalarWhereInput[]
  NOT?: Prisma.CommonAreaScalarWhereInput | Prisma.CommonAreaScalarWhereInput[]
  id?: Prisma.StringFilter<"CommonArea"> | string
  buildingId?: Prisma.StringFilter<"CommonArea"> | string
  name?: Prisma.StringFilter<"CommonArea"> | string
  type?: Prisma.StringNullableFilter<"CommonArea"> | string | null
  floor?: Prisma.IntNullableFilter<"CommonArea"> | number | null
  notes?: Prisma.StringNullableFilter<"CommonArea"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CommonArea"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CommonArea"> | Date | string
}

export type CommonAreaCreateManyBuildingInput = {
  id?: string
  name: string
  type?: string | null
  floor?: number | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommonAreaUpdateWithoutBuildingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommonAreaUncheckedUpdateWithoutBuildingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommonAreaUncheckedUpdateManyWithoutBuildingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CommonAreaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buildingId?: boolean
  name?: boolean
  type?: boolean
  floor?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["commonArea"]>

export type CommonAreaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buildingId?: boolean
  name?: boolean
  type?: boolean
  floor?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["commonArea"]>

export type CommonAreaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buildingId?: boolean
  name?: boolean
  type?: boolean
  floor?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["commonArea"]>

export type CommonAreaSelectScalar = {
  id?: boolean
  buildingId?: boolean
  name?: boolean
  type?: boolean
  floor?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CommonAreaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "buildingId" | "name" | "type" | "floor" | "notes" | "createdAt" | "updatedAt", ExtArgs["result"]["commonArea"]>
export type CommonAreaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
}
export type CommonAreaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
}
export type CommonAreaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
}

export type $CommonAreaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CommonArea"
  objects: {
    building: Prisma.$BuildingPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    buildingId: string
    name: string
    type: string | null
    floor: number | null
    notes: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["commonArea"]>
  composites: {}
}

export type CommonAreaGetPayload<S extends boolean | null | undefined | CommonAreaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CommonAreaPayload, S>

export type CommonAreaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CommonAreaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CommonAreaCountAggregateInputType | true
  }

export interface CommonAreaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CommonArea'], meta: { name: 'CommonArea' } }
  /**
   * Find zero or one CommonArea that matches the filter.
   * @param {CommonAreaFindUniqueArgs} args - Arguments to find a CommonArea
   * @example
   * // Get one CommonArea
   * const commonArea = await prisma.commonArea.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CommonAreaFindUniqueArgs>(args: Prisma.SelectSubset<T, CommonAreaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CommonAreaClient<runtime.Types.Result.GetResult<Prisma.$CommonAreaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CommonArea that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CommonAreaFindUniqueOrThrowArgs} args - Arguments to find a CommonArea
   * @example
   * // Get one CommonArea
   * const commonArea = await prisma.commonArea.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CommonAreaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CommonAreaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CommonAreaClient<runtime.Types.Result.GetResult<Prisma.$CommonAreaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CommonArea that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommonAreaFindFirstArgs} args - Arguments to find a CommonArea
   * @example
   * // Get one CommonArea
   * const commonArea = await prisma.commonArea.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CommonAreaFindFirstArgs>(args?: Prisma.SelectSubset<T, CommonAreaFindFirstArgs<ExtArgs>>): Prisma.Prisma__CommonAreaClient<runtime.Types.Result.GetResult<Prisma.$CommonAreaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CommonArea that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommonAreaFindFirstOrThrowArgs} args - Arguments to find a CommonArea
   * @example
   * // Get one CommonArea
   * const commonArea = await prisma.commonArea.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CommonAreaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CommonAreaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CommonAreaClient<runtime.Types.Result.GetResult<Prisma.$CommonAreaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CommonAreas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommonAreaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CommonAreas
   * const commonAreas = await prisma.commonArea.findMany()
   * 
   * // Get first 10 CommonAreas
   * const commonAreas = await prisma.commonArea.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const commonAreaWithIdOnly = await prisma.commonArea.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CommonAreaFindManyArgs>(args?: Prisma.SelectSubset<T, CommonAreaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommonAreaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CommonArea.
   * @param {CommonAreaCreateArgs} args - Arguments to create a CommonArea.
   * @example
   * // Create one CommonArea
   * const CommonArea = await prisma.commonArea.create({
   *   data: {
   *     // ... data to create a CommonArea
   *   }
   * })
   * 
   */
  create<T extends CommonAreaCreateArgs>(args: Prisma.SelectSubset<T, CommonAreaCreateArgs<ExtArgs>>): Prisma.Prisma__CommonAreaClient<runtime.Types.Result.GetResult<Prisma.$CommonAreaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CommonAreas.
   * @param {CommonAreaCreateManyArgs} args - Arguments to create many CommonAreas.
   * @example
   * // Create many CommonAreas
   * const commonArea = await prisma.commonArea.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CommonAreaCreateManyArgs>(args?: Prisma.SelectSubset<T, CommonAreaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CommonAreas and returns the data saved in the database.
   * @param {CommonAreaCreateManyAndReturnArgs} args - Arguments to create many CommonAreas.
   * @example
   * // Create many CommonAreas
   * const commonArea = await prisma.commonArea.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CommonAreas and only return the `id`
   * const commonAreaWithIdOnly = await prisma.commonArea.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CommonAreaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CommonAreaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommonAreaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CommonArea.
   * @param {CommonAreaDeleteArgs} args - Arguments to delete one CommonArea.
   * @example
   * // Delete one CommonArea
   * const CommonArea = await prisma.commonArea.delete({
   *   where: {
   *     // ... filter to delete one CommonArea
   *   }
   * })
   * 
   */
  delete<T extends CommonAreaDeleteArgs>(args: Prisma.SelectSubset<T, CommonAreaDeleteArgs<ExtArgs>>): Prisma.Prisma__CommonAreaClient<runtime.Types.Result.GetResult<Prisma.$CommonAreaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CommonArea.
   * @param {CommonAreaUpdateArgs} args - Arguments to update one CommonArea.
   * @example
   * // Update one CommonArea
   * const commonArea = await prisma.commonArea.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CommonAreaUpdateArgs>(args: Prisma.SelectSubset<T, CommonAreaUpdateArgs<ExtArgs>>): Prisma.Prisma__CommonAreaClient<runtime.Types.Result.GetResult<Prisma.$CommonAreaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CommonAreas.
   * @param {CommonAreaDeleteManyArgs} args - Arguments to filter CommonAreas to delete.
   * @example
   * // Delete a few CommonAreas
   * const { count } = await prisma.commonArea.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CommonAreaDeleteManyArgs>(args?: Prisma.SelectSubset<T, CommonAreaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CommonAreas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommonAreaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CommonAreas
   * const commonArea = await prisma.commonArea.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CommonAreaUpdateManyArgs>(args: Prisma.SelectSubset<T, CommonAreaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CommonAreas and returns the data updated in the database.
   * @param {CommonAreaUpdateManyAndReturnArgs} args - Arguments to update many CommonAreas.
   * @example
   * // Update many CommonAreas
   * const commonArea = await prisma.commonArea.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CommonAreas and only return the `id`
   * const commonAreaWithIdOnly = await prisma.commonArea.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CommonAreaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CommonAreaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommonAreaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CommonArea.
   * @param {CommonAreaUpsertArgs} args - Arguments to update or create a CommonArea.
   * @example
   * // Update or create a CommonArea
   * const commonArea = await prisma.commonArea.upsert({
   *   create: {
   *     // ... data to create a CommonArea
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CommonArea we want to update
   *   }
   * })
   */
  upsert<T extends CommonAreaUpsertArgs>(args: Prisma.SelectSubset<T, CommonAreaUpsertArgs<ExtArgs>>): Prisma.Prisma__CommonAreaClient<runtime.Types.Result.GetResult<Prisma.$CommonAreaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CommonAreas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommonAreaCountArgs} args - Arguments to filter CommonAreas to count.
   * @example
   * // Count the number of CommonAreas
   * const count = await prisma.commonArea.count({
   *   where: {
   *     // ... the filter for the CommonAreas we want to count
   *   }
   * })
  **/
  count<T extends CommonAreaCountArgs>(
    args?: Prisma.Subset<T, CommonAreaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CommonAreaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CommonArea.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommonAreaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CommonAreaAggregateArgs>(args: Prisma.Subset<T, CommonAreaAggregateArgs>): Prisma.PrismaPromise<GetCommonAreaAggregateType<T>>

  /**
   * Group by CommonArea.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommonAreaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CommonAreaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CommonAreaGroupByArgs['orderBy'] }
      : { orderBy?: CommonAreaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CommonAreaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCommonAreaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CommonArea model
 */
readonly fields: CommonAreaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CommonArea.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CommonAreaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  building<T extends Prisma.BuildingDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BuildingDefaultArgs<ExtArgs>>): Prisma.Prisma__BuildingClient<runtime.Types.Result.GetResult<Prisma.$BuildingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CommonArea model
 */
export interface CommonAreaFieldRefs {
  readonly id: Prisma.FieldRef<"CommonArea", 'String'>
  readonly buildingId: Prisma.FieldRef<"CommonArea", 'String'>
  readonly name: Prisma.FieldRef<"CommonArea", 'String'>
  readonly type: Prisma.FieldRef<"CommonArea", 'String'>
  readonly floor: Prisma.FieldRef<"CommonArea", 'Int'>
  readonly notes: Prisma.FieldRef<"CommonArea", 'String'>
  readonly createdAt: Prisma.FieldRef<"CommonArea", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CommonArea", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CommonArea findUnique
 */
export type CommonAreaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonArea
   */
  select?: Prisma.CommonAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonArea
   */
  omit?: Prisma.CommonAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAreaInclude<ExtArgs> | null
  /**
   * Filter, which CommonArea to fetch.
   */
  where: Prisma.CommonAreaWhereUniqueInput
}

/**
 * CommonArea findUniqueOrThrow
 */
export type CommonAreaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonArea
   */
  select?: Prisma.CommonAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonArea
   */
  omit?: Prisma.CommonAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAreaInclude<ExtArgs> | null
  /**
   * Filter, which CommonArea to fetch.
   */
  where: Prisma.CommonAreaWhereUniqueInput
}

/**
 * CommonArea findFirst
 */
export type CommonAreaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonArea
   */
  select?: Prisma.CommonAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonArea
   */
  omit?: Prisma.CommonAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAreaInclude<ExtArgs> | null
  /**
   * Filter, which CommonArea to fetch.
   */
  where?: Prisma.CommonAreaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommonAreas to fetch.
   */
  orderBy?: Prisma.CommonAreaOrderByWithRelationInput | Prisma.CommonAreaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CommonAreas.
   */
  cursor?: Prisma.CommonAreaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommonAreas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommonAreas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CommonAreas.
   */
  distinct?: Prisma.CommonAreaScalarFieldEnum | Prisma.CommonAreaScalarFieldEnum[]
}

/**
 * CommonArea findFirstOrThrow
 */
export type CommonAreaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonArea
   */
  select?: Prisma.CommonAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonArea
   */
  omit?: Prisma.CommonAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAreaInclude<ExtArgs> | null
  /**
   * Filter, which CommonArea to fetch.
   */
  where?: Prisma.CommonAreaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommonAreas to fetch.
   */
  orderBy?: Prisma.CommonAreaOrderByWithRelationInput | Prisma.CommonAreaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CommonAreas.
   */
  cursor?: Prisma.CommonAreaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommonAreas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommonAreas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CommonAreas.
   */
  distinct?: Prisma.CommonAreaScalarFieldEnum | Prisma.CommonAreaScalarFieldEnum[]
}

/**
 * CommonArea findMany
 */
export type CommonAreaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonArea
   */
  select?: Prisma.CommonAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonArea
   */
  omit?: Prisma.CommonAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAreaInclude<ExtArgs> | null
  /**
   * Filter, which CommonAreas to fetch.
   */
  where?: Prisma.CommonAreaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommonAreas to fetch.
   */
  orderBy?: Prisma.CommonAreaOrderByWithRelationInput | Prisma.CommonAreaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CommonAreas.
   */
  cursor?: Prisma.CommonAreaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommonAreas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommonAreas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CommonAreas.
   */
  distinct?: Prisma.CommonAreaScalarFieldEnum | Prisma.CommonAreaScalarFieldEnum[]
}

/**
 * CommonArea create
 */
export type CommonAreaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonArea
   */
  select?: Prisma.CommonAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonArea
   */
  omit?: Prisma.CommonAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAreaInclude<ExtArgs> | null
  /**
   * The data needed to create a CommonArea.
   */
  data: Prisma.XOR<Prisma.CommonAreaCreateInput, Prisma.CommonAreaUncheckedCreateInput>
}

/**
 * CommonArea createMany
 */
export type CommonAreaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CommonAreas.
   */
  data: Prisma.CommonAreaCreateManyInput | Prisma.CommonAreaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CommonArea createManyAndReturn
 */
export type CommonAreaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonArea
   */
  select?: Prisma.CommonAreaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CommonArea
   */
  omit?: Prisma.CommonAreaOmit<ExtArgs> | null
  /**
   * The data used to create many CommonAreas.
   */
  data: Prisma.CommonAreaCreateManyInput | Prisma.CommonAreaCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAreaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CommonArea update
 */
export type CommonAreaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonArea
   */
  select?: Prisma.CommonAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonArea
   */
  omit?: Prisma.CommonAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAreaInclude<ExtArgs> | null
  /**
   * The data needed to update a CommonArea.
   */
  data: Prisma.XOR<Prisma.CommonAreaUpdateInput, Prisma.CommonAreaUncheckedUpdateInput>
  /**
   * Choose, which CommonArea to update.
   */
  where: Prisma.CommonAreaWhereUniqueInput
}

/**
 * CommonArea updateMany
 */
export type CommonAreaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CommonAreas.
   */
  data: Prisma.XOR<Prisma.CommonAreaUpdateManyMutationInput, Prisma.CommonAreaUncheckedUpdateManyInput>
  /**
   * Filter which CommonAreas to update
   */
  where?: Prisma.CommonAreaWhereInput
  /**
   * Limit how many CommonAreas to update.
   */
  limit?: number
}

/**
 * CommonArea updateManyAndReturn
 */
export type CommonAreaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonArea
   */
  select?: Prisma.CommonAreaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CommonArea
   */
  omit?: Prisma.CommonAreaOmit<ExtArgs> | null
  /**
   * The data used to update CommonAreas.
   */
  data: Prisma.XOR<Prisma.CommonAreaUpdateManyMutationInput, Prisma.CommonAreaUncheckedUpdateManyInput>
  /**
   * Filter which CommonAreas to update
   */
  where?: Prisma.CommonAreaWhereInput
  /**
   * Limit how many CommonAreas to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAreaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CommonArea upsert
 */
export type CommonAreaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonArea
   */
  select?: Prisma.CommonAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonArea
   */
  omit?: Prisma.CommonAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAreaInclude<ExtArgs> | null
  /**
   * The filter to search for the CommonArea to update in case it exists.
   */
  where: Prisma.CommonAreaWhereUniqueInput
  /**
   * In case the CommonArea found by the `where` argument doesn't exist, create a new CommonArea with this data.
   */
  create: Prisma.XOR<Prisma.CommonAreaCreateInput, Prisma.CommonAreaUncheckedCreateInput>
  /**
   * In case the CommonArea was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CommonAreaUpdateInput, Prisma.CommonAreaUncheckedUpdateInput>
}

/**
 * CommonArea delete
 */
export type CommonAreaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonArea
   */
  select?: Prisma.CommonAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonArea
   */
  omit?: Prisma.CommonAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAreaInclude<ExtArgs> | null
  /**
   * Filter which CommonArea to delete.
   */
  where: Prisma.CommonAreaWhereUniqueInput
}

/**
 * CommonArea deleteMany
 */
export type CommonAreaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CommonAreas to delete
   */
  where?: Prisma.CommonAreaWhereInput
  /**
   * Limit how many CommonAreas to delete.
   */
  limit?: number
}

/**
 * CommonArea without action
 */
export type CommonAreaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonArea
   */
  select?: Prisma.CommonAreaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonArea
   */
  omit?: Prisma.CommonAreaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAreaInclude<ExtArgs> | null
}
