
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MaintenanceAttachment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MaintenanceAttachment
 * 
 */
export type MaintenanceAttachmentModel = runtime.Types.Result.DefaultSelection<Prisma.$MaintenanceAttachmentPayload>

export type AggregateMaintenanceAttachment = {
  _count: MaintenanceAttachmentCountAggregateOutputType | null
  _avg: MaintenanceAttachmentAvgAggregateOutputType | null
  _sum: MaintenanceAttachmentSumAggregateOutputType | null
  _min: MaintenanceAttachmentMinAggregateOutputType | null
  _max: MaintenanceAttachmentMaxAggregateOutputType | null
}

export type MaintenanceAttachmentAvgAggregateOutputType = {
  sizeBytes: number | null
}

export type MaintenanceAttachmentSumAggregateOutputType = {
  sizeBytes: number | null
}

export type MaintenanceAttachmentMinAggregateOutputType = {
  id: string | null
  requestId: string | null
  url: string | null
  cdnPath: string | null
  kind: string | null
  contentType: string | null
  sizeBytes: number | null
  createdAt: Date | null
}

export type MaintenanceAttachmentMaxAggregateOutputType = {
  id: string | null
  requestId: string | null
  url: string | null
  cdnPath: string | null
  kind: string | null
  contentType: string | null
  sizeBytes: number | null
  createdAt: Date | null
}

export type MaintenanceAttachmentCountAggregateOutputType = {
  id: number
  requestId: number
  url: number
  cdnPath: number
  kind: number
  contentType: number
  sizeBytes: number
  createdAt: number
  _all: number
}


export type MaintenanceAttachmentAvgAggregateInputType = {
  sizeBytes?: true
}

export type MaintenanceAttachmentSumAggregateInputType = {
  sizeBytes?: true
}

export type MaintenanceAttachmentMinAggregateInputType = {
  id?: true
  requestId?: true
  url?: true
  cdnPath?: true
  kind?: true
  contentType?: true
  sizeBytes?: true
  createdAt?: true
}

export type MaintenanceAttachmentMaxAggregateInputType = {
  id?: true
  requestId?: true
  url?: true
  cdnPath?: true
  kind?: true
  contentType?: true
  sizeBytes?: true
  createdAt?: true
}

export type MaintenanceAttachmentCountAggregateInputType = {
  id?: true
  requestId?: true
  url?: true
  cdnPath?: true
  kind?: true
  contentType?: true
  sizeBytes?: true
  createdAt?: true
  _all?: true
}

export type MaintenanceAttachmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MaintenanceAttachment to aggregate.
   */
  where?: Prisma.MaintenanceAttachmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaintenanceAttachments to fetch.
   */
  orderBy?: Prisma.MaintenanceAttachmentOrderByWithRelationInput | Prisma.MaintenanceAttachmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MaintenanceAttachmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaintenanceAttachments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaintenanceAttachments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MaintenanceAttachments
  **/
  _count?: true | MaintenanceAttachmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MaintenanceAttachmentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MaintenanceAttachmentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MaintenanceAttachmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MaintenanceAttachmentMaxAggregateInputType
}

export type GetMaintenanceAttachmentAggregateType<T extends MaintenanceAttachmentAggregateArgs> = {
      [P in keyof T & keyof AggregateMaintenanceAttachment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMaintenanceAttachment[P]>
    : Prisma.GetScalarType<T[P], AggregateMaintenanceAttachment[P]>
}




export type MaintenanceAttachmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MaintenanceAttachmentWhereInput
  orderBy?: Prisma.MaintenanceAttachmentOrderByWithAggregationInput | Prisma.MaintenanceAttachmentOrderByWithAggregationInput[]
  by: Prisma.MaintenanceAttachmentScalarFieldEnum[] | Prisma.MaintenanceAttachmentScalarFieldEnum
  having?: Prisma.MaintenanceAttachmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MaintenanceAttachmentCountAggregateInputType | true
  _avg?: MaintenanceAttachmentAvgAggregateInputType
  _sum?: MaintenanceAttachmentSumAggregateInputType
  _min?: MaintenanceAttachmentMinAggregateInputType
  _max?: MaintenanceAttachmentMaxAggregateInputType
}

export type MaintenanceAttachmentGroupByOutputType = {
  id: string
  requestId: string
  url: string
  cdnPath: string | null
  kind: string
  contentType: string | null
  sizeBytes: number | null
  createdAt: Date
  _count: MaintenanceAttachmentCountAggregateOutputType | null
  _avg: MaintenanceAttachmentAvgAggregateOutputType | null
  _sum: MaintenanceAttachmentSumAggregateOutputType | null
  _min: MaintenanceAttachmentMinAggregateOutputType | null
  _max: MaintenanceAttachmentMaxAggregateOutputType | null
}

export type GetMaintenanceAttachmentGroupByPayload<T extends MaintenanceAttachmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MaintenanceAttachmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MaintenanceAttachmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MaintenanceAttachmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MaintenanceAttachmentGroupByOutputType[P]>
      }
    >
  >



export type MaintenanceAttachmentWhereInput = {
  AND?: Prisma.MaintenanceAttachmentWhereInput | Prisma.MaintenanceAttachmentWhereInput[]
  OR?: Prisma.MaintenanceAttachmentWhereInput[]
  NOT?: Prisma.MaintenanceAttachmentWhereInput | Prisma.MaintenanceAttachmentWhereInput[]
  id?: Prisma.StringFilter<"MaintenanceAttachment"> | string
  requestId?: Prisma.StringFilter<"MaintenanceAttachment"> | string
  url?: Prisma.StringFilter<"MaintenanceAttachment"> | string
  cdnPath?: Prisma.StringNullableFilter<"MaintenanceAttachment"> | string | null
  kind?: Prisma.StringFilter<"MaintenanceAttachment"> | string
  contentType?: Prisma.StringNullableFilter<"MaintenanceAttachment"> | string | null
  sizeBytes?: Prisma.IntNullableFilter<"MaintenanceAttachment"> | number | null
  createdAt?: Prisma.DateTimeFilter<"MaintenanceAttachment"> | Date | string
  request?: Prisma.XOR<Prisma.MaintenanceRequestScalarRelationFilter, Prisma.MaintenanceRequestWhereInput>
}

export type MaintenanceAttachmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  cdnPath?: Prisma.SortOrderInput | Prisma.SortOrder
  kind?: Prisma.SortOrder
  contentType?: Prisma.SortOrderInput | Prisma.SortOrder
  sizeBytes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  request?: Prisma.MaintenanceRequestOrderByWithRelationInput
}

export type MaintenanceAttachmentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MaintenanceAttachmentWhereInput | Prisma.MaintenanceAttachmentWhereInput[]
  OR?: Prisma.MaintenanceAttachmentWhereInput[]
  NOT?: Prisma.MaintenanceAttachmentWhereInput | Prisma.MaintenanceAttachmentWhereInput[]
  requestId?: Prisma.StringFilter<"MaintenanceAttachment"> | string
  url?: Prisma.StringFilter<"MaintenanceAttachment"> | string
  cdnPath?: Prisma.StringNullableFilter<"MaintenanceAttachment"> | string | null
  kind?: Prisma.StringFilter<"MaintenanceAttachment"> | string
  contentType?: Prisma.StringNullableFilter<"MaintenanceAttachment"> | string | null
  sizeBytes?: Prisma.IntNullableFilter<"MaintenanceAttachment"> | number | null
  createdAt?: Prisma.DateTimeFilter<"MaintenanceAttachment"> | Date | string
  request?: Prisma.XOR<Prisma.MaintenanceRequestScalarRelationFilter, Prisma.MaintenanceRequestWhereInput>
}, "id">

export type MaintenanceAttachmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  cdnPath?: Prisma.SortOrderInput | Prisma.SortOrder
  kind?: Prisma.SortOrder
  contentType?: Prisma.SortOrderInput | Prisma.SortOrder
  sizeBytes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.MaintenanceAttachmentCountOrderByAggregateInput
  _avg?: Prisma.MaintenanceAttachmentAvgOrderByAggregateInput
  _max?: Prisma.MaintenanceAttachmentMaxOrderByAggregateInput
  _min?: Prisma.MaintenanceAttachmentMinOrderByAggregateInput
  _sum?: Prisma.MaintenanceAttachmentSumOrderByAggregateInput
}

export type MaintenanceAttachmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.MaintenanceAttachmentScalarWhereWithAggregatesInput | Prisma.MaintenanceAttachmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.MaintenanceAttachmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MaintenanceAttachmentScalarWhereWithAggregatesInput | Prisma.MaintenanceAttachmentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MaintenanceAttachment"> | string
  requestId?: Prisma.StringWithAggregatesFilter<"MaintenanceAttachment"> | string
  url?: Prisma.StringWithAggregatesFilter<"MaintenanceAttachment"> | string
  cdnPath?: Prisma.StringNullableWithAggregatesFilter<"MaintenanceAttachment"> | string | null
  kind?: Prisma.StringWithAggregatesFilter<"MaintenanceAttachment"> | string
  contentType?: Prisma.StringNullableWithAggregatesFilter<"MaintenanceAttachment"> | string | null
  sizeBytes?: Prisma.IntNullableWithAggregatesFilter<"MaintenanceAttachment"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MaintenanceAttachment"> | Date | string
}

export type MaintenanceAttachmentCreateInput = {
  id?: string
  url: string
  cdnPath?: string | null
  kind?: string
  contentType?: string | null
  sizeBytes?: number | null
  createdAt?: Date | string
  request: Prisma.MaintenanceRequestCreateNestedOneWithoutAttachmentsInput
}

export type MaintenanceAttachmentUncheckedCreateInput = {
  id?: string
  requestId: string
  url: string
  cdnPath?: string | null
  kind?: string
  contentType?: string | null
  sizeBytes?: number | null
  createdAt?: Date | string
}

export type MaintenanceAttachmentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kind?: Prisma.StringFieldUpdateOperationsInput | string
  contentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  request?: Prisma.MaintenanceRequestUpdateOneRequiredWithoutAttachmentsNestedInput
}

export type MaintenanceAttachmentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kind?: Prisma.StringFieldUpdateOperationsInput | string
  contentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceAttachmentCreateManyInput = {
  id?: string
  requestId: string
  url: string
  cdnPath?: string | null
  kind?: string
  contentType?: string | null
  sizeBytes?: number | null
  createdAt?: Date | string
}

export type MaintenanceAttachmentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kind?: Prisma.StringFieldUpdateOperationsInput | string
  contentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceAttachmentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kind?: Prisma.StringFieldUpdateOperationsInput | string
  contentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceAttachmentListRelationFilter = {
  every?: Prisma.MaintenanceAttachmentWhereInput
  some?: Prisma.MaintenanceAttachmentWhereInput
  none?: Prisma.MaintenanceAttachmentWhereInput
}

export type MaintenanceAttachmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MaintenanceAttachmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  cdnPath?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  contentType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MaintenanceAttachmentAvgOrderByAggregateInput = {
  sizeBytes?: Prisma.SortOrder
}

export type MaintenanceAttachmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  cdnPath?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  contentType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MaintenanceAttachmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  cdnPath?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  contentType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MaintenanceAttachmentSumOrderByAggregateInput = {
  sizeBytes?: Prisma.SortOrder
}

export type MaintenanceAttachmentCreateNestedManyWithoutRequestInput = {
  create?: Prisma.XOR<Prisma.MaintenanceAttachmentCreateWithoutRequestInput, Prisma.MaintenanceAttachmentUncheckedCreateWithoutRequestInput> | Prisma.MaintenanceAttachmentCreateWithoutRequestInput[] | Prisma.MaintenanceAttachmentUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.MaintenanceAttachmentCreateOrConnectWithoutRequestInput | Prisma.MaintenanceAttachmentCreateOrConnectWithoutRequestInput[]
  createMany?: Prisma.MaintenanceAttachmentCreateManyRequestInputEnvelope
  connect?: Prisma.MaintenanceAttachmentWhereUniqueInput | Prisma.MaintenanceAttachmentWhereUniqueInput[]
}

export type MaintenanceAttachmentUncheckedCreateNestedManyWithoutRequestInput = {
  create?: Prisma.XOR<Prisma.MaintenanceAttachmentCreateWithoutRequestInput, Prisma.MaintenanceAttachmentUncheckedCreateWithoutRequestInput> | Prisma.MaintenanceAttachmentCreateWithoutRequestInput[] | Prisma.MaintenanceAttachmentUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.MaintenanceAttachmentCreateOrConnectWithoutRequestInput | Prisma.MaintenanceAttachmentCreateOrConnectWithoutRequestInput[]
  createMany?: Prisma.MaintenanceAttachmentCreateManyRequestInputEnvelope
  connect?: Prisma.MaintenanceAttachmentWhereUniqueInput | Prisma.MaintenanceAttachmentWhereUniqueInput[]
}

export type MaintenanceAttachmentUpdateManyWithoutRequestNestedInput = {
  create?: Prisma.XOR<Prisma.MaintenanceAttachmentCreateWithoutRequestInput, Prisma.MaintenanceAttachmentUncheckedCreateWithoutRequestInput> | Prisma.MaintenanceAttachmentCreateWithoutRequestInput[] | Prisma.MaintenanceAttachmentUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.MaintenanceAttachmentCreateOrConnectWithoutRequestInput | Prisma.MaintenanceAttachmentCreateOrConnectWithoutRequestInput[]
  upsert?: Prisma.MaintenanceAttachmentUpsertWithWhereUniqueWithoutRequestInput | Prisma.MaintenanceAttachmentUpsertWithWhereUniqueWithoutRequestInput[]
  createMany?: Prisma.MaintenanceAttachmentCreateManyRequestInputEnvelope
  set?: Prisma.MaintenanceAttachmentWhereUniqueInput | Prisma.MaintenanceAttachmentWhereUniqueInput[]
  disconnect?: Prisma.MaintenanceAttachmentWhereUniqueInput | Prisma.MaintenanceAttachmentWhereUniqueInput[]
  delete?: Prisma.MaintenanceAttachmentWhereUniqueInput | Prisma.MaintenanceAttachmentWhereUniqueInput[]
  connect?: Prisma.MaintenanceAttachmentWhereUniqueInput | Prisma.MaintenanceAttachmentWhereUniqueInput[]
  update?: Prisma.MaintenanceAttachmentUpdateWithWhereUniqueWithoutRequestInput | Prisma.MaintenanceAttachmentUpdateWithWhereUniqueWithoutRequestInput[]
  updateMany?: Prisma.MaintenanceAttachmentUpdateManyWithWhereWithoutRequestInput | Prisma.MaintenanceAttachmentUpdateManyWithWhereWithoutRequestInput[]
  deleteMany?: Prisma.MaintenanceAttachmentScalarWhereInput | Prisma.MaintenanceAttachmentScalarWhereInput[]
}

export type MaintenanceAttachmentUncheckedUpdateManyWithoutRequestNestedInput = {
  create?: Prisma.XOR<Prisma.MaintenanceAttachmentCreateWithoutRequestInput, Prisma.MaintenanceAttachmentUncheckedCreateWithoutRequestInput> | Prisma.MaintenanceAttachmentCreateWithoutRequestInput[] | Prisma.MaintenanceAttachmentUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.MaintenanceAttachmentCreateOrConnectWithoutRequestInput | Prisma.MaintenanceAttachmentCreateOrConnectWithoutRequestInput[]
  upsert?: Prisma.MaintenanceAttachmentUpsertWithWhereUniqueWithoutRequestInput | Prisma.MaintenanceAttachmentUpsertWithWhereUniqueWithoutRequestInput[]
  createMany?: Prisma.MaintenanceAttachmentCreateManyRequestInputEnvelope
  set?: Prisma.MaintenanceAttachmentWhereUniqueInput | Prisma.MaintenanceAttachmentWhereUniqueInput[]
  disconnect?: Prisma.MaintenanceAttachmentWhereUniqueInput | Prisma.MaintenanceAttachmentWhereUniqueInput[]
  delete?: Prisma.MaintenanceAttachmentWhereUniqueInput | Prisma.MaintenanceAttachmentWhereUniqueInput[]
  connect?: Prisma.MaintenanceAttachmentWhereUniqueInput | Prisma.MaintenanceAttachmentWhereUniqueInput[]
  update?: Prisma.MaintenanceAttachmentUpdateWithWhereUniqueWithoutRequestInput | Prisma.MaintenanceAttachmentUpdateWithWhereUniqueWithoutRequestInput[]
  updateMany?: Prisma.MaintenanceAttachmentUpdateManyWithWhereWithoutRequestInput | Prisma.MaintenanceAttachmentUpdateManyWithWhereWithoutRequestInput[]
  deleteMany?: Prisma.MaintenanceAttachmentScalarWhereInput | Prisma.MaintenanceAttachmentScalarWhereInput[]
}

export type MaintenanceAttachmentCreateWithoutRequestInput = {
  id?: string
  url: string
  cdnPath?: string | null
  kind?: string
  contentType?: string | null
  sizeBytes?: number | null
  createdAt?: Date | string
}

export type MaintenanceAttachmentUncheckedCreateWithoutRequestInput = {
  id?: string
  url: string
  cdnPath?: string | null
  kind?: string
  contentType?: string | null
  sizeBytes?: number | null
  createdAt?: Date | string
}

export type MaintenanceAttachmentCreateOrConnectWithoutRequestInput = {
  where: Prisma.MaintenanceAttachmentWhereUniqueInput
  create: Prisma.XOR<Prisma.MaintenanceAttachmentCreateWithoutRequestInput, Prisma.MaintenanceAttachmentUncheckedCreateWithoutRequestInput>
}

export type MaintenanceAttachmentCreateManyRequestInputEnvelope = {
  data: Prisma.MaintenanceAttachmentCreateManyRequestInput | Prisma.MaintenanceAttachmentCreateManyRequestInput[]
  skipDuplicates?: boolean
}

export type MaintenanceAttachmentUpsertWithWhereUniqueWithoutRequestInput = {
  where: Prisma.MaintenanceAttachmentWhereUniqueInput
  update: Prisma.XOR<Prisma.MaintenanceAttachmentUpdateWithoutRequestInput, Prisma.MaintenanceAttachmentUncheckedUpdateWithoutRequestInput>
  create: Prisma.XOR<Prisma.MaintenanceAttachmentCreateWithoutRequestInput, Prisma.MaintenanceAttachmentUncheckedCreateWithoutRequestInput>
}

export type MaintenanceAttachmentUpdateWithWhereUniqueWithoutRequestInput = {
  where: Prisma.MaintenanceAttachmentWhereUniqueInput
  data: Prisma.XOR<Prisma.MaintenanceAttachmentUpdateWithoutRequestInput, Prisma.MaintenanceAttachmentUncheckedUpdateWithoutRequestInput>
}

export type MaintenanceAttachmentUpdateManyWithWhereWithoutRequestInput = {
  where: Prisma.MaintenanceAttachmentScalarWhereInput
  data: Prisma.XOR<Prisma.MaintenanceAttachmentUpdateManyMutationInput, Prisma.MaintenanceAttachmentUncheckedUpdateManyWithoutRequestInput>
}

export type MaintenanceAttachmentScalarWhereInput = {
  AND?: Prisma.MaintenanceAttachmentScalarWhereInput | Prisma.MaintenanceAttachmentScalarWhereInput[]
  OR?: Prisma.MaintenanceAttachmentScalarWhereInput[]
  NOT?: Prisma.MaintenanceAttachmentScalarWhereInput | Prisma.MaintenanceAttachmentScalarWhereInput[]
  id?: Prisma.StringFilter<"MaintenanceAttachment"> | string
  requestId?: Prisma.StringFilter<"MaintenanceAttachment"> | string
  url?: Prisma.StringFilter<"MaintenanceAttachment"> | string
  cdnPath?: Prisma.StringNullableFilter<"MaintenanceAttachment"> | string | null
  kind?: Prisma.StringFilter<"MaintenanceAttachment"> | string
  contentType?: Prisma.StringNullableFilter<"MaintenanceAttachment"> | string | null
  sizeBytes?: Prisma.IntNullableFilter<"MaintenanceAttachment"> | number | null
  createdAt?: Prisma.DateTimeFilter<"MaintenanceAttachment"> | Date | string
}

export type MaintenanceAttachmentCreateManyRequestInput = {
  id?: string
  url: string
  cdnPath?: string | null
  kind?: string
  contentType?: string | null
  sizeBytes?: number | null
  createdAt?: Date | string
}

export type MaintenanceAttachmentUpdateWithoutRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kind?: Prisma.StringFieldUpdateOperationsInput | string
  contentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceAttachmentUncheckedUpdateWithoutRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kind?: Prisma.StringFieldUpdateOperationsInput | string
  contentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceAttachmentUncheckedUpdateManyWithoutRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  cdnPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kind?: Prisma.StringFieldUpdateOperationsInput | string
  contentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sizeBytes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MaintenanceAttachmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  url?: boolean
  cdnPath?: boolean
  kind?: boolean
  contentType?: boolean
  sizeBytes?: boolean
  createdAt?: boolean
  request?: boolean | Prisma.MaintenanceRequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["maintenanceAttachment"]>

export type MaintenanceAttachmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  url?: boolean
  cdnPath?: boolean
  kind?: boolean
  contentType?: boolean
  sizeBytes?: boolean
  createdAt?: boolean
  request?: boolean | Prisma.MaintenanceRequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["maintenanceAttachment"]>

export type MaintenanceAttachmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  url?: boolean
  cdnPath?: boolean
  kind?: boolean
  contentType?: boolean
  sizeBytes?: boolean
  createdAt?: boolean
  request?: boolean | Prisma.MaintenanceRequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["maintenanceAttachment"]>

export type MaintenanceAttachmentSelectScalar = {
  id?: boolean
  requestId?: boolean
  url?: boolean
  cdnPath?: boolean
  kind?: boolean
  contentType?: boolean
  sizeBytes?: boolean
  createdAt?: boolean
}

export type MaintenanceAttachmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "requestId" | "url" | "cdnPath" | "kind" | "contentType" | "sizeBytes" | "createdAt", ExtArgs["result"]["maintenanceAttachment"]>
export type MaintenanceAttachmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request?: boolean | Prisma.MaintenanceRequestDefaultArgs<ExtArgs>
}
export type MaintenanceAttachmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request?: boolean | Prisma.MaintenanceRequestDefaultArgs<ExtArgs>
}
export type MaintenanceAttachmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request?: boolean | Prisma.MaintenanceRequestDefaultArgs<ExtArgs>
}

export type $MaintenanceAttachmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MaintenanceAttachment"
  objects: {
    request: Prisma.$MaintenanceRequestPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    requestId: string
    url: string
    cdnPath: string | null
    kind: string
    contentType: string | null
    sizeBytes: number | null
    createdAt: Date
  }, ExtArgs["result"]["maintenanceAttachment"]>
  composites: {}
}

export type MaintenanceAttachmentGetPayload<S extends boolean | null | undefined | MaintenanceAttachmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MaintenanceAttachmentPayload, S>

export type MaintenanceAttachmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MaintenanceAttachmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MaintenanceAttachmentCountAggregateInputType | true
  }

export interface MaintenanceAttachmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MaintenanceAttachment'], meta: { name: 'MaintenanceAttachment' } }
  /**
   * Find zero or one MaintenanceAttachment that matches the filter.
   * @param {MaintenanceAttachmentFindUniqueArgs} args - Arguments to find a MaintenanceAttachment
   * @example
   * // Get one MaintenanceAttachment
   * const maintenanceAttachment = await prisma.maintenanceAttachment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MaintenanceAttachmentFindUniqueArgs>(args: Prisma.SelectSubset<T, MaintenanceAttachmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MaintenanceAttachmentClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceAttachmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MaintenanceAttachment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MaintenanceAttachmentFindUniqueOrThrowArgs} args - Arguments to find a MaintenanceAttachment
   * @example
   * // Get one MaintenanceAttachment
   * const maintenanceAttachment = await prisma.maintenanceAttachment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MaintenanceAttachmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MaintenanceAttachmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaintenanceAttachmentClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceAttachmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MaintenanceAttachment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceAttachmentFindFirstArgs} args - Arguments to find a MaintenanceAttachment
   * @example
   * // Get one MaintenanceAttachment
   * const maintenanceAttachment = await prisma.maintenanceAttachment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MaintenanceAttachmentFindFirstArgs>(args?: Prisma.SelectSubset<T, MaintenanceAttachmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__MaintenanceAttachmentClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceAttachmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MaintenanceAttachment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceAttachmentFindFirstOrThrowArgs} args - Arguments to find a MaintenanceAttachment
   * @example
   * // Get one MaintenanceAttachment
   * const maintenanceAttachment = await prisma.maintenanceAttachment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MaintenanceAttachmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MaintenanceAttachmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaintenanceAttachmentClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceAttachmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MaintenanceAttachments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceAttachmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MaintenanceAttachments
   * const maintenanceAttachments = await prisma.maintenanceAttachment.findMany()
   * 
   * // Get first 10 MaintenanceAttachments
   * const maintenanceAttachments = await prisma.maintenanceAttachment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const maintenanceAttachmentWithIdOnly = await prisma.maintenanceAttachment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MaintenanceAttachmentFindManyArgs>(args?: Prisma.SelectSubset<T, MaintenanceAttachmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaintenanceAttachmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MaintenanceAttachment.
   * @param {MaintenanceAttachmentCreateArgs} args - Arguments to create a MaintenanceAttachment.
   * @example
   * // Create one MaintenanceAttachment
   * const MaintenanceAttachment = await prisma.maintenanceAttachment.create({
   *   data: {
   *     // ... data to create a MaintenanceAttachment
   *   }
   * })
   * 
   */
  create<T extends MaintenanceAttachmentCreateArgs>(args: Prisma.SelectSubset<T, MaintenanceAttachmentCreateArgs<ExtArgs>>): Prisma.Prisma__MaintenanceAttachmentClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceAttachmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MaintenanceAttachments.
   * @param {MaintenanceAttachmentCreateManyArgs} args - Arguments to create many MaintenanceAttachments.
   * @example
   * // Create many MaintenanceAttachments
   * const maintenanceAttachment = await prisma.maintenanceAttachment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MaintenanceAttachmentCreateManyArgs>(args?: Prisma.SelectSubset<T, MaintenanceAttachmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MaintenanceAttachments and returns the data saved in the database.
   * @param {MaintenanceAttachmentCreateManyAndReturnArgs} args - Arguments to create many MaintenanceAttachments.
   * @example
   * // Create many MaintenanceAttachments
   * const maintenanceAttachment = await prisma.maintenanceAttachment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MaintenanceAttachments and only return the `id`
   * const maintenanceAttachmentWithIdOnly = await prisma.maintenanceAttachment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MaintenanceAttachmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MaintenanceAttachmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaintenanceAttachmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MaintenanceAttachment.
   * @param {MaintenanceAttachmentDeleteArgs} args - Arguments to delete one MaintenanceAttachment.
   * @example
   * // Delete one MaintenanceAttachment
   * const MaintenanceAttachment = await prisma.maintenanceAttachment.delete({
   *   where: {
   *     // ... filter to delete one MaintenanceAttachment
   *   }
   * })
   * 
   */
  delete<T extends MaintenanceAttachmentDeleteArgs>(args: Prisma.SelectSubset<T, MaintenanceAttachmentDeleteArgs<ExtArgs>>): Prisma.Prisma__MaintenanceAttachmentClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceAttachmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MaintenanceAttachment.
   * @param {MaintenanceAttachmentUpdateArgs} args - Arguments to update one MaintenanceAttachment.
   * @example
   * // Update one MaintenanceAttachment
   * const maintenanceAttachment = await prisma.maintenanceAttachment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MaintenanceAttachmentUpdateArgs>(args: Prisma.SelectSubset<T, MaintenanceAttachmentUpdateArgs<ExtArgs>>): Prisma.Prisma__MaintenanceAttachmentClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceAttachmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MaintenanceAttachments.
   * @param {MaintenanceAttachmentDeleteManyArgs} args - Arguments to filter MaintenanceAttachments to delete.
   * @example
   * // Delete a few MaintenanceAttachments
   * const { count } = await prisma.maintenanceAttachment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MaintenanceAttachmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, MaintenanceAttachmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MaintenanceAttachments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceAttachmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MaintenanceAttachments
   * const maintenanceAttachment = await prisma.maintenanceAttachment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MaintenanceAttachmentUpdateManyArgs>(args: Prisma.SelectSubset<T, MaintenanceAttachmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MaintenanceAttachments and returns the data updated in the database.
   * @param {MaintenanceAttachmentUpdateManyAndReturnArgs} args - Arguments to update many MaintenanceAttachments.
   * @example
   * // Update many MaintenanceAttachments
   * const maintenanceAttachment = await prisma.maintenanceAttachment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MaintenanceAttachments and only return the `id`
   * const maintenanceAttachmentWithIdOnly = await prisma.maintenanceAttachment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MaintenanceAttachmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MaintenanceAttachmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaintenanceAttachmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MaintenanceAttachment.
   * @param {MaintenanceAttachmentUpsertArgs} args - Arguments to update or create a MaintenanceAttachment.
   * @example
   * // Update or create a MaintenanceAttachment
   * const maintenanceAttachment = await prisma.maintenanceAttachment.upsert({
   *   create: {
   *     // ... data to create a MaintenanceAttachment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MaintenanceAttachment we want to update
   *   }
   * })
   */
  upsert<T extends MaintenanceAttachmentUpsertArgs>(args: Prisma.SelectSubset<T, MaintenanceAttachmentUpsertArgs<ExtArgs>>): Prisma.Prisma__MaintenanceAttachmentClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceAttachmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MaintenanceAttachments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceAttachmentCountArgs} args - Arguments to filter MaintenanceAttachments to count.
   * @example
   * // Count the number of MaintenanceAttachments
   * const count = await prisma.maintenanceAttachment.count({
   *   where: {
   *     // ... the filter for the MaintenanceAttachments we want to count
   *   }
   * })
  **/
  count<T extends MaintenanceAttachmentCountArgs>(
    args?: Prisma.Subset<T, MaintenanceAttachmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MaintenanceAttachmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MaintenanceAttachment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceAttachmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MaintenanceAttachmentAggregateArgs>(args: Prisma.Subset<T, MaintenanceAttachmentAggregateArgs>): Prisma.PrismaPromise<GetMaintenanceAttachmentAggregateType<T>>

  /**
   * Group by MaintenanceAttachment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceAttachmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MaintenanceAttachmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MaintenanceAttachmentGroupByArgs['orderBy'] }
      : { orderBy?: MaintenanceAttachmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MaintenanceAttachmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMaintenanceAttachmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MaintenanceAttachment model
 */
readonly fields: MaintenanceAttachmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MaintenanceAttachment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MaintenanceAttachmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  request<T extends Prisma.MaintenanceRequestDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MaintenanceRequestDefaultArgs<ExtArgs>>): Prisma.Prisma__MaintenanceRequestClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MaintenanceAttachment model
 */
export interface MaintenanceAttachmentFieldRefs {
  readonly id: Prisma.FieldRef<"MaintenanceAttachment", 'String'>
  readonly requestId: Prisma.FieldRef<"MaintenanceAttachment", 'String'>
  readonly url: Prisma.FieldRef<"MaintenanceAttachment", 'String'>
  readonly cdnPath: Prisma.FieldRef<"MaintenanceAttachment", 'String'>
  readonly kind: Prisma.FieldRef<"MaintenanceAttachment", 'String'>
  readonly contentType: Prisma.FieldRef<"MaintenanceAttachment", 'String'>
  readonly sizeBytes: Prisma.FieldRef<"MaintenanceAttachment", 'Int'>
  readonly createdAt: Prisma.FieldRef<"MaintenanceAttachment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MaintenanceAttachment findUnique
 */
export type MaintenanceAttachmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceAttachment
   */
  select?: Prisma.MaintenanceAttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceAttachment
   */
  omit?: Prisma.MaintenanceAttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceAttachmentInclude<ExtArgs> | null
  /**
   * Filter, which MaintenanceAttachment to fetch.
   */
  where: Prisma.MaintenanceAttachmentWhereUniqueInput
}

/**
 * MaintenanceAttachment findUniqueOrThrow
 */
export type MaintenanceAttachmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceAttachment
   */
  select?: Prisma.MaintenanceAttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceAttachment
   */
  omit?: Prisma.MaintenanceAttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceAttachmentInclude<ExtArgs> | null
  /**
   * Filter, which MaintenanceAttachment to fetch.
   */
  where: Prisma.MaintenanceAttachmentWhereUniqueInput
}

/**
 * MaintenanceAttachment findFirst
 */
export type MaintenanceAttachmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceAttachment
   */
  select?: Prisma.MaintenanceAttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceAttachment
   */
  omit?: Prisma.MaintenanceAttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceAttachmentInclude<ExtArgs> | null
  /**
   * Filter, which MaintenanceAttachment to fetch.
   */
  where?: Prisma.MaintenanceAttachmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaintenanceAttachments to fetch.
   */
  orderBy?: Prisma.MaintenanceAttachmentOrderByWithRelationInput | Prisma.MaintenanceAttachmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MaintenanceAttachments.
   */
  cursor?: Prisma.MaintenanceAttachmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaintenanceAttachments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaintenanceAttachments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MaintenanceAttachments.
   */
  distinct?: Prisma.MaintenanceAttachmentScalarFieldEnum | Prisma.MaintenanceAttachmentScalarFieldEnum[]
}

/**
 * MaintenanceAttachment findFirstOrThrow
 */
export type MaintenanceAttachmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceAttachment
   */
  select?: Prisma.MaintenanceAttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceAttachment
   */
  omit?: Prisma.MaintenanceAttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceAttachmentInclude<ExtArgs> | null
  /**
   * Filter, which MaintenanceAttachment to fetch.
   */
  where?: Prisma.MaintenanceAttachmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaintenanceAttachments to fetch.
   */
  orderBy?: Prisma.MaintenanceAttachmentOrderByWithRelationInput | Prisma.MaintenanceAttachmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MaintenanceAttachments.
   */
  cursor?: Prisma.MaintenanceAttachmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaintenanceAttachments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaintenanceAttachments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MaintenanceAttachments.
   */
  distinct?: Prisma.MaintenanceAttachmentScalarFieldEnum | Prisma.MaintenanceAttachmentScalarFieldEnum[]
}

/**
 * MaintenanceAttachment findMany
 */
export type MaintenanceAttachmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceAttachment
   */
  select?: Prisma.MaintenanceAttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceAttachment
   */
  omit?: Prisma.MaintenanceAttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceAttachmentInclude<ExtArgs> | null
  /**
   * Filter, which MaintenanceAttachments to fetch.
   */
  where?: Prisma.MaintenanceAttachmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaintenanceAttachments to fetch.
   */
  orderBy?: Prisma.MaintenanceAttachmentOrderByWithRelationInput | Prisma.MaintenanceAttachmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MaintenanceAttachments.
   */
  cursor?: Prisma.MaintenanceAttachmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaintenanceAttachments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaintenanceAttachments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MaintenanceAttachments.
   */
  distinct?: Prisma.MaintenanceAttachmentScalarFieldEnum | Prisma.MaintenanceAttachmentScalarFieldEnum[]
}

/**
 * MaintenanceAttachment create
 */
export type MaintenanceAttachmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceAttachment
   */
  select?: Prisma.MaintenanceAttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceAttachment
   */
  omit?: Prisma.MaintenanceAttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceAttachmentInclude<ExtArgs> | null
  /**
   * The data needed to create a MaintenanceAttachment.
   */
  data: Prisma.XOR<Prisma.MaintenanceAttachmentCreateInput, Prisma.MaintenanceAttachmentUncheckedCreateInput>
}

/**
 * MaintenanceAttachment createMany
 */
export type MaintenanceAttachmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MaintenanceAttachments.
   */
  data: Prisma.MaintenanceAttachmentCreateManyInput | Prisma.MaintenanceAttachmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MaintenanceAttachment createManyAndReturn
 */
export type MaintenanceAttachmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceAttachment
   */
  select?: Prisma.MaintenanceAttachmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceAttachment
   */
  omit?: Prisma.MaintenanceAttachmentOmit<ExtArgs> | null
  /**
   * The data used to create many MaintenanceAttachments.
   */
  data: Prisma.MaintenanceAttachmentCreateManyInput | Prisma.MaintenanceAttachmentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceAttachmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MaintenanceAttachment update
 */
export type MaintenanceAttachmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceAttachment
   */
  select?: Prisma.MaintenanceAttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceAttachment
   */
  omit?: Prisma.MaintenanceAttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceAttachmentInclude<ExtArgs> | null
  /**
   * The data needed to update a MaintenanceAttachment.
   */
  data: Prisma.XOR<Prisma.MaintenanceAttachmentUpdateInput, Prisma.MaintenanceAttachmentUncheckedUpdateInput>
  /**
   * Choose, which MaintenanceAttachment to update.
   */
  where: Prisma.MaintenanceAttachmentWhereUniqueInput
}

/**
 * MaintenanceAttachment updateMany
 */
export type MaintenanceAttachmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MaintenanceAttachments.
   */
  data: Prisma.XOR<Prisma.MaintenanceAttachmentUpdateManyMutationInput, Prisma.MaintenanceAttachmentUncheckedUpdateManyInput>
  /**
   * Filter which MaintenanceAttachments to update
   */
  where?: Prisma.MaintenanceAttachmentWhereInput
  /**
   * Limit how many MaintenanceAttachments to update.
   */
  limit?: number
}

/**
 * MaintenanceAttachment updateManyAndReturn
 */
export type MaintenanceAttachmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceAttachment
   */
  select?: Prisma.MaintenanceAttachmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceAttachment
   */
  omit?: Prisma.MaintenanceAttachmentOmit<ExtArgs> | null
  /**
   * The data used to update MaintenanceAttachments.
   */
  data: Prisma.XOR<Prisma.MaintenanceAttachmentUpdateManyMutationInput, Prisma.MaintenanceAttachmentUncheckedUpdateManyInput>
  /**
   * Filter which MaintenanceAttachments to update
   */
  where?: Prisma.MaintenanceAttachmentWhereInput
  /**
   * Limit how many MaintenanceAttachments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceAttachmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MaintenanceAttachment upsert
 */
export type MaintenanceAttachmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceAttachment
   */
  select?: Prisma.MaintenanceAttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceAttachment
   */
  omit?: Prisma.MaintenanceAttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceAttachmentInclude<ExtArgs> | null
  /**
   * The filter to search for the MaintenanceAttachment to update in case it exists.
   */
  where: Prisma.MaintenanceAttachmentWhereUniqueInput
  /**
   * In case the MaintenanceAttachment found by the `where` argument doesn't exist, create a new MaintenanceAttachment with this data.
   */
  create: Prisma.XOR<Prisma.MaintenanceAttachmentCreateInput, Prisma.MaintenanceAttachmentUncheckedCreateInput>
  /**
   * In case the MaintenanceAttachment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MaintenanceAttachmentUpdateInput, Prisma.MaintenanceAttachmentUncheckedUpdateInput>
}

/**
 * MaintenanceAttachment delete
 */
export type MaintenanceAttachmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceAttachment
   */
  select?: Prisma.MaintenanceAttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceAttachment
   */
  omit?: Prisma.MaintenanceAttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceAttachmentInclude<ExtArgs> | null
  /**
   * Filter which MaintenanceAttachment to delete.
   */
  where: Prisma.MaintenanceAttachmentWhereUniqueInput
}

/**
 * MaintenanceAttachment deleteMany
 */
export type MaintenanceAttachmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MaintenanceAttachments to delete
   */
  where?: Prisma.MaintenanceAttachmentWhereInput
  /**
   * Limit how many MaintenanceAttachments to delete.
   */
  limit?: number
}

/**
 * MaintenanceAttachment without action
 */
export type MaintenanceAttachmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceAttachment
   */
  select?: Prisma.MaintenanceAttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceAttachment
   */
  omit?: Prisma.MaintenanceAttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceAttachmentInclude<ExtArgs> | null
}
