
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ManagedItemType` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ManagedItemType
 * 
 */
export type ManagedItemTypeModel = runtime.Types.Result.DefaultSelection<Prisma.$ManagedItemTypePayload>

export type AggregateManagedItemType = {
  _count: ManagedItemTypeCountAggregateOutputType | null
  _min: ManagedItemTypeMinAggregateOutputType | null
  _max: ManagedItemTypeMaxAggregateOutputType | null
}

export type ManagedItemTypeMinAggregateOutputType = {
  id: string | null
  name: string | null
  notes: string | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ManagedItemTypeMaxAggregateOutputType = {
  id: string | null
  name: string | null
  notes: string | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ManagedItemTypeCountAggregateOutputType = {
  id: number
  name: number
  notes: number
  active: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ManagedItemTypeMinAggregateInputType = {
  id?: true
  name?: true
  notes?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type ManagedItemTypeMaxAggregateInputType = {
  id?: true
  name?: true
  notes?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type ManagedItemTypeCountAggregateInputType = {
  id?: true
  name?: true
  notes?: true
  active?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ManagedItemTypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ManagedItemType to aggregate.
   */
  where?: Prisma.ManagedItemTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManagedItemTypes to fetch.
   */
  orderBy?: Prisma.ManagedItemTypeOrderByWithRelationInput | Prisma.ManagedItemTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ManagedItemTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManagedItemTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManagedItemTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ManagedItemTypes
  **/
  _count?: true | ManagedItemTypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ManagedItemTypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ManagedItemTypeMaxAggregateInputType
}

export type GetManagedItemTypeAggregateType<T extends ManagedItemTypeAggregateArgs> = {
      [P in keyof T & keyof AggregateManagedItemType]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateManagedItemType[P]>
    : Prisma.GetScalarType<T[P], AggregateManagedItemType[P]>
}




export type ManagedItemTypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ManagedItemTypeWhereInput
  orderBy?: Prisma.ManagedItemTypeOrderByWithAggregationInput | Prisma.ManagedItemTypeOrderByWithAggregationInput[]
  by: Prisma.ManagedItemTypeScalarFieldEnum[] | Prisma.ManagedItemTypeScalarFieldEnum
  having?: Prisma.ManagedItemTypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ManagedItemTypeCountAggregateInputType | true
  _min?: ManagedItemTypeMinAggregateInputType
  _max?: ManagedItemTypeMaxAggregateInputType
}

export type ManagedItemTypeGroupByOutputType = {
  id: string
  name: string
  notes: string | null
  active: boolean
  createdAt: Date
  updatedAt: Date
  _count: ManagedItemTypeCountAggregateOutputType | null
  _min: ManagedItemTypeMinAggregateOutputType | null
  _max: ManagedItemTypeMaxAggregateOutputType | null
}

export type GetManagedItemTypeGroupByPayload<T extends ManagedItemTypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ManagedItemTypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ManagedItemTypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ManagedItemTypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ManagedItemTypeGroupByOutputType[P]>
      }
    >
  >



export type ManagedItemTypeWhereInput = {
  AND?: Prisma.ManagedItemTypeWhereInput | Prisma.ManagedItemTypeWhereInput[]
  OR?: Prisma.ManagedItemTypeWhereInput[]
  NOT?: Prisma.ManagedItemTypeWhereInput | Prisma.ManagedItemTypeWhereInput[]
  id?: Prisma.StringFilter<"ManagedItemType"> | string
  name?: Prisma.StringFilter<"ManagedItemType"> | string
  notes?: Prisma.StringNullableFilter<"ManagedItemType"> | string | null
  active?: Prisma.BoolFilter<"ManagedItemType"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ManagedItemType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ManagedItemType"> | Date | string
  items?: Prisma.ManagedItemListRelationFilter
}

export type ManagedItemTypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  items?: Prisma.ManagedItemOrderByRelationAggregateInput
}

export type ManagedItemTypeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.ManagedItemTypeWhereInput | Prisma.ManagedItemTypeWhereInput[]
  OR?: Prisma.ManagedItemTypeWhereInput[]
  NOT?: Prisma.ManagedItemTypeWhereInput | Prisma.ManagedItemTypeWhereInput[]
  notes?: Prisma.StringNullableFilter<"ManagedItemType"> | string | null
  active?: Prisma.BoolFilter<"ManagedItemType"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ManagedItemType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ManagedItemType"> | Date | string
  items?: Prisma.ManagedItemListRelationFilter
}, "id" | "name">

export type ManagedItemTypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ManagedItemTypeCountOrderByAggregateInput
  _max?: Prisma.ManagedItemTypeMaxOrderByAggregateInput
  _min?: Prisma.ManagedItemTypeMinOrderByAggregateInput
}

export type ManagedItemTypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.ManagedItemTypeScalarWhereWithAggregatesInput | Prisma.ManagedItemTypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.ManagedItemTypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ManagedItemTypeScalarWhereWithAggregatesInput | Prisma.ManagedItemTypeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ManagedItemType"> | string
  name?: Prisma.StringWithAggregatesFilter<"ManagedItemType"> | string
  notes?: Prisma.StringNullableWithAggregatesFilter<"ManagedItemType"> | string | null
  active?: Prisma.BoolWithAggregatesFilter<"ManagedItemType"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ManagedItemType"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ManagedItemType"> | Date | string
}

export type ManagedItemTypeCreateInput = {
  id?: string
  name: string
  notes?: string | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.ManagedItemCreateNestedManyWithoutItemTypeInput
}

export type ManagedItemTypeUncheckedCreateInput = {
  id?: string
  name: string
  notes?: string | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.ManagedItemUncheckedCreateNestedManyWithoutItemTypeInput
}

export type ManagedItemTypeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.ManagedItemUpdateManyWithoutItemTypeNestedInput
}

export type ManagedItemTypeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.ManagedItemUncheckedUpdateManyWithoutItemTypeNestedInput
}

export type ManagedItemTypeCreateManyInput = {
  id?: string
  name: string
  notes?: string | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ManagedItemTypeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManagedItemTypeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManagedItemTypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ManagedItemTypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ManagedItemTypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ManagedItemTypeScalarRelationFilter = {
  is?: Prisma.ManagedItemTypeWhereInput
  isNot?: Prisma.ManagedItemTypeWhereInput
}

export type ManagedItemTypeCreateNestedOneWithoutItemsInput = {
  create?: Prisma.XOR<Prisma.ManagedItemTypeCreateWithoutItemsInput, Prisma.ManagedItemTypeUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.ManagedItemTypeCreateOrConnectWithoutItemsInput
  connect?: Prisma.ManagedItemTypeWhereUniqueInput
}

export type ManagedItemTypeUpdateOneRequiredWithoutItemsNestedInput = {
  create?: Prisma.XOR<Prisma.ManagedItemTypeCreateWithoutItemsInput, Prisma.ManagedItemTypeUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.ManagedItemTypeCreateOrConnectWithoutItemsInput
  upsert?: Prisma.ManagedItemTypeUpsertWithoutItemsInput
  connect?: Prisma.ManagedItemTypeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ManagedItemTypeUpdateToOneWithWhereWithoutItemsInput, Prisma.ManagedItemTypeUpdateWithoutItemsInput>, Prisma.ManagedItemTypeUncheckedUpdateWithoutItemsInput>
}

export type ManagedItemTypeCreateWithoutItemsInput = {
  id?: string
  name: string
  notes?: string | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ManagedItemTypeUncheckedCreateWithoutItemsInput = {
  id?: string
  name: string
  notes?: string | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ManagedItemTypeCreateOrConnectWithoutItemsInput = {
  where: Prisma.ManagedItemTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.ManagedItemTypeCreateWithoutItemsInput, Prisma.ManagedItemTypeUncheckedCreateWithoutItemsInput>
}

export type ManagedItemTypeUpsertWithoutItemsInput = {
  update: Prisma.XOR<Prisma.ManagedItemTypeUpdateWithoutItemsInput, Prisma.ManagedItemTypeUncheckedUpdateWithoutItemsInput>
  create: Prisma.XOR<Prisma.ManagedItemTypeCreateWithoutItemsInput, Prisma.ManagedItemTypeUncheckedCreateWithoutItemsInput>
  where?: Prisma.ManagedItemTypeWhereInput
}

export type ManagedItemTypeUpdateToOneWithWhereWithoutItemsInput = {
  where?: Prisma.ManagedItemTypeWhereInput
  data: Prisma.XOR<Prisma.ManagedItemTypeUpdateWithoutItemsInput, Prisma.ManagedItemTypeUncheckedUpdateWithoutItemsInput>
}

export type ManagedItemTypeUpdateWithoutItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManagedItemTypeUncheckedUpdateWithoutItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ManagedItemTypeCountOutputType
 */

export type ManagedItemTypeCountOutputType = {
  items: number
}

export type ManagedItemTypeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | ManagedItemTypeCountOutputTypeCountItemsArgs
}

/**
 * ManagedItemTypeCountOutputType without action
 */
export type ManagedItemTypeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagedItemTypeCountOutputType
   */
  select?: Prisma.ManagedItemTypeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ManagedItemTypeCountOutputType without action
 */
export type ManagedItemTypeCountOutputTypeCountItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ManagedItemWhereInput
}


export type ManagedItemTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  notes?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  items?: boolean | Prisma.ManagedItemType$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.ManagedItemTypeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["managedItemType"]>

export type ManagedItemTypeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  notes?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["managedItemType"]>

export type ManagedItemTypeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  notes?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["managedItemType"]>

export type ManagedItemTypeSelectScalar = {
  id?: boolean
  name?: boolean
  notes?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ManagedItemTypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "notes" | "active" | "createdAt" | "updatedAt", ExtArgs["result"]["managedItemType"]>
export type ManagedItemTypeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | Prisma.ManagedItemType$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.ManagedItemTypeCountOutputTypeDefaultArgs<ExtArgs>
}
export type ManagedItemTypeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ManagedItemTypeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ManagedItemTypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ManagedItemType"
  objects: {
    items: Prisma.$ManagedItemPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    notes: string | null
    active: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["managedItemType"]>
  composites: {}
}

export type ManagedItemTypeGetPayload<S extends boolean | null | undefined | ManagedItemTypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ManagedItemTypePayload, S>

export type ManagedItemTypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ManagedItemTypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ManagedItemTypeCountAggregateInputType | true
  }

export interface ManagedItemTypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ManagedItemType'], meta: { name: 'ManagedItemType' } }
  /**
   * Find zero or one ManagedItemType that matches the filter.
   * @param {ManagedItemTypeFindUniqueArgs} args - Arguments to find a ManagedItemType
   * @example
   * // Get one ManagedItemType
   * const managedItemType = await prisma.managedItemType.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ManagedItemTypeFindUniqueArgs>(args: Prisma.SelectSubset<T, ManagedItemTypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ManagedItemTypeClient<runtime.Types.Result.GetResult<Prisma.$ManagedItemTypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ManagedItemType that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ManagedItemTypeFindUniqueOrThrowArgs} args - Arguments to find a ManagedItemType
   * @example
   * // Get one ManagedItemType
   * const managedItemType = await prisma.managedItemType.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ManagedItemTypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ManagedItemTypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ManagedItemTypeClient<runtime.Types.Result.GetResult<Prisma.$ManagedItemTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ManagedItemType that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManagedItemTypeFindFirstArgs} args - Arguments to find a ManagedItemType
   * @example
   * // Get one ManagedItemType
   * const managedItemType = await prisma.managedItemType.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ManagedItemTypeFindFirstArgs>(args?: Prisma.SelectSubset<T, ManagedItemTypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__ManagedItemTypeClient<runtime.Types.Result.GetResult<Prisma.$ManagedItemTypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ManagedItemType that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManagedItemTypeFindFirstOrThrowArgs} args - Arguments to find a ManagedItemType
   * @example
   * // Get one ManagedItemType
   * const managedItemType = await prisma.managedItemType.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ManagedItemTypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ManagedItemTypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ManagedItemTypeClient<runtime.Types.Result.GetResult<Prisma.$ManagedItemTypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ManagedItemTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManagedItemTypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ManagedItemTypes
   * const managedItemTypes = await prisma.managedItemType.findMany()
   * 
   * // Get first 10 ManagedItemTypes
   * const managedItemTypes = await prisma.managedItemType.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const managedItemTypeWithIdOnly = await prisma.managedItemType.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ManagedItemTypeFindManyArgs>(args?: Prisma.SelectSubset<T, ManagedItemTypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManagedItemTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ManagedItemType.
   * @param {ManagedItemTypeCreateArgs} args - Arguments to create a ManagedItemType.
   * @example
   * // Create one ManagedItemType
   * const ManagedItemType = await prisma.managedItemType.create({
   *   data: {
   *     // ... data to create a ManagedItemType
   *   }
   * })
   * 
   */
  create<T extends ManagedItemTypeCreateArgs>(args: Prisma.SelectSubset<T, ManagedItemTypeCreateArgs<ExtArgs>>): Prisma.Prisma__ManagedItemTypeClient<runtime.Types.Result.GetResult<Prisma.$ManagedItemTypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ManagedItemTypes.
   * @param {ManagedItemTypeCreateManyArgs} args - Arguments to create many ManagedItemTypes.
   * @example
   * // Create many ManagedItemTypes
   * const managedItemType = await prisma.managedItemType.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ManagedItemTypeCreateManyArgs>(args?: Prisma.SelectSubset<T, ManagedItemTypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ManagedItemTypes and returns the data saved in the database.
   * @param {ManagedItemTypeCreateManyAndReturnArgs} args - Arguments to create many ManagedItemTypes.
   * @example
   * // Create many ManagedItemTypes
   * const managedItemType = await prisma.managedItemType.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ManagedItemTypes and only return the `id`
   * const managedItemTypeWithIdOnly = await prisma.managedItemType.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ManagedItemTypeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ManagedItemTypeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManagedItemTypePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ManagedItemType.
   * @param {ManagedItemTypeDeleteArgs} args - Arguments to delete one ManagedItemType.
   * @example
   * // Delete one ManagedItemType
   * const ManagedItemType = await prisma.managedItemType.delete({
   *   where: {
   *     // ... filter to delete one ManagedItemType
   *   }
   * })
   * 
   */
  delete<T extends ManagedItemTypeDeleteArgs>(args: Prisma.SelectSubset<T, ManagedItemTypeDeleteArgs<ExtArgs>>): Prisma.Prisma__ManagedItemTypeClient<runtime.Types.Result.GetResult<Prisma.$ManagedItemTypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ManagedItemType.
   * @param {ManagedItemTypeUpdateArgs} args - Arguments to update one ManagedItemType.
   * @example
   * // Update one ManagedItemType
   * const managedItemType = await prisma.managedItemType.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ManagedItemTypeUpdateArgs>(args: Prisma.SelectSubset<T, ManagedItemTypeUpdateArgs<ExtArgs>>): Prisma.Prisma__ManagedItemTypeClient<runtime.Types.Result.GetResult<Prisma.$ManagedItemTypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ManagedItemTypes.
   * @param {ManagedItemTypeDeleteManyArgs} args - Arguments to filter ManagedItemTypes to delete.
   * @example
   * // Delete a few ManagedItemTypes
   * const { count } = await prisma.managedItemType.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ManagedItemTypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, ManagedItemTypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ManagedItemTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManagedItemTypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ManagedItemTypes
   * const managedItemType = await prisma.managedItemType.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ManagedItemTypeUpdateManyArgs>(args: Prisma.SelectSubset<T, ManagedItemTypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ManagedItemTypes and returns the data updated in the database.
   * @param {ManagedItemTypeUpdateManyAndReturnArgs} args - Arguments to update many ManagedItemTypes.
   * @example
   * // Update many ManagedItemTypes
   * const managedItemType = await prisma.managedItemType.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ManagedItemTypes and only return the `id`
   * const managedItemTypeWithIdOnly = await prisma.managedItemType.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ManagedItemTypeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ManagedItemTypeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManagedItemTypePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ManagedItemType.
   * @param {ManagedItemTypeUpsertArgs} args - Arguments to update or create a ManagedItemType.
   * @example
   * // Update or create a ManagedItemType
   * const managedItemType = await prisma.managedItemType.upsert({
   *   create: {
   *     // ... data to create a ManagedItemType
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ManagedItemType we want to update
   *   }
   * })
   */
  upsert<T extends ManagedItemTypeUpsertArgs>(args: Prisma.SelectSubset<T, ManagedItemTypeUpsertArgs<ExtArgs>>): Prisma.Prisma__ManagedItemTypeClient<runtime.Types.Result.GetResult<Prisma.$ManagedItemTypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ManagedItemTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManagedItemTypeCountArgs} args - Arguments to filter ManagedItemTypes to count.
   * @example
   * // Count the number of ManagedItemTypes
   * const count = await prisma.managedItemType.count({
   *   where: {
   *     // ... the filter for the ManagedItemTypes we want to count
   *   }
   * })
  **/
  count<T extends ManagedItemTypeCountArgs>(
    args?: Prisma.Subset<T, ManagedItemTypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ManagedItemTypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ManagedItemType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManagedItemTypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ManagedItemTypeAggregateArgs>(args: Prisma.Subset<T, ManagedItemTypeAggregateArgs>): Prisma.PrismaPromise<GetManagedItemTypeAggregateType<T>>

  /**
   * Group by ManagedItemType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManagedItemTypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ManagedItemTypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ManagedItemTypeGroupByArgs['orderBy'] }
      : { orderBy?: ManagedItemTypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ManagedItemTypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetManagedItemTypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ManagedItemType model
 */
readonly fields: ManagedItemTypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ManagedItemType.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ManagedItemTypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  items<T extends Prisma.ManagedItemType$itemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ManagedItemType$itemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManagedItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ManagedItemType model
 */
export interface ManagedItemTypeFieldRefs {
  readonly id: Prisma.FieldRef<"ManagedItemType", 'String'>
  readonly name: Prisma.FieldRef<"ManagedItemType", 'String'>
  readonly notes: Prisma.FieldRef<"ManagedItemType", 'String'>
  readonly active: Prisma.FieldRef<"ManagedItemType", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"ManagedItemType", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ManagedItemType", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ManagedItemType findUnique
 */
export type ManagedItemTypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagedItemType
   */
  select?: Prisma.ManagedItemTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagedItemType
   */
  omit?: Prisma.ManagedItemTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagedItemTypeInclude<ExtArgs> | null
  /**
   * Filter, which ManagedItemType to fetch.
   */
  where: Prisma.ManagedItemTypeWhereUniqueInput
}

/**
 * ManagedItemType findUniqueOrThrow
 */
export type ManagedItemTypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagedItemType
   */
  select?: Prisma.ManagedItemTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagedItemType
   */
  omit?: Prisma.ManagedItemTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagedItemTypeInclude<ExtArgs> | null
  /**
   * Filter, which ManagedItemType to fetch.
   */
  where: Prisma.ManagedItemTypeWhereUniqueInput
}

/**
 * ManagedItemType findFirst
 */
export type ManagedItemTypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagedItemType
   */
  select?: Prisma.ManagedItemTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagedItemType
   */
  omit?: Prisma.ManagedItemTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagedItemTypeInclude<ExtArgs> | null
  /**
   * Filter, which ManagedItemType to fetch.
   */
  where?: Prisma.ManagedItemTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManagedItemTypes to fetch.
   */
  orderBy?: Prisma.ManagedItemTypeOrderByWithRelationInput | Prisma.ManagedItemTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ManagedItemTypes.
   */
  cursor?: Prisma.ManagedItemTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManagedItemTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManagedItemTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ManagedItemTypes.
   */
  distinct?: Prisma.ManagedItemTypeScalarFieldEnum | Prisma.ManagedItemTypeScalarFieldEnum[]
}

/**
 * ManagedItemType findFirstOrThrow
 */
export type ManagedItemTypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagedItemType
   */
  select?: Prisma.ManagedItemTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagedItemType
   */
  omit?: Prisma.ManagedItemTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagedItemTypeInclude<ExtArgs> | null
  /**
   * Filter, which ManagedItemType to fetch.
   */
  where?: Prisma.ManagedItemTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManagedItemTypes to fetch.
   */
  orderBy?: Prisma.ManagedItemTypeOrderByWithRelationInput | Prisma.ManagedItemTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ManagedItemTypes.
   */
  cursor?: Prisma.ManagedItemTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManagedItemTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManagedItemTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ManagedItemTypes.
   */
  distinct?: Prisma.ManagedItemTypeScalarFieldEnum | Prisma.ManagedItemTypeScalarFieldEnum[]
}

/**
 * ManagedItemType findMany
 */
export type ManagedItemTypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagedItemType
   */
  select?: Prisma.ManagedItemTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagedItemType
   */
  omit?: Prisma.ManagedItemTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagedItemTypeInclude<ExtArgs> | null
  /**
   * Filter, which ManagedItemTypes to fetch.
   */
  where?: Prisma.ManagedItemTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManagedItemTypes to fetch.
   */
  orderBy?: Prisma.ManagedItemTypeOrderByWithRelationInput | Prisma.ManagedItemTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ManagedItemTypes.
   */
  cursor?: Prisma.ManagedItemTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManagedItemTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManagedItemTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ManagedItemTypes.
   */
  distinct?: Prisma.ManagedItemTypeScalarFieldEnum | Prisma.ManagedItemTypeScalarFieldEnum[]
}

/**
 * ManagedItemType create
 */
export type ManagedItemTypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagedItemType
   */
  select?: Prisma.ManagedItemTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagedItemType
   */
  omit?: Prisma.ManagedItemTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagedItemTypeInclude<ExtArgs> | null
  /**
   * The data needed to create a ManagedItemType.
   */
  data: Prisma.XOR<Prisma.ManagedItemTypeCreateInput, Prisma.ManagedItemTypeUncheckedCreateInput>
}

/**
 * ManagedItemType createMany
 */
export type ManagedItemTypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ManagedItemTypes.
   */
  data: Prisma.ManagedItemTypeCreateManyInput | Prisma.ManagedItemTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ManagedItemType createManyAndReturn
 */
export type ManagedItemTypeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagedItemType
   */
  select?: Prisma.ManagedItemTypeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ManagedItemType
   */
  omit?: Prisma.ManagedItemTypeOmit<ExtArgs> | null
  /**
   * The data used to create many ManagedItemTypes.
   */
  data: Prisma.ManagedItemTypeCreateManyInput | Prisma.ManagedItemTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ManagedItemType update
 */
export type ManagedItemTypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagedItemType
   */
  select?: Prisma.ManagedItemTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagedItemType
   */
  omit?: Prisma.ManagedItemTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagedItemTypeInclude<ExtArgs> | null
  /**
   * The data needed to update a ManagedItemType.
   */
  data: Prisma.XOR<Prisma.ManagedItemTypeUpdateInput, Prisma.ManagedItemTypeUncheckedUpdateInput>
  /**
   * Choose, which ManagedItemType to update.
   */
  where: Prisma.ManagedItemTypeWhereUniqueInput
}

/**
 * ManagedItemType updateMany
 */
export type ManagedItemTypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ManagedItemTypes.
   */
  data: Prisma.XOR<Prisma.ManagedItemTypeUpdateManyMutationInput, Prisma.ManagedItemTypeUncheckedUpdateManyInput>
  /**
   * Filter which ManagedItemTypes to update
   */
  where?: Prisma.ManagedItemTypeWhereInput
  /**
   * Limit how many ManagedItemTypes to update.
   */
  limit?: number
}

/**
 * ManagedItemType updateManyAndReturn
 */
export type ManagedItemTypeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagedItemType
   */
  select?: Prisma.ManagedItemTypeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ManagedItemType
   */
  omit?: Prisma.ManagedItemTypeOmit<ExtArgs> | null
  /**
   * The data used to update ManagedItemTypes.
   */
  data: Prisma.XOR<Prisma.ManagedItemTypeUpdateManyMutationInput, Prisma.ManagedItemTypeUncheckedUpdateManyInput>
  /**
   * Filter which ManagedItemTypes to update
   */
  where?: Prisma.ManagedItemTypeWhereInput
  /**
   * Limit how many ManagedItemTypes to update.
   */
  limit?: number
}

/**
 * ManagedItemType upsert
 */
export type ManagedItemTypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagedItemType
   */
  select?: Prisma.ManagedItemTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagedItemType
   */
  omit?: Prisma.ManagedItemTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagedItemTypeInclude<ExtArgs> | null
  /**
   * The filter to search for the ManagedItemType to update in case it exists.
   */
  where: Prisma.ManagedItemTypeWhereUniqueInput
  /**
   * In case the ManagedItemType found by the `where` argument doesn't exist, create a new ManagedItemType with this data.
   */
  create: Prisma.XOR<Prisma.ManagedItemTypeCreateInput, Prisma.ManagedItemTypeUncheckedCreateInput>
  /**
   * In case the ManagedItemType was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ManagedItemTypeUpdateInput, Prisma.ManagedItemTypeUncheckedUpdateInput>
}

/**
 * ManagedItemType delete
 */
export type ManagedItemTypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagedItemType
   */
  select?: Prisma.ManagedItemTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagedItemType
   */
  omit?: Prisma.ManagedItemTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagedItemTypeInclude<ExtArgs> | null
  /**
   * Filter which ManagedItemType to delete.
   */
  where: Prisma.ManagedItemTypeWhereUniqueInput
}

/**
 * ManagedItemType deleteMany
 */
export type ManagedItemTypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ManagedItemTypes to delete
   */
  where?: Prisma.ManagedItemTypeWhereInput
  /**
   * Limit how many ManagedItemTypes to delete.
   */
  limit?: number
}

/**
 * ManagedItemType.items
 */
export type ManagedItemType$itemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagedItem
   */
  select?: Prisma.ManagedItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagedItem
   */
  omit?: Prisma.ManagedItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagedItemInclude<ExtArgs> | null
  where?: Prisma.ManagedItemWhereInput
  orderBy?: Prisma.ManagedItemOrderByWithRelationInput | Prisma.ManagedItemOrderByWithRelationInput[]
  cursor?: Prisma.ManagedItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ManagedItemScalarFieldEnum | Prisma.ManagedItemScalarFieldEnum[]
}

/**
 * ManagedItemType without action
 */
export type ManagedItemTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManagedItemType
   */
  select?: Prisma.ManagedItemTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManagedItemType
   */
  omit?: Prisma.ManagedItemTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManagedItemTypeInclude<ExtArgs> | null
}
