
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RfqInvitation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RfqInvitation
 * 
 */
export type RfqInvitationModel = runtime.Types.Result.DefaultSelection<Prisma.$RfqInvitationPayload>

export type AggregateRfqInvitation = {
  _count: RfqInvitationCountAggregateOutputType | null
  _min: RfqInvitationMinAggregateOutputType | null
  _max: RfqInvitationMaxAggregateOutputType | null
}

export type RfqInvitationMinAggregateOutputType = {
  id: string | null
  rfqId: string | null
  supplierId: string | null
  status: string | null
  sentAt: Date | null
  viewedAt: Date | null
  declineReason: string | null
}

export type RfqInvitationMaxAggregateOutputType = {
  id: string | null
  rfqId: string | null
  supplierId: string | null
  status: string | null
  sentAt: Date | null
  viewedAt: Date | null
  declineReason: string | null
}

export type RfqInvitationCountAggregateOutputType = {
  id: number
  rfqId: number
  supplierId: number
  status: number
  sentAt: number
  viewedAt: number
  declineReason: number
  _all: number
}


export type RfqInvitationMinAggregateInputType = {
  id?: true
  rfqId?: true
  supplierId?: true
  status?: true
  sentAt?: true
  viewedAt?: true
  declineReason?: true
}

export type RfqInvitationMaxAggregateInputType = {
  id?: true
  rfqId?: true
  supplierId?: true
  status?: true
  sentAt?: true
  viewedAt?: true
  declineReason?: true
}

export type RfqInvitationCountAggregateInputType = {
  id?: true
  rfqId?: true
  supplierId?: true
  status?: true
  sentAt?: true
  viewedAt?: true
  declineReason?: true
  _all?: true
}

export type RfqInvitationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RfqInvitation to aggregate.
   */
  where?: Prisma.RfqInvitationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RfqInvitations to fetch.
   */
  orderBy?: Prisma.RfqInvitationOrderByWithRelationInput | Prisma.RfqInvitationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RfqInvitationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RfqInvitations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RfqInvitations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RfqInvitations
  **/
  _count?: true | RfqInvitationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RfqInvitationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RfqInvitationMaxAggregateInputType
}

export type GetRfqInvitationAggregateType<T extends RfqInvitationAggregateArgs> = {
      [P in keyof T & keyof AggregateRfqInvitation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRfqInvitation[P]>
    : Prisma.GetScalarType<T[P], AggregateRfqInvitation[P]>
}




export type RfqInvitationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RfqInvitationWhereInput
  orderBy?: Prisma.RfqInvitationOrderByWithAggregationInput | Prisma.RfqInvitationOrderByWithAggregationInput[]
  by: Prisma.RfqInvitationScalarFieldEnum[] | Prisma.RfqInvitationScalarFieldEnum
  having?: Prisma.RfqInvitationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RfqInvitationCountAggregateInputType | true
  _min?: RfqInvitationMinAggregateInputType
  _max?: RfqInvitationMaxAggregateInputType
}

export type RfqInvitationGroupByOutputType = {
  id: string
  rfqId: string
  supplierId: string
  status: string
  sentAt: Date
  viewedAt: Date | null
  declineReason: string | null
  _count: RfqInvitationCountAggregateOutputType | null
  _min: RfqInvitationMinAggregateOutputType | null
  _max: RfqInvitationMaxAggregateOutputType | null
}

export type GetRfqInvitationGroupByPayload<T extends RfqInvitationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RfqInvitationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RfqInvitationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RfqInvitationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RfqInvitationGroupByOutputType[P]>
      }
    >
  >



export type RfqInvitationWhereInput = {
  AND?: Prisma.RfqInvitationWhereInput | Prisma.RfqInvitationWhereInput[]
  OR?: Prisma.RfqInvitationWhereInput[]
  NOT?: Prisma.RfqInvitationWhereInput | Prisma.RfqInvitationWhereInput[]
  id?: Prisma.StringFilter<"RfqInvitation"> | string
  rfqId?: Prisma.StringFilter<"RfqInvitation"> | string
  supplierId?: Prisma.StringFilter<"RfqInvitation"> | string
  status?: Prisma.StringFilter<"RfqInvitation"> | string
  sentAt?: Prisma.DateTimeFilter<"RfqInvitation"> | Date | string
  viewedAt?: Prisma.DateTimeNullableFilter<"RfqInvitation"> | Date | string | null
  declineReason?: Prisma.StringNullableFilter<"RfqInvitation"> | string | null
  rfq?: Prisma.XOR<Prisma.ServiceRequestScalarRelationFilter, Prisma.ServiceRequestWhereInput>
  supplier?: Prisma.XOR<Prisma.SupplierScalarRelationFilter, Prisma.SupplierWhereInput>
}

export type RfqInvitationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  rfqId?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sentAt?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  declineReason?: Prisma.SortOrderInput | Prisma.SortOrder
  rfq?: Prisma.ServiceRequestOrderByWithRelationInput
  supplier?: Prisma.SupplierOrderByWithRelationInput
}

export type RfqInvitationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  rfqId_supplierId?: Prisma.RfqInvitationRfqIdSupplierIdCompoundUniqueInput
  AND?: Prisma.RfqInvitationWhereInput | Prisma.RfqInvitationWhereInput[]
  OR?: Prisma.RfqInvitationWhereInput[]
  NOT?: Prisma.RfqInvitationWhereInput | Prisma.RfqInvitationWhereInput[]
  rfqId?: Prisma.StringFilter<"RfqInvitation"> | string
  supplierId?: Prisma.StringFilter<"RfqInvitation"> | string
  status?: Prisma.StringFilter<"RfqInvitation"> | string
  sentAt?: Prisma.DateTimeFilter<"RfqInvitation"> | Date | string
  viewedAt?: Prisma.DateTimeNullableFilter<"RfqInvitation"> | Date | string | null
  declineReason?: Prisma.StringNullableFilter<"RfqInvitation"> | string | null
  rfq?: Prisma.XOR<Prisma.ServiceRequestScalarRelationFilter, Prisma.ServiceRequestWhereInput>
  supplier?: Prisma.XOR<Prisma.SupplierScalarRelationFilter, Prisma.SupplierWhereInput>
}, "id" | "rfqId_supplierId">

export type RfqInvitationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  rfqId?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sentAt?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  declineReason?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.RfqInvitationCountOrderByAggregateInput
  _max?: Prisma.RfqInvitationMaxOrderByAggregateInput
  _min?: Prisma.RfqInvitationMinOrderByAggregateInput
}

export type RfqInvitationScalarWhereWithAggregatesInput = {
  AND?: Prisma.RfqInvitationScalarWhereWithAggregatesInput | Prisma.RfqInvitationScalarWhereWithAggregatesInput[]
  OR?: Prisma.RfqInvitationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RfqInvitationScalarWhereWithAggregatesInput | Prisma.RfqInvitationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RfqInvitation"> | string
  rfqId?: Prisma.StringWithAggregatesFilter<"RfqInvitation"> | string
  supplierId?: Prisma.StringWithAggregatesFilter<"RfqInvitation"> | string
  status?: Prisma.StringWithAggregatesFilter<"RfqInvitation"> | string
  sentAt?: Prisma.DateTimeWithAggregatesFilter<"RfqInvitation"> | Date | string
  viewedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"RfqInvitation"> | Date | string | null
  declineReason?: Prisma.StringNullableWithAggregatesFilter<"RfqInvitation"> | string | null
}

export type RfqInvitationCreateInput = {
  id?: string
  status?: string
  sentAt?: Date | string
  viewedAt?: Date | string | null
  declineReason?: string | null
  rfq: Prisma.ServiceRequestCreateNestedOneWithoutInvitationsInput
  supplier: Prisma.SupplierCreateNestedOneWithoutRfqInvitationsInput
}

export type RfqInvitationUncheckedCreateInput = {
  id?: string
  rfqId: string
  supplierId: string
  status?: string
  sentAt?: Date | string
  viewedAt?: Date | string | null
  declineReason?: string | null
}

export type RfqInvitationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  declineReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rfq?: Prisma.ServiceRequestUpdateOneRequiredWithoutInvitationsNestedInput
  supplier?: Prisma.SupplierUpdateOneRequiredWithoutRfqInvitationsNestedInput
}

export type RfqInvitationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rfqId?: Prisma.StringFieldUpdateOperationsInput | string
  supplierId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  declineReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RfqInvitationCreateManyInput = {
  id?: string
  rfqId: string
  supplierId: string
  status?: string
  sentAt?: Date | string
  viewedAt?: Date | string | null
  declineReason?: string | null
}

export type RfqInvitationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  declineReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RfqInvitationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rfqId?: Prisma.StringFieldUpdateOperationsInput | string
  supplierId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  declineReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RfqInvitationListRelationFilter = {
  every?: Prisma.RfqInvitationWhereInput
  some?: Prisma.RfqInvitationWhereInput
  none?: Prisma.RfqInvitationWhereInput
}

export type RfqInvitationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RfqInvitationRfqIdSupplierIdCompoundUniqueInput = {
  rfqId: string
  supplierId: string
}

export type RfqInvitationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rfqId?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sentAt?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrder
  declineReason?: Prisma.SortOrder
}

export type RfqInvitationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rfqId?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sentAt?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrder
  declineReason?: Prisma.SortOrder
}

export type RfqInvitationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rfqId?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sentAt?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrder
  declineReason?: Prisma.SortOrder
}

export type RfqInvitationCreateNestedManyWithoutSupplierInput = {
  create?: Prisma.XOR<Prisma.RfqInvitationCreateWithoutSupplierInput, Prisma.RfqInvitationUncheckedCreateWithoutSupplierInput> | Prisma.RfqInvitationCreateWithoutSupplierInput[] | Prisma.RfqInvitationUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.RfqInvitationCreateOrConnectWithoutSupplierInput | Prisma.RfqInvitationCreateOrConnectWithoutSupplierInput[]
  createMany?: Prisma.RfqInvitationCreateManySupplierInputEnvelope
  connect?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
}

export type RfqInvitationUncheckedCreateNestedManyWithoutSupplierInput = {
  create?: Prisma.XOR<Prisma.RfqInvitationCreateWithoutSupplierInput, Prisma.RfqInvitationUncheckedCreateWithoutSupplierInput> | Prisma.RfqInvitationCreateWithoutSupplierInput[] | Prisma.RfqInvitationUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.RfqInvitationCreateOrConnectWithoutSupplierInput | Prisma.RfqInvitationCreateOrConnectWithoutSupplierInput[]
  createMany?: Prisma.RfqInvitationCreateManySupplierInputEnvelope
  connect?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
}

export type RfqInvitationUpdateManyWithoutSupplierNestedInput = {
  create?: Prisma.XOR<Prisma.RfqInvitationCreateWithoutSupplierInput, Prisma.RfqInvitationUncheckedCreateWithoutSupplierInput> | Prisma.RfqInvitationCreateWithoutSupplierInput[] | Prisma.RfqInvitationUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.RfqInvitationCreateOrConnectWithoutSupplierInput | Prisma.RfqInvitationCreateOrConnectWithoutSupplierInput[]
  upsert?: Prisma.RfqInvitationUpsertWithWhereUniqueWithoutSupplierInput | Prisma.RfqInvitationUpsertWithWhereUniqueWithoutSupplierInput[]
  createMany?: Prisma.RfqInvitationCreateManySupplierInputEnvelope
  set?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  disconnect?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  delete?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  connect?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  update?: Prisma.RfqInvitationUpdateWithWhereUniqueWithoutSupplierInput | Prisma.RfqInvitationUpdateWithWhereUniqueWithoutSupplierInput[]
  updateMany?: Prisma.RfqInvitationUpdateManyWithWhereWithoutSupplierInput | Prisma.RfqInvitationUpdateManyWithWhereWithoutSupplierInput[]
  deleteMany?: Prisma.RfqInvitationScalarWhereInput | Prisma.RfqInvitationScalarWhereInput[]
}

export type RfqInvitationUncheckedUpdateManyWithoutSupplierNestedInput = {
  create?: Prisma.XOR<Prisma.RfqInvitationCreateWithoutSupplierInput, Prisma.RfqInvitationUncheckedCreateWithoutSupplierInput> | Prisma.RfqInvitationCreateWithoutSupplierInput[] | Prisma.RfqInvitationUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.RfqInvitationCreateOrConnectWithoutSupplierInput | Prisma.RfqInvitationCreateOrConnectWithoutSupplierInput[]
  upsert?: Prisma.RfqInvitationUpsertWithWhereUniqueWithoutSupplierInput | Prisma.RfqInvitationUpsertWithWhereUniqueWithoutSupplierInput[]
  createMany?: Prisma.RfqInvitationCreateManySupplierInputEnvelope
  set?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  disconnect?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  delete?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  connect?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  update?: Prisma.RfqInvitationUpdateWithWhereUniqueWithoutSupplierInput | Prisma.RfqInvitationUpdateWithWhereUniqueWithoutSupplierInput[]
  updateMany?: Prisma.RfqInvitationUpdateManyWithWhereWithoutSupplierInput | Prisma.RfqInvitationUpdateManyWithWhereWithoutSupplierInput[]
  deleteMany?: Prisma.RfqInvitationScalarWhereInput | Prisma.RfqInvitationScalarWhereInput[]
}

export type RfqInvitationCreateNestedManyWithoutRfqInput = {
  create?: Prisma.XOR<Prisma.RfqInvitationCreateWithoutRfqInput, Prisma.RfqInvitationUncheckedCreateWithoutRfqInput> | Prisma.RfqInvitationCreateWithoutRfqInput[] | Prisma.RfqInvitationUncheckedCreateWithoutRfqInput[]
  connectOrCreate?: Prisma.RfqInvitationCreateOrConnectWithoutRfqInput | Prisma.RfqInvitationCreateOrConnectWithoutRfqInput[]
  createMany?: Prisma.RfqInvitationCreateManyRfqInputEnvelope
  connect?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
}

export type RfqInvitationUncheckedCreateNestedManyWithoutRfqInput = {
  create?: Prisma.XOR<Prisma.RfqInvitationCreateWithoutRfqInput, Prisma.RfqInvitationUncheckedCreateWithoutRfqInput> | Prisma.RfqInvitationCreateWithoutRfqInput[] | Prisma.RfqInvitationUncheckedCreateWithoutRfqInput[]
  connectOrCreate?: Prisma.RfqInvitationCreateOrConnectWithoutRfqInput | Prisma.RfqInvitationCreateOrConnectWithoutRfqInput[]
  createMany?: Prisma.RfqInvitationCreateManyRfqInputEnvelope
  connect?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
}

export type RfqInvitationUpdateManyWithoutRfqNestedInput = {
  create?: Prisma.XOR<Prisma.RfqInvitationCreateWithoutRfqInput, Prisma.RfqInvitationUncheckedCreateWithoutRfqInput> | Prisma.RfqInvitationCreateWithoutRfqInput[] | Prisma.RfqInvitationUncheckedCreateWithoutRfqInput[]
  connectOrCreate?: Prisma.RfqInvitationCreateOrConnectWithoutRfqInput | Prisma.RfqInvitationCreateOrConnectWithoutRfqInput[]
  upsert?: Prisma.RfqInvitationUpsertWithWhereUniqueWithoutRfqInput | Prisma.RfqInvitationUpsertWithWhereUniqueWithoutRfqInput[]
  createMany?: Prisma.RfqInvitationCreateManyRfqInputEnvelope
  set?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  disconnect?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  delete?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  connect?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  update?: Prisma.RfqInvitationUpdateWithWhereUniqueWithoutRfqInput | Prisma.RfqInvitationUpdateWithWhereUniqueWithoutRfqInput[]
  updateMany?: Prisma.RfqInvitationUpdateManyWithWhereWithoutRfqInput | Prisma.RfqInvitationUpdateManyWithWhereWithoutRfqInput[]
  deleteMany?: Prisma.RfqInvitationScalarWhereInput | Prisma.RfqInvitationScalarWhereInput[]
}

export type RfqInvitationUncheckedUpdateManyWithoutRfqNestedInput = {
  create?: Prisma.XOR<Prisma.RfqInvitationCreateWithoutRfqInput, Prisma.RfqInvitationUncheckedCreateWithoutRfqInput> | Prisma.RfqInvitationCreateWithoutRfqInput[] | Prisma.RfqInvitationUncheckedCreateWithoutRfqInput[]
  connectOrCreate?: Prisma.RfqInvitationCreateOrConnectWithoutRfqInput | Prisma.RfqInvitationCreateOrConnectWithoutRfqInput[]
  upsert?: Prisma.RfqInvitationUpsertWithWhereUniqueWithoutRfqInput | Prisma.RfqInvitationUpsertWithWhereUniqueWithoutRfqInput[]
  createMany?: Prisma.RfqInvitationCreateManyRfqInputEnvelope
  set?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  disconnect?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  delete?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  connect?: Prisma.RfqInvitationWhereUniqueInput | Prisma.RfqInvitationWhereUniqueInput[]
  update?: Prisma.RfqInvitationUpdateWithWhereUniqueWithoutRfqInput | Prisma.RfqInvitationUpdateWithWhereUniqueWithoutRfqInput[]
  updateMany?: Prisma.RfqInvitationUpdateManyWithWhereWithoutRfqInput | Prisma.RfqInvitationUpdateManyWithWhereWithoutRfqInput[]
  deleteMany?: Prisma.RfqInvitationScalarWhereInput | Prisma.RfqInvitationScalarWhereInput[]
}

export type RfqInvitationCreateWithoutSupplierInput = {
  id?: string
  status?: string
  sentAt?: Date | string
  viewedAt?: Date | string | null
  declineReason?: string | null
  rfq: Prisma.ServiceRequestCreateNestedOneWithoutInvitationsInput
}

export type RfqInvitationUncheckedCreateWithoutSupplierInput = {
  id?: string
  rfqId: string
  status?: string
  sentAt?: Date | string
  viewedAt?: Date | string | null
  declineReason?: string | null
}

export type RfqInvitationCreateOrConnectWithoutSupplierInput = {
  where: Prisma.RfqInvitationWhereUniqueInput
  create: Prisma.XOR<Prisma.RfqInvitationCreateWithoutSupplierInput, Prisma.RfqInvitationUncheckedCreateWithoutSupplierInput>
}

export type RfqInvitationCreateManySupplierInputEnvelope = {
  data: Prisma.RfqInvitationCreateManySupplierInput | Prisma.RfqInvitationCreateManySupplierInput[]
  skipDuplicates?: boolean
}

export type RfqInvitationUpsertWithWhereUniqueWithoutSupplierInput = {
  where: Prisma.RfqInvitationWhereUniqueInput
  update: Prisma.XOR<Prisma.RfqInvitationUpdateWithoutSupplierInput, Prisma.RfqInvitationUncheckedUpdateWithoutSupplierInput>
  create: Prisma.XOR<Prisma.RfqInvitationCreateWithoutSupplierInput, Prisma.RfqInvitationUncheckedCreateWithoutSupplierInput>
}

export type RfqInvitationUpdateWithWhereUniqueWithoutSupplierInput = {
  where: Prisma.RfqInvitationWhereUniqueInput
  data: Prisma.XOR<Prisma.RfqInvitationUpdateWithoutSupplierInput, Prisma.RfqInvitationUncheckedUpdateWithoutSupplierInput>
}

export type RfqInvitationUpdateManyWithWhereWithoutSupplierInput = {
  where: Prisma.RfqInvitationScalarWhereInput
  data: Prisma.XOR<Prisma.RfqInvitationUpdateManyMutationInput, Prisma.RfqInvitationUncheckedUpdateManyWithoutSupplierInput>
}

export type RfqInvitationScalarWhereInput = {
  AND?: Prisma.RfqInvitationScalarWhereInput | Prisma.RfqInvitationScalarWhereInput[]
  OR?: Prisma.RfqInvitationScalarWhereInput[]
  NOT?: Prisma.RfqInvitationScalarWhereInput | Prisma.RfqInvitationScalarWhereInput[]
  id?: Prisma.StringFilter<"RfqInvitation"> | string
  rfqId?: Prisma.StringFilter<"RfqInvitation"> | string
  supplierId?: Prisma.StringFilter<"RfqInvitation"> | string
  status?: Prisma.StringFilter<"RfqInvitation"> | string
  sentAt?: Prisma.DateTimeFilter<"RfqInvitation"> | Date | string
  viewedAt?: Prisma.DateTimeNullableFilter<"RfqInvitation"> | Date | string | null
  declineReason?: Prisma.StringNullableFilter<"RfqInvitation"> | string | null
}

export type RfqInvitationCreateWithoutRfqInput = {
  id?: string
  status?: string
  sentAt?: Date | string
  viewedAt?: Date | string | null
  declineReason?: string | null
  supplier: Prisma.SupplierCreateNestedOneWithoutRfqInvitationsInput
}

export type RfqInvitationUncheckedCreateWithoutRfqInput = {
  id?: string
  supplierId: string
  status?: string
  sentAt?: Date | string
  viewedAt?: Date | string | null
  declineReason?: string | null
}

export type RfqInvitationCreateOrConnectWithoutRfqInput = {
  where: Prisma.RfqInvitationWhereUniqueInput
  create: Prisma.XOR<Prisma.RfqInvitationCreateWithoutRfqInput, Prisma.RfqInvitationUncheckedCreateWithoutRfqInput>
}

export type RfqInvitationCreateManyRfqInputEnvelope = {
  data: Prisma.RfqInvitationCreateManyRfqInput | Prisma.RfqInvitationCreateManyRfqInput[]
  skipDuplicates?: boolean
}

export type RfqInvitationUpsertWithWhereUniqueWithoutRfqInput = {
  where: Prisma.RfqInvitationWhereUniqueInput
  update: Prisma.XOR<Prisma.RfqInvitationUpdateWithoutRfqInput, Prisma.RfqInvitationUncheckedUpdateWithoutRfqInput>
  create: Prisma.XOR<Prisma.RfqInvitationCreateWithoutRfqInput, Prisma.RfqInvitationUncheckedCreateWithoutRfqInput>
}

export type RfqInvitationUpdateWithWhereUniqueWithoutRfqInput = {
  where: Prisma.RfqInvitationWhereUniqueInput
  data: Prisma.XOR<Prisma.RfqInvitationUpdateWithoutRfqInput, Prisma.RfqInvitationUncheckedUpdateWithoutRfqInput>
}

export type RfqInvitationUpdateManyWithWhereWithoutRfqInput = {
  where: Prisma.RfqInvitationScalarWhereInput
  data: Prisma.XOR<Prisma.RfqInvitationUpdateManyMutationInput, Prisma.RfqInvitationUncheckedUpdateManyWithoutRfqInput>
}

export type RfqInvitationCreateManySupplierInput = {
  id?: string
  rfqId: string
  status?: string
  sentAt?: Date | string
  viewedAt?: Date | string | null
  declineReason?: string | null
}

export type RfqInvitationUpdateWithoutSupplierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  declineReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rfq?: Prisma.ServiceRequestUpdateOneRequiredWithoutInvitationsNestedInput
}

export type RfqInvitationUncheckedUpdateWithoutSupplierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rfqId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  declineReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RfqInvitationUncheckedUpdateManyWithoutSupplierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rfqId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  declineReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RfqInvitationCreateManyRfqInput = {
  id?: string
  supplierId: string
  status?: string
  sentAt?: Date | string
  viewedAt?: Date | string | null
  declineReason?: string | null
}

export type RfqInvitationUpdateWithoutRfqInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  declineReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  supplier?: Prisma.SupplierUpdateOneRequiredWithoutRfqInvitationsNestedInput
}

export type RfqInvitationUncheckedUpdateWithoutRfqInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  supplierId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  declineReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RfqInvitationUncheckedUpdateManyWithoutRfqInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  supplierId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  declineReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type RfqInvitationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rfqId?: boolean
  supplierId?: boolean
  status?: boolean
  sentAt?: boolean
  viewedAt?: boolean
  declineReason?: boolean
  rfq?: boolean | Prisma.ServiceRequestDefaultArgs<ExtArgs>
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rfqInvitation"]>

export type RfqInvitationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rfqId?: boolean
  supplierId?: boolean
  status?: boolean
  sentAt?: boolean
  viewedAt?: boolean
  declineReason?: boolean
  rfq?: boolean | Prisma.ServiceRequestDefaultArgs<ExtArgs>
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rfqInvitation"]>

export type RfqInvitationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rfqId?: boolean
  supplierId?: boolean
  status?: boolean
  sentAt?: boolean
  viewedAt?: boolean
  declineReason?: boolean
  rfq?: boolean | Prisma.ServiceRequestDefaultArgs<ExtArgs>
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rfqInvitation"]>

export type RfqInvitationSelectScalar = {
  id?: boolean
  rfqId?: boolean
  supplierId?: boolean
  status?: boolean
  sentAt?: boolean
  viewedAt?: boolean
  declineReason?: boolean
}

export type RfqInvitationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "rfqId" | "supplierId" | "status" | "sentAt" | "viewedAt" | "declineReason", ExtArgs["result"]["rfqInvitation"]>
export type RfqInvitationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  rfq?: boolean | Prisma.ServiceRequestDefaultArgs<ExtArgs>
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
}
export type RfqInvitationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  rfq?: boolean | Prisma.ServiceRequestDefaultArgs<ExtArgs>
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
}
export type RfqInvitationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  rfq?: boolean | Prisma.ServiceRequestDefaultArgs<ExtArgs>
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
}

export type $RfqInvitationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RfqInvitation"
  objects: {
    rfq: Prisma.$ServiceRequestPayload<ExtArgs>
    supplier: Prisma.$SupplierPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    rfqId: string
    supplierId: string
    status: string
    sentAt: Date
    viewedAt: Date | null
    declineReason: string | null
  }, ExtArgs["result"]["rfqInvitation"]>
  composites: {}
}

export type RfqInvitationGetPayload<S extends boolean | null | undefined | RfqInvitationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RfqInvitationPayload, S>

export type RfqInvitationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RfqInvitationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RfqInvitationCountAggregateInputType | true
  }

export interface RfqInvitationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RfqInvitation'], meta: { name: 'RfqInvitation' } }
  /**
   * Find zero or one RfqInvitation that matches the filter.
   * @param {RfqInvitationFindUniqueArgs} args - Arguments to find a RfqInvitation
   * @example
   * // Get one RfqInvitation
   * const rfqInvitation = await prisma.rfqInvitation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RfqInvitationFindUniqueArgs>(args: Prisma.SelectSubset<T, RfqInvitationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RfqInvitationClient<runtime.Types.Result.GetResult<Prisma.$RfqInvitationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RfqInvitation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RfqInvitationFindUniqueOrThrowArgs} args - Arguments to find a RfqInvitation
   * @example
   * // Get one RfqInvitation
   * const rfqInvitation = await prisma.rfqInvitation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RfqInvitationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RfqInvitationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RfqInvitationClient<runtime.Types.Result.GetResult<Prisma.$RfqInvitationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RfqInvitation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RfqInvitationFindFirstArgs} args - Arguments to find a RfqInvitation
   * @example
   * // Get one RfqInvitation
   * const rfqInvitation = await prisma.rfqInvitation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RfqInvitationFindFirstArgs>(args?: Prisma.SelectSubset<T, RfqInvitationFindFirstArgs<ExtArgs>>): Prisma.Prisma__RfqInvitationClient<runtime.Types.Result.GetResult<Prisma.$RfqInvitationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RfqInvitation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RfqInvitationFindFirstOrThrowArgs} args - Arguments to find a RfqInvitation
   * @example
   * // Get one RfqInvitation
   * const rfqInvitation = await prisma.rfqInvitation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RfqInvitationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RfqInvitationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RfqInvitationClient<runtime.Types.Result.GetResult<Prisma.$RfqInvitationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RfqInvitations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RfqInvitationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RfqInvitations
   * const rfqInvitations = await prisma.rfqInvitation.findMany()
   * 
   * // Get first 10 RfqInvitations
   * const rfqInvitations = await prisma.rfqInvitation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const rfqInvitationWithIdOnly = await prisma.rfqInvitation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RfqInvitationFindManyArgs>(args?: Prisma.SelectSubset<T, RfqInvitationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RfqInvitationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RfqInvitation.
   * @param {RfqInvitationCreateArgs} args - Arguments to create a RfqInvitation.
   * @example
   * // Create one RfqInvitation
   * const RfqInvitation = await prisma.rfqInvitation.create({
   *   data: {
   *     // ... data to create a RfqInvitation
   *   }
   * })
   * 
   */
  create<T extends RfqInvitationCreateArgs>(args: Prisma.SelectSubset<T, RfqInvitationCreateArgs<ExtArgs>>): Prisma.Prisma__RfqInvitationClient<runtime.Types.Result.GetResult<Prisma.$RfqInvitationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RfqInvitations.
   * @param {RfqInvitationCreateManyArgs} args - Arguments to create many RfqInvitations.
   * @example
   * // Create many RfqInvitations
   * const rfqInvitation = await prisma.rfqInvitation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RfqInvitationCreateManyArgs>(args?: Prisma.SelectSubset<T, RfqInvitationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RfqInvitations and returns the data saved in the database.
   * @param {RfqInvitationCreateManyAndReturnArgs} args - Arguments to create many RfqInvitations.
   * @example
   * // Create many RfqInvitations
   * const rfqInvitation = await prisma.rfqInvitation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RfqInvitations and only return the `id`
   * const rfqInvitationWithIdOnly = await prisma.rfqInvitation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RfqInvitationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RfqInvitationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RfqInvitationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RfqInvitation.
   * @param {RfqInvitationDeleteArgs} args - Arguments to delete one RfqInvitation.
   * @example
   * // Delete one RfqInvitation
   * const RfqInvitation = await prisma.rfqInvitation.delete({
   *   where: {
   *     // ... filter to delete one RfqInvitation
   *   }
   * })
   * 
   */
  delete<T extends RfqInvitationDeleteArgs>(args: Prisma.SelectSubset<T, RfqInvitationDeleteArgs<ExtArgs>>): Prisma.Prisma__RfqInvitationClient<runtime.Types.Result.GetResult<Prisma.$RfqInvitationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RfqInvitation.
   * @param {RfqInvitationUpdateArgs} args - Arguments to update one RfqInvitation.
   * @example
   * // Update one RfqInvitation
   * const rfqInvitation = await prisma.rfqInvitation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RfqInvitationUpdateArgs>(args: Prisma.SelectSubset<T, RfqInvitationUpdateArgs<ExtArgs>>): Prisma.Prisma__RfqInvitationClient<runtime.Types.Result.GetResult<Prisma.$RfqInvitationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RfqInvitations.
   * @param {RfqInvitationDeleteManyArgs} args - Arguments to filter RfqInvitations to delete.
   * @example
   * // Delete a few RfqInvitations
   * const { count } = await prisma.rfqInvitation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RfqInvitationDeleteManyArgs>(args?: Prisma.SelectSubset<T, RfqInvitationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RfqInvitations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RfqInvitationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RfqInvitations
   * const rfqInvitation = await prisma.rfqInvitation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RfqInvitationUpdateManyArgs>(args: Prisma.SelectSubset<T, RfqInvitationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RfqInvitations and returns the data updated in the database.
   * @param {RfqInvitationUpdateManyAndReturnArgs} args - Arguments to update many RfqInvitations.
   * @example
   * // Update many RfqInvitations
   * const rfqInvitation = await prisma.rfqInvitation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RfqInvitations and only return the `id`
   * const rfqInvitationWithIdOnly = await prisma.rfqInvitation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RfqInvitationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RfqInvitationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RfqInvitationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RfqInvitation.
   * @param {RfqInvitationUpsertArgs} args - Arguments to update or create a RfqInvitation.
   * @example
   * // Update or create a RfqInvitation
   * const rfqInvitation = await prisma.rfqInvitation.upsert({
   *   create: {
   *     // ... data to create a RfqInvitation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RfqInvitation we want to update
   *   }
   * })
   */
  upsert<T extends RfqInvitationUpsertArgs>(args: Prisma.SelectSubset<T, RfqInvitationUpsertArgs<ExtArgs>>): Prisma.Prisma__RfqInvitationClient<runtime.Types.Result.GetResult<Prisma.$RfqInvitationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RfqInvitations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RfqInvitationCountArgs} args - Arguments to filter RfqInvitations to count.
   * @example
   * // Count the number of RfqInvitations
   * const count = await prisma.rfqInvitation.count({
   *   where: {
   *     // ... the filter for the RfqInvitations we want to count
   *   }
   * })
  **/
  count<T extends RfqInvitationCountArgs>(
    args?: Prisma.Subset<T, RfqInvitationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RfqInvitationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RfqInvitation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RfqInvitationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RfqInvitationAggregateArgs>(args: Prisma.Subset<T, RfqInvitationAggregateArgs>): Prisma.PrismaPromise<GetRfqInvitationAggregateType<T>>

  /**
   * Group by RfqInvitation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RfqInvitationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RfqInvitationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RfqInvitationGroupByArgs['orderBy'] }
      : { orderBy?: RfqInvitationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RfqInvitationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRfqInvitationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RfqInvitation model
 */
readonly fields: RfqInvitationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RfqInvitation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RfqInvitationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  rfq<T extends Prisma.ServiceRequestDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceRequestDefaultArgs<ExtArgs>>): Prisma.Prisma__ServiceRequestClient<runtime.Types.Result.GetResult<Prisma.$ServiceRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  supplier<T extends Prisma.SupplierDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SupplierDefaultArgs<ExtArgs>>): Prisma.Prisma__SupplierClient<runtime.Types.Result.GetResult<Prisma.$SupplierPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RfqInvitation model
 */
export interface RfqInvitationFieldRefs {
  readonly id: Prisma.FieldRef<"RfqInvitation", 'String'>
  readonly rfqId: Prisma.FieldRef<"RfqInvitation", 'String'>
  readonly supplierId: Prisma.FieldRef<"RfqInvitation", 'String'>
  readonly status: Prisma.FieldRef<"RfqInvitation", 'String'>
  readonly sentAt: Prisma.FieldRef<"RfqInvitation", 'DateTime'>
  readonly viewedAt: Prisma.FieldRef<"RfqInvitation", 'DateTime'>
  readonly declineReason: Prisma.FieldRef<"RfqInvitation", 'String'>
}
    

// Custom InputTypes
/**
 * RfqInvitation findUnique
 */
export type RfqInvitationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RfqInvitation
   */
  select?: Prisma.RfqInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RfqInvitation
   */
  omit?: Prisma.RfqInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RfqInvitationInclude<ExtArgs> | null
  /**
   * Filter, which RfqInvitation to fetch.
   */
  where: Prisma.RfqInvitationWhereUniqueInput
}

/**
 * RfqInvitation findUniqueOrThrow
 */
export type RfqInvitationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RfqInvitation
   */
  select?: Prisma.RfqInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RfqInvitation
   */
  omit?: Prisma.RfqInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RfqInvitationInclude<ExtArgs> | null
  /**
   * Filter, which RfqInvitation to fetch.
   */
  where: Prisma.RfqInvitationWhereUniqueInput
}

/**
 * RfqInvitation findFirst
 */
export type RfqInvitationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RfqInvitation
   */
  select?: Prisma.RfqInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RfqInvitation
   */
  omit?: Prisma.RfqInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RfqInvitationInclude<ExtArgs> | null
  /**
   * Filter, which RfqInvitation to fetch.
   */
  where?: Prisma.RfqInvitationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RfqInvitations to fetch.
   */
  orderBy?: Prisma.RfqInvitationOrderByWithRelationInput | Prisma.RfqInvitationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RfqInvitations.
   */
  cursor?: Prisma.RfqInvitationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RfqInvitations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RfqInvitations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RfqInvitations.
   */
  distinct?: Prisma.RfqInvitationScalarFieldEnum | Prisma.RfqInvitationScalarFieldEnum[]
}

/**
 * RfqInvitation findFirstOrThrow
 */
export type RfqInvitationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RfqInvitation
   */
  select?: Prisma.RfqInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RfqInvitation
   */
  omit?: Prisma.RfqInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RfqInvitationInclude<ExtArgs> | null
  /**
   * Filter, which RfqInvitation to fetch.
   */
  where?: Prisma.RfqInvitationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RfqInvitations to fetch.
   */
  orderBy?: Prisma.RfqInvitationOrderByWithRelationInput | Prisma.RfqInvitationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RfqInvitations.
   */
  cursor?: Prisma.RfqInvitationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RfqInvitations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RfqInvitations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RfqInvitations.
   */
  distinct?: Prisma.RfqInvitationScalarFieldEnum | Prisma.RfqInvitationScalarFieldEnum[]
}

/**
 * RfqInvitation findMany
 */
export type RfqInvitationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RfqInvitation
   */
  select?: Prisma.RfqInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RfqInvitation
   */
  omit?: Prisma.RfqInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RfqInvitationInclude<ExtArgs> | null
  /**
   * Filter, which RfqInvitations to fetch.
   */
  where?: Prisma.RfqInvitationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RfqInvitations to fetch.
   */
  orderBy?: Prisma.RfqInvitationOrderByWithRelationInput | Prisma.RfqInvitationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RfqInvitations.
   */
  cursor?: Prisma.RfqInvitationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RfqInvitations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RfqInvitations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RfqInvitations.
   */
  distinct?: Prisma.RfqInvitationScalarFieldEnum | Prisma.RfqInvitationScalarFieldEnum[]
}

/**
 * RfqInvitation create
 */
export type RfqInvitationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RfqInvitation
   */
  select?: Prisma.RfqInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RfqInvitation
   */
  omit?: Prisma.RfqInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RfqInvitationInclude<ExtArgs> | null
  /**
   * The data needed to create a RfqInvitation.
   */
  data: Prisma.XOR<Prisma.RfqInvitationCreateInput, Prisma.RfqInvitationUncheckedCreateInput>
}

/**
 * RfqInvitation createMany
 */
export type RfqInvitationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RfqInvitations.
   */
  data: Prisma.RfqInvitationCreateManyInput | Prisma.RfqInvitationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RfqInvitation createManyAndReturn
 */
export type RfqInvitationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RfqInvitation
   */
  select?: Prisma.RfqInvitationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RfqInvitation
   */
  omit?: Prisma.RfqInvitationOmit<ExtArgs> | null
  /**
   * The data used to create many RfqInvitations.
   */
  data: Prisma.RfqInvitationCreateManyInput | Prisma.RfqInvitationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RfqInvitationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RfqInvitation update
 */
export type RfqInvitationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RfqInvitation
   */
  select?: Prisma.RfqInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RfqInvitation
   */
  omit?: Prisma.RfqInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RfqInvitationInclude<ExtArgs> | null
  /**
   * The data needed to update a RfqInvitation.
   */
  data: Prisma.XOR<Prisma.RfqInvitationUpdateInput, Prisma.RfqInvitationUncheckedUpdateInput>
  /**
   * Choose, which RfqInvitation to update.
   */
  where: Prisma.RfqInvitationWhereUniqueInput
}

/**
 * RfqInvitation updateMany
 */
export type RfqInvitationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RfqInvitations.
   */
  data: Prisma.XOR<Prisma.RfqInvitationUpdateManyMutationInput, Prisma.RfqInvitationUncheckedUpdateManyInput>
  /**
   * Filter which RfqInvitations to update
   */
  where?: Prisma.RfqInvitationWhereInput
  /**
   * Limit how many RfqInvitations to update.
   */
  limit?: number
}

/**
 * RfqInvitation updateManyAndReturn
 */
export type RfqInvitationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RfqInvitation
   */
  select?: Prisma.RfqInvitationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RfqInvitation
   */
  omit?: Prisma.RfqInvitationOmit<ExtArgs> | null
  /**
   * The data used to update RfqInvitations.
   */
  data: Prisma.XOR<Prisma.RfqInvitationUpdateManyMutationInput, Prisma.RfqInvitationUncheckedUpdateManyInput>
  /**
   * Filter which RfqInvitations to update
   */
  where?: Prisma.RfqInvitationWhereInput
  /**
   * Limit how many RfqInvitations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RfqInvitationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RfqInvitation upsert
 */
export type RfqInvitationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RfqInvitation
   */
  select?: Prisma.RfqInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RfqInvitation
   */
  omit?: Prisma.RfqInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RfqInvitationInclude<ExtArgs> | null
  /**
   * The filter to search for the RfqInvitation to update in case it exists.
   */
  where: Prisma.RfqInvitationWhereUniqueInput
  /**
   * In case the RfqInvitation found by the `where` argument doesn't exist, create a new RfqInvitation with this data.
   */
  create: Prisma.XOR<Prisma.RfqInvitationCreateInput, Prisma.RfqInvitationUncheckedCreateInput>
  /**
   * In case the RfqInvitation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RfqInvitationUpdateInput, Prisma.RfqInvitationUncheckedUpdateInput>
}

/**
 * RfqInvitation delete
 */
export type RfqInvitationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RfqInvitation
   */
  select?: Prisma.RfqInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RfqInvitation
   */
  omit?: Prisma.RfqInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RfqInvitationInclude<ExtArgs> | null
  /**
   * Filter which RfqInvitation to delete.
   */
  where: Prisma.RfqInvitationWhereUniqueInput
}

/**
 * RfqInvitation deleteMany
 */
export type RfqInvitationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RfqInvitations to delete
   */
  where?: Prisma.RfqInvitationWhereInput
  /**
   * Limit how many RfqInvitations to delete.
   */
  limit?: number
}

/**
 * RfqInvitation without action
 */
export type RfqInvitationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RfqInvitation
   */
  select?: Prisma.RfqInvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RfqInvitation
   */
  omit?: Prisma.RfqInvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RfqInvitationInclude<ExtArgs> | null
}
