
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Unit` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Unit
 * 
 */
export type UnitModel = runtime.Types.Result.DefaultSelection<Prisma.$UnitPayload>

export type AggregateUnit = {
  _count: UnitCountAggregateOutputType | null
  _avg: UnitAvgAggregateOutputType | null
  _sum: UnitSumAggregateOutputType | null
  _min: UnitMinAggregateOutputType | null
  _max: UnitMaxAggregateOutputType | null
}

export type UnitAvgAggregateOutputType = {
  floor: number | null
  areaSqm: number | null
  millesimes: number | null
}

export type UnitSumAggregateOutputType = {
  floor: number | null
  areaSqm: number | null
  millesimes: number | null
}

export type UnitMinAggregateOutputType = {
  id: string | null
  buildingId: string | null
  unitNumber: string | null
  unitType: $Enums.UnitType | null
  floor: number | null
  areaSqm: number | null
  millesimes: number | null
  ownerId: string | null
  residentId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UnitMaxAggregateOutputType = {
  id: string | null
  buildingId: string | null
  unitNumber: string | null
  unitType: $Enums.UnitType | null
  floor: number | null
  areaSqm: number | null
  millesimes: number | null
  ownerId: string | null
  residentId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UnitCountAggregateOutputType = {
  id: number
  buildingId: number
  unitNumber: number
  unitType: number
  floor: number
  areaSqm: number
  millesimes: number
  ownerId: number
  residentId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type UnitAvgAggregateInputType = {
  floor?: true
  areaSqm?: true
  millesimes?: true
}

export type UnitSumAggregateInputType = {
  floor?: true
  areaSqm?: true
  millesimes?: true
}

export type UnitMinAggregateInputType = {
  id?: true
  buildingId?: true
  unitNumber?: true
  unitType?: true
  floor?: true
  areaSqm?: true
  millesimes?: true
  ownerId?: true
  residentId?: true
  createdAt?: true
  updatedAt?: true
}

export type UnitMaxAggregateInputType = {
  id?: true
  buildingId?: true
  unitNumber?: true
  unitType?: true
  floor?: true
  areaSqm?: true
  millesimes?: true
  ownerId?: true
  residentId?: true
  createdAt?: true
  updatedAt?: true
}

export type UnitCountAggregateInputType = {
  id?: true
  buildingId?: true
  unitNumber?: true
  unitType?: true
  floor?: true
  areaSqm?: true
  millesimes?: true
  ownerId?: true
  residentId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type UnitAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Unit to aggregate.
   */
  where?: Prisma.UnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Units to fetch.
   */
  orderBy?: Prisma.UnitOrderByWithRelationInput | Prisma.UnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Units from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Units.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Units
  **/
  _count?: true | UnitCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UnitAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UnitSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UnitMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UnitMaxAggregateInputType
}

export type GetUnitAggregateType<T extends UnitAggregateArgs> = {
      [P in keyof T & keyof AggregateUnit]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUnit[P]>
    : Prisma.GetScalarType<T[P], AggregateUnit[P]>
}




export type UnitGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UnitWhereInput
  orderBy?: Prisma.UnitOrderByWithAggregationInput | Prisma.UnitOrderByWithAggregationInput[]
  by: Prisma.UnitScalarFieldEnum[] | Prisma.UnitScalarFieldEnum
  having?: Prisma.UnitScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UnitCountAggregateInputType | true
  _avg?: UnitAvgAggregateInputType
  _sum?: UnitSumAggregateInputType
  _min?: UnitMinAggregateInputType
  _max?: UnitMaxAggregateInputType
}

export type UnitGroupByOutputType = {
  id: string
  buildingId: string
  unitNumber: string
  unitType: $Enums.UnitType
  floor: number | null
  areaSqm: number | null
  millesimes: number | null
  ownerId: string | null
  residentId: string | null
  createdAt: Date
  updatedAt: Date
  _count: UnitCountAggregateOutputType | null
  _avg: UnitAvgAggregateOutputType | null
  _sum: UnitSumAggregateOutputType | null
  _min: UnitMinAggregateOutputType | null
  _max: UnitMaxAggregateOutputType | null
}

export type GetUnitGroupByPayload<T extends UnitGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UnitGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UnitGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UnitGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UnitGroupByOutputType[P]>
      }
    >
  >



export type UnitWhereInput = {
  AND?: Prisma.UnitWhereInput | Prisma.UnitWhereInput[]
  OR?: Prisma.UnitWhereInput[]
  NOT?: Prisma.UnitWhereInput | Prisma.UnitWhereInput[]
  id?: Prisma.StringFilter<"Unit"> | string
  buildingId?: Prisma.StringFilter<"Unit"> | string
  unitNumber?: Prisma.StringFilter<"Unit"> | string
  unitType?: Prisma.EnumUnitTypeFilter<"Unit"> | $Enums.UnitType
  floor?: Prisma.IntNullableFilter<"Unit"> | number | null
  areaSqm?: Prisma.FloatNullableFilter<"Unit"> | number | null
  millesimes?: Prisma.FloatNullableFilter<"Unit"> | number | null
  ownerId?: Prisma.StringNullableFilter<"Unit"> | string | null
  residentId?: Prisma.StringNullableFilter<"Unit"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Unit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Unit"> | Date | string
  building?: Prisma.XOR<Prisma.BuildingScalarRelationFilter, Prisma.BuildingWhereInput>
  owner?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  resident?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  maintenanceRequests?: Prisma.MaintenanceRequestListRelationFilter
  payments?: Prisma.UnitPaymentListRelationFilter
  occupancies?: Prisma.UnitOccupancyListRelationFilter
}

export type UnitOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  unitNumber?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  floor?: Prisma.SortOrderInput | Prisma.SortOrder
  areaSqm?: Prisma.SortOrderInput | Prisma.SortOrder
  millesimes?: Prisma.SortOrderInput | Prisma.SortOrder
  ownerId?: Prisma.SortOrderInput | Prisma.SortOrder
  residentId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  building?: Prisma.BuildingOrderByWithRelationInput
  owner?: Prisma.UserOrderByWithRelationInput
  resident?: Prisma.UserOrderByWithRelationInput
  maintenanceRequests?: Prisma.MaintenanceRequestOrderByRelationAggregateInput
  payments?: Prisma.UnitPaymentOrderByRelationAggregateInput
  occupancies?: Prisma.UnitOccupancyOrderByRelationAggregateInput
}

export type UnitWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  buildingId_unitNumber?: Prisma.UnitBuildingIdUnitNumberCompoundUniqueInput
  AND?: Prisma.UnitWhereInput | Prisma.UnitWhereInput[]
  OR?: Prisma.UnitWhereInput[]
  NOT?: Prisma.UnitWhereInput | Prisma.UnitWhereInput[]
  buildingId?: Prisma.StringFilter<"Unit"> | string
  unitNumber?: Prisma.StringFilter<"Unit"> | string
  unitType?: Prisma.EnumUnitTypeFilter<"Unit"> | $Enums.UnitType
  floor?: Prisma.IntNullableFilter<"Unit"> | number | null
  areaSqm?: Prisma.FloatNullableFilter<"Unit"> | number | null
  millesimes?: Prisma.FloatNullableFilter<"Unit"> | number | null
  ownerId?: Prisma.StringNullableFilter<"Unit"> | string | null
  residentId?: Prisma.StringNullableFilter<"Unit"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Unit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Unit"> | Date | string
  building?: Prisma.XOR<Prisma.BuildingScalarRelationFilter, Prisma.BuildingWhereInput>
  owner?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  resident?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  maintenanceRequests?: Prisma.MaintenanceRequestListRelationFilter
  payments?: Prisma.UnitPaymentListRelationFilter
  occupancies?: Prisma.UnitOccupancyListRelationFilter
}, "id" | "buildingId_unitNumber">

export type UnitOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  unitNumber?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  floor?: Prisma.SortOrderInput | Prisma.SortOrder
  areaSqm?: Prisma.SortOrderInput | Prisma.SortOrder
  millesimes?: Prisma.SortOrderInput | Prisma.SortOrder
  ownerId?: Prisma.SortOrderInput | Prisma.SortOrder
  residentId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UnitCountOrderByAggregateInput
  _avg?: Prisma.UnitAvgOrderByAggregateInput
  _max?: Prisma.UnitMaxOrderByAggregateInput
  _min?: Prisma.UnitMinOrderByAggregateInput
  _sum?: Prisma.UnitSumOrderByAggregateInput
}

export type UnitScalarWhereWithAggregatesInput = {
  AND?: Prisma.UnitScalarWhereWithAggregatesInput | Prisma.UnitScalarWhereWithAggregatesInput[]
  OR?: Prisma.UnitScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UnitScalarWhereWithAggregatesInput | Prisma.UnitScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Unit"> | string
  buildingId?: Prisma.StringWithAggregatesFilter<"Unit"> | string
  unitNumber?: Prisma.StringWithAggregatesFilter<"Unit"> | string
  unitType?: Prisma.EnumUnitTypeWithAggregatesFilter<"Unit"> | $Enums.UnitType
  floor?: Prisma.IntNullableWithAggregatesFilter<"Unit"> | number | null
  areaSqm?: Prisma.FloatNullableWithAggregatesFilter<"Unit"> | number | null
  millesimes?: Prisma.FloatNullableWithAggregatesFilter<"Unit"> | number | null
  ownerId?: Prisma.StringNullableWithAggregatesFilter<"Unit"> | string | null
  residentId?: Prisma.StringNullableWithAggregatesFilter<"Unit"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Unit"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Unit"> | Date | string
}

export type UnitCreateInput = {
  id?: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  building: Prisma.BuildingCreateNestedOneWithoutUnitsInput
  owner?: Prisma.UserCreateNestedOneWithoutOwnedUnitsInput
  resident?: Prisma.UserCreateNestedOneWithoutResidentUnitsInput
  maintenanceRequests?: Prisma.MaintenanceRequestCreateNestedManyWithoutUnitInput
  payments?: Prisma.UnitPaymentCreateNestedManyWithoutUnitInput
  occupancies?: Prisma.UnitOccupancyCreateNestedManyWithoutUnitInput
}

export type UnitUncheckedCreateInput = {
  id?: string
  buildingId: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  ownerId?: string | null
  residentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  maintenanceRequests?: Prisma.MaintenanceRequestUncheckedCreateNestedManyWithoutUnitInput
  payments?: Prisma.UnitPaymentUncheckedCreateNestedManyWithoutUnitInput
  occupancies?: Prisma.UnitOccupancyUncheckedCreateNestedManyWithoutUnitInput
}

export type UnitUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  building?: Prisma.BuildingUpdateOneRequiredWithoutUnitsNestedInput
  owner?: Prisma.UserUpdateOneWithoutOwnedUnitsNestedInput
  resident?: Prisma.UserUpdateOneWithoutResidentUnitsNestedInput
  maintenanceRequests?: Prisma.MaintenanceRequestUpdateManyWithoutUnitNestedInput
  payments?: Prisma.UnitPaymentUpdateManyWithoutUnitNestedInput
  occupancies?: Prisma.UnitOccupancyUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  residentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maintenanceRequests?: Prisma.MaintenanceRequestUncheckedUpdateManyWithoutUnitNestedInput
  payments?: Prisma.UnitPaymentUncheckedUpdateManyWithoutUnitNestedInput
  occupancies?: Prisma.UnitOccupancyUncheckedUpdateManyWithoutUnitNestedInput
}

export type UnitCreateManyInput = {
  id?: string
  buildingId: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  ownerId?: string | null
  residentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UnitUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UnitUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  residentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UnitListRelationFilter = {
  every?: Prisma.UnitWhereInput
  some?: Prisma.UnitWhereInput
  none?: Prisma.UnitWhereInput
}

export type UnitOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UnitScalarRelationFilter = {
  is?: Prisma.UnitWhereInput
  isNot?: Prisma.UnitWhereInput
}

export type UnitBuildingIdUnitNumberCompoundUniqueInput = {
  buildingId: string
  unitNumber: string
}

export type UnitCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  unitNumber?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  floor?: Prisma.SortOrder
  areaSqm?: Prisma.SortOrder
  millesimes?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  residentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UnitAvgOrderByAggregateInput = {
  floor?: Prisma.SortOrder
  areaSqm?: Prisma.SortOrder
  millesimes?: Prisma.SortOrder
}

export type UnitMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  unitNumber?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  floor?: Prisma.SortOrder
  areaSqm?: Prisma.SortOrder
  millesimes?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  residentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UnitMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  unitNumber?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  floor?: Prisma.SortOrder
  areaSqm?: Prisma.SortOrder
  millesimes?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  residentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UnitSumOrderByAggregateInput = {
  floor?: Prisma.SortOrder
  areaSqm?: Prisma.SortOrder
  millesimes?: Prisma.SortOrder
}

export type UnitNullableScalarRelationFilter = {
  is?: Prisma.UnitWhereInput | null
  isNot?: Prisma.UnitWhereInput | null
}

export type UnitCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutOwnerInput, Prisma.UnitUncheckedCreateWithoutOwnerInput> | Prisma.UnitCreateWithoutOwnerInput[] | Prisma.UnitUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutOwnerInput | Prisma.UnitCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.UnitCreateManyOwnerInputEnvelope
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
}

export type UnitCreateNestedManyWithoutResidentInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutResidentInput, Prisma.UnitUncheckedCreateWithoutResidentInput> | Prisma.UnitCreateWithoutResidentInput[] | Prisma.UnitUncheckedCreateWithoutResidentInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutResidentInput | Prisma.UnitCreateOrConnectWithoutResidentInput[]
  createMany?: Prisma.UnitCreateManyResidentInputEnvelope
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
}

export type UnitUncheckedCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutOwnerInput, Prisma.UnitUncheckedCreateWithoutOwnerInput> | Prisma.UnitCreateWithoutOwnerInput[] | Prisma.UnitUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutOwnerInput | Prisma.UnitCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.UnitCreateManyOwnerInputEnvelope
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
}

export type UnitUncheckedCreateNestedManyWithoutResidentInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutResidentInput, Prisma.UnitUncheckedCreateWithoutResidentInput> | Prisma.UnitCreateWithoutResidentInput[] | Prisma.UnitUncheckedCreateWithoutResidentInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutResidentInput | Prisma.UnitCreateOrConnectWithoutResidentInput[]
  createMany?: Prisma.UnitCreateManyResidentInputEnvelope
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
}

export type UnitUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutOwnerInput, Prisma.UnitUncheckedCreateWithoutOwnerInput> | Prisma.UnitCreateWithoutOwnerInput[] | Prisma.UnitUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutOwnerInput | Prisma.UnitCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.UnitUpsertWithWhereUniqueWithoutOwnerInput | Prisma.UnitUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.UnitCreateManyOwnerInputEnvelope
  set?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  disconnect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  delete?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  update?: Prisma.UnitUpdateWithWhereUniqueWithoutOwnerInput | Prisma.UnitUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.UnitUpdateManyWithWhereWithoutOwnerInput | Prisma.UnitUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.UnitScalarWhereInput | Prisma.UnitScalarWhereInput[]
}

export type UnitUpdateManyWithoutResidentNestedInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutResidentInput, Prisma.UnitUncheckedCreateWithoutResidentInput> | Prisma.UnitCreateWithoutResidentInput[] | Prisma.UnitUncheckedCreateWithoutResidentInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutResidentInput | Prisma.UnitCreateOrConnectWithoutResidentInput[]
  upsert?: Prisma.UnitUpsertWithWhereUniqueWithoutResidentInput | Prisma.UnitUpsertWithWhereUniqueWithoutResidentInput[]
  createMany?: Prisma.UnitCreateManyResidentInputEnvelope
  set?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  disconnect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  delete?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  update?: Prisma.UnitUpdateWithWhereUniqueWithoutResidentInput | Prisma.UnitUpdateWithWhereUniqueWithoutResidentInput[]
  updateMany?: Prisma.UnitUpdateManyWithWhereWithoutResidentInput | Prisma.UnitUpdateManyWithWhereWithoutResidentInput[]
  deleteMany?: Prisma.UnitScalarWhereInput | Prisma.UnitScalarWhereInput[]
}

export type UnitUncheckedUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutOwnerInput, Prisma.UnitUncheckedCreateWithoutOwnerInput> | Prisma.UnitCreateWithoutOwnerInput[] | Prisma.UnitUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutOwnerInput | Prisma.UnitCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.UnitUpsertWithWhereUniqueWithoutOwnerInput | Prisma.UnitUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.UnitCreateManyOwnerInputEnvelope
  set?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  disconnect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  delete?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  update?: Prisma.UnitUpdateWithWhereUniqueWithoutOwnerInput | Prisma.UnitUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.UnitUpdateManyWithWhereWithoutOwnerInput | Prisma.UnitUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.UnitScalarWhereInput | Prisma.UnitScalarWhereInput[]
}

export type UnitUncheckedUpdateManyWithoutResidentNestedInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutResidentInput, Prisma.UnitUncheckedCreateWithoutResidentInput> | Prisma.UnitCreateWithoutResidentInput[] | Prisma.UnitUncheckedCreateWithoutResidentInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutResidentInput | Prisma.UnitCreateOrConnectWithoutResidentInput[]
  upsert?: Prisma.UnitUpsertWithWhereUniqueWithoutResidentInput | Prisma.UnitUpsertWithWhereUniqueWithoutResidentInput[]
  createMany?: Prisma.UnitCreateManyResidentInputEnvelope
  set?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  disconnect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  delete?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  update?: Prisma.UnitUpdateWithWhereUniqueWithoutResidentInput | Prisma.UnitUpdateWithWhereUniqueWithoutResidentInput[]
  updateMany?: Prisma.UnitUpdateManyWithWhereWithoutResidentInput | Prisma.UnitUpdateManyWithWhereWithoutResidentInput[]
  deleteMany?: Prisma.UnitScalarWhereInput | Prisma.UnitScalarWhereInput[]
}

export type UnitCreateNestedManyWithoutBuildingInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutBuildingInput, Prisma.UnitUncheckedCreateWithoutBuildingInput> | Prisma.UnitCreateWithoutBuildingInput[] | Prisma.UnitUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutBuildingInput | Prisma.UnitCreateOrConnectWithoutBuildingInput[]
  createMany?: Prisma.UnitCreateManyBuildingInputEnvelope
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
}

export type UnitUncheckedCreateNestedManyWithoutBuildingInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutBuildingInput, Prisma.UnitUncheckedCreateWithoutBuildingInput> | Prisma.UnitCreateWithoutBuildingInput[] | Prisma.UnitUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutBuildingInput | Prisma.UnitCreateOrConnectWithoutBuildingInput[]
  createMany?: Prisma.UnitCreateManyBuildingInputEnvelope
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
}

export type UnitUpdateManyWithoutBuildingNestedInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutBuildingInput, Prisma.UnitUncheckedCreateWithoutBuildingInput> | Prisma.UnitCreateWithoutBuildingInput[] | Prisma.UnitUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutBuildingInput | Prisma.UnitCreateOrConnectWithoutBuildingInput[]
  upsert?: Prisma.UnitUpsertWithWhereUniqueWithoutBuildingInput | Prisma.UnitUpsertWithWhereUniqueWithoutBuildingInput[]
  createMany?: Prisma.UnitCreateManyBuildingInputEnvelope
  set?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  disconnect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  delete?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  update?: Prisma.UnitUpdateWithWhereUniqueWithoutBuildingInput | Prisma.UnitUpdateWithWhereUniqueWithoutBuildingInput[]
  updateMany?: Prisma.UnitUpdateManyWithWhereWithoutBuildingInput | Prisma.UnitUpdateManyWithWhereWithoutBuildingInput[]
  deleteMany?: Prisma.UnitScalarWhereInput | Prisma.UnitScalarWhereInput[]
}

export type UnitUncheckedUpdateManyWithoutBuildingNestedInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutBuildingInput, Prisma.UnitUncheckedCreateWithoutBuildingInput> | Prisma.UnitCreateWithoutBuildingInput[] | Prisma.UnitUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutBuildingInput | Prisma.UnitCreateOrConnectWithoutBuildingInput[]
  upsert?: Prisma.UnitUpsertWithWhereUniqueWithoutBuildingInput | Prisma.UnitUpsertWithWhereUniqueWithoutBuildingInput[]
  createMany?: Prisma.UnitCreateManyBuildingInputEnvelope
  set?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  disconnect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  delete?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  connect?: Prisma.UnitWhereUniqueInput | Prisma.UnitWhereUniqueInput[]
  update?: Prisma.UnitUpdateWithWhereUniqueWithoutBuildingInput | Prisma.UnitUpdateWithWhereUniqueWithoutBuildingInput[]
  updateMany?: Prisma.UnitUpdateManyWithWhereWithoutBuildingInput | Prisma.UnitUpdateManyWithWhereWithoutBuildingInput[]
  deleteMany?: Prisma.UnitScalarWhereInput | Prisma.UnitScalarWhereInput[]
}

export type UnitCreateNestedOneWithoutOccupanciesInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutOccupanciesInput, Prisma.UnitUncheckedCreateWithoutOccupanciesInput>
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutOccupanciesInput
  connect?: Prisma.UnitWhereUniqueInput
}

export type UnitUpdateOneRequiredWithoutOccupanciesNestedInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutOccupanciesInput, Prisma.UnitUncheckedCreateWithoutOccupanciesInput>
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutOccupanciesInput
  upsert?: Prisma.UnitUpsertWithoutOccupanciesInput
  connect?: Prisma.UnitWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UnitUpdateToOneWithWhereWithoutOccupanciesInput, Prisma.UnitUpdateWithoutOccupanciesInput>, Prisma.UnitUncheckedUpdateWithoutOccupanciesInput>
}

export type UnitCreateNestedOneWithoutPaymentsInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutPaymentsInput, Prisma.UnitUncheckedCreateWithoutPaymentsInput>
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutPaymentsInput
  connect?: Prisma.UnitWhereUniqueInput
}

export type UnitUpdateOneRequiredWithoutPaymentsNestedInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutPaymentsInput, Prisma.UnitUncheckedCreateWithoutPaymentsInput>
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutPaymentsInput
  upsert?: Prisma.UnitUpsertWithoutPaymentsInput
  connect?: Prisma.UnitWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UnitUpdateToOneWithWhereWithoutPaymentsInput, Prisma.UnitUpdateWithoutPaymentsInput>, Prisma.UnitUncheckedUpdateWithoutPaymentsInput>
}

export type EnumUnitTypeFieldUpdateOperationsInput = {
  set?: $Enums.UnitType
}

export type UnitCreateNestedOneWithoutMaintenanceRequestsInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutMaintenanceRequestsInput, Prisma.UnitUncheckedCreateWithoutMaintenanceRequestsInput>
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutMaintenanceRequestsInput
  connect?: Prisma.UnitWhereUniqueInput
}

export type UnitUpdateOneWithoutMaintenanceRequestsNestedInput = {
  create?: Prisma.XOR<Prisma.UnitCreateWithoutMaintenanceRequestsInput, Prisma.UnitUncheckedCreateWithoutMaintenanceRequestsInput>
  connectOrCreate?: Prisma.UnitCreateOrConnectWithoutMaintenanceRequestsInput
  upsert?: Prisma.UnitUpsertWithoutMaintenanceRequestsInput
  disconnect?: Prisma.UnitWhereInput | boolean
  delete?: Prisma.UnitWhereInput | boolean
  connect?: Prisma.UnitWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UnitUpdateToOneWithWhereWithoutMaintenanceRequestsInput, Prisma.UnitUpdateWithoutMaintenanceRequestsInput>, Prisma.UnitUncheckedUpdateWithoutMaintenanceRequestsInput>
}

export type UnitCreateWithoutOwnerInput = {
  id?: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  building: Prisma.BuildingCreateNestedOneWithoutUnitsInput
  resident?: Prisma.UserCreateNestedOneWithoutResidentUnitsInput
  maintenanceRequests?: Prisma.MaintenanceRequestCreateNestedManyWithoutUnitInput
  payments?: Prisma.UnitPaymentCreateNestedManyWithoutUnitInput
  occupancies?: Prisma.UnitOccupancyCreateNestedManyWithoutUnitInput
}

export type UnitUncheckedCreateWithoutOwnerInput = {
  id?: string
  buildingId: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  residentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  maintenanceRequests?: Prisma.MaintenanceRequestUncheckedCreateNestedManyWithoutUnitInput
  payments?: Prisma.UnitPaymentUncheckedCreateNestedManyWithoutUnitInput
  occupancies?: Prisma.UnitOccupancyUncheckedCreateNestedManyWithoutUnitInput
}

export type UnitCreateOrConnectWithoutOwnerInput = {
  where: Prisma.UnitWhereUniqueInput
  create: Prisma.XOR<Prisma.UnitCreateWithoutOwnerInput, Prisma.UnitUncheckedCreateWithoutOwnerInput>
}

export type UnitCreateManyOwnerInputEnvelope = {
  data: Prisma.UnitCreateManyOwnerInput | Prisma.UnitCreateManyOwnerInput[]
  skipDuplicates?: boolean
}

export type UnitCreateWithoutResidentInput = {
  id?: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  building: Prisma.BuildingCreateNestedOneWithoutUnitsInput
  owner?: Prisma.UserCreateNestedOneWithoutOwnedUnitsInput
  maintenanceRequests?: Prisma.MaintenanceRequestCreateNestedManyWithoutUnitInput
  payments?: Prisma.UnitPaymentCreateNestedManyWithoutUnitInput
  occupancies?: Prisma.UnitOccupancyCreateNestedManyWithoutUnitInput
}

export type UnitUncheckedCreateWithoutResidentInput = {
  id?: string
  buildingId: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  ownerId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  maintenanceRequests?: Prisma.MaintenanceRequestUncheckedCreateNestedManyWithoutUnitInput
  payments?: Prisma.UnitPaymentUncheckedCreateNestedManyWithoutUnitInput
  occupancies?: Prisma.UnitOccupancyUncheckedCreateNestedManyWithoutUnitInput
}

export type UnitCreateOrConnectWithoutResidentInput = {
  where: Prisma.UnitWhereUniqueInput
  create: Prisma.XOR<Prisma.UnitCreateWithoutResidentInput, Prisma.UnitUncheckedCreateWithoutResidentInput>
}

export type UnitCreateManyResidentInputEnvelope = {
  data: Prisma.UnitCreateManyResidentInput | Prisma.UnitCreateManyResidentInput[]
  skipDuplicates?: boolean
}

export type UnitUpsertWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.UnitWhereUniqueInput
  update: Prisma.XOR<Prisma.UnitUpdateWithoutOwnerInput, Prisma.UnitUncheckedUpdateWithoutOwnerInput>
  create: Prisma.XOR<Prisma.UnitCreateWithoutOwnerInput, Prisma.UnitUncheckedCreateWithoutOwnerInput>
}

export type UnitUpdateWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.UnitWhereUniqueInput
  data: Prisma.XOR<Prisma.UnitUpdateWithoutOwnerInput, Prisma.UnitUncheckedUpdateWithoutOwnerInput>
}

export type UnitUpdateManyWithWhereWithoutOwnerInput = {
  where: Prisma.UnitScalarWhereInput
  data: Prisma.XOR<Prisma.UnitUpdateManyMutationInput, Prisma.UnitUncheckedUpdateManyWithoutOwnerInput>
}

export type UnitScalarWhereInput = {
  AND?: Prisma.UnitScalarWhereInput | Prisma.UnitScalarWhereInput[]
  OR?: Prisma.UnitScalarWhereInput[]
  NOT?: Prisma.UnitScalarWhereInput | Prisma.UnitScalarWhereInput[]
  id?: Prisma.StringFilter<"Unit"> | string
  buildingId?: Prisma.StringFilter<"Unit"> | string
  unitNumber?: Prisma.StringFilter<"Unit"> | string
  unitType?: Prisma.EnumUnitTypeFilter<"Unit"> | $Enums.UnitType
  floor?: Prisma.IntNullableFilter<"Unit"> | number | null
  areaSqm?: Prisma.FloatNullableFilter<"Unit"> | number | null
  millesimes?: Prisma.FloatNullableFilter<"Unit"> | number | null
  ownerId?: Prisma.StringNullableFilter<"Unit"> | string | null
  residentId?: Prisma.StringNullableFilter<"Unit"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Unit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Unit"> | Date | string
}

export type UnitUpsertWithWhereUniqueWithoutResidentInput = {
  where: Prisma.UnitWhereUniqueInput
  update: Prisma.XOR<Prisma.UnitUpdateWithoutResidentInput, Prisma.UnitUncheckedUpdateWithoutResidentInput>
  create: Prisma.XOR<Prisma.UnitCreateWithoutResidentInput, Prisma.UnitUncheckedCreateWithoutResidentInput>
}

export type UnitUpdateWithWhereUniqueWithoutResidentInput = {
  where: Prisma.UnitWhereUniqueInput
  data: Prisma.XOR<Prisma.UnitUpdateWithoutResidentInput, Prisma.UnitUncheckedUpdateWithoutResidentInput>
}

export type UnitUpdateManyWithWhereWithoutResidentInput = {
  where: Prisma.UnitScalarWhereInput
  data: Prisma.XOR<Prisma.UnitUpdateManyMutationInput, Prisma.UnitUncheckedUpdateManyWithoutResidentInput>
}

export type UnitCreateWithoutBuildingInput = {
  id?: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  owner?: Prisma.UserCreateNestedOneWithoutOwnedUnitsInput
  resident?: Prisma.UserCreateNestedOneWithoutResidentUnitsInput
  maintenanceRequests?: Prisma.MaintenanceRequestCreateNestedManyWithoutUnitInput
  payments?: Prisma.UnitPaymentCreateNestedManyWithoutUnitInput
  occupancies?: Prisma.UnitOccupancyCreateNestedManyWithoutUnitInput
}

export type UnitUncheckedCreateWithoutBuildingInput = {
  id?: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  ownerId?: string | null
  residentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  maintenanceRequests?: Prisma.MaintenanceRequestUncheckedCreateNestedManyWithoutUnitInput
  payments?: Prisma.UnitPaymentUncheckedCreateNestedManyWithoutUnitInput
  occupancies?: Prisma.UnitOccupancyUncheckedCreateNestedManyWithoutUnitInput
}

export type UnitCreateOrConnectWithoutBuildingInput = {
  where: Prisma.UnitWhereUniqueInput
  create: Prisma.XOR<Prisma.UnitCreateWithoutBuildingInput, Prisma.UnitUncheckedCreateWithoutBuildingInput>
}

export type UnitCreateManyBuildingInputEnvelope = {
  data: Prisma.UnitCreateManyBuildingInput | Prisma.UnitCreateManyBuildingInput[]
  skipDuplicates?: boolean
}

export type UnitUpsertWithWhereUniqueWithoutBuildingInput = {
  where: Prisma.UnitWhereUniqueInput
  update: Prisma.XOR<Prisma.UnitUpdateWithoutBuildingInput, Prisma.UnitUncheckedUpdateWithoutBuildingInput>
  create: Prisma.XOR<Prisma.UnitCreateWithoutBuildingInput, Prisma.UnitUncheckedCreateWithoutBuildingInput>
}

export type UnitUpdateWithWhereUniqueWithoutBuildingInput = {
  where: Prisma.UnitWhereUniqueInput
  data: Prisma.XOR<Prisma.UnitUpdateWithoutBuildingInput, Prisma.UnitUncheckedUpdateWithoutBuildingInput>
}

export type UnitUpdateManyWithWhereWithoutBuildingInput = {
  where: Prisma.UnitScalarWhereInput
  data: Prisma.XOR<Prisma.UnitUpdateManyMutationInput, Prisma.UnitUncheckedUpdateManyWithoutBuildingInput>
}

export type UnitCreateWithoutOccupanciesInput = {
  id?: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  building: Prisma.BuildingCreateNestedOneWithoutUnitsInput
  owner?: Prisma.UserCreateNestedOneWithoutOwnedUnitsInput
  resident?: Prisma.UserCreateNestedOneWithoutResidentUnitsInput
  maintenanceRequests?: Prisma.MaintenanceRequestCreateNestedManyWithoutUnitInput
  payments?: Prisma.UnitPaymentCreateNestedManyWithoutUnitInput
}

export type UnitUncheckedCreateWithoutOccupanciesInput = {
  id?: string
  buildingId: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  ownerId?: string | null
  residentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  maintenanceRequests?: Prisma.MaintenanceRequestUncheckedCreateNestedManyWithoutUnitInput
  payments?: Prisma.UnitPaymentUncheckedCreateNestedManyWithoutUnitInput
}

export type UnitCreateOrConnectWithoutOccupanciesInput = {
  where: Prisma.UnitWhereUniqueInput
  create: Prisma.XOR<Prisma.UnitCreateWithoutOccupanciesInput, Prisma.UnitUncheckedCreateWithoutOccupanciesInput>
}

export type UnitUpsertWithoutOccupanciesInput = {
  update: Prisma.XOR<Prisma.UnitUpdateWithoutOccupanciesInput, Prisma.UnitUncheckedUpdateWithoutOccupanciesInput>
  create: Prisma.XOR<Prisma.UnitCreateWithoutOccupanciesInput, Prisma.UnitUncheckedCreateWithoutOccupanciesInput>
  where?: Prisma.UnitWhereInput
}

export type UnitUpdateToOneWithWhereWithoutOccupanciesInput = {
  where?: Prisma.UnitWhereInput
  data: Prisma.XOR<Prisma.UnitUpdateWithoutOccupanciesInput, Prisma.UnitUncheckedUpdateWithoutOccupanciesInput>
}

export type UnitUpdateWithoutOccupanciesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  building?: Prisma.BuildingUpdateOneRequiredWithoutUnitsNestedInput
  owner?: Prisma.UserUpdateOneWithoutOwnedUnitsNestedInput
  resident?: Prisma.UserUpdateOneWithoutResidentUnitsNestedInput
  maintenanceRequests?: Prisma.MaintenanceRequestUpdateManyWithoutUnitNestedInput
  payments?: Prisma.UnitPaymentUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateWithoutOccupanciesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  residentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maintenanceRequests?: Prisma.MaintenanceRequestUncheckedUpdateManyWithoutUnitNestedInput
  payments?: Prisma.UnitPaymentUncheckedUpdateManyWithoutUnitNestedInput
}

export type UnitCreateWithoutPaymentsInput = {
  id?: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  building: Prisma.BuildingCreateNestedOneWithoutUnitsInput
  owner?: Prisma.UserCreateNestedOneWithoutOwnedUnitsInput
  resident?: Prisma.UserCreateNestedOneWithoutResidentUnitsInput
  maintenanceRequests?: Prisma.MaintenanceRequestCreateNestedManyWithoutUnitInput
  occupancies?: Prisma.UnitOccupancyCreateNestedManyWithoutUnitInput
}

export type UnitUncheckedCreateWithoutPaymentsInput = {
  id?: string
  buildingId: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  ownerId?: string | null
  residentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  maintenanceRequests?: Prisma.MaintenanceRequestUncheckedCreateNestedManyWithoutUnitInput
  occupancies?: Prisma.UnitOccupancyUncheckedCreateNestedManyWithoutUnitInput
}

export type UnitCreateOrConnectWithoutPaymentsInput = {
  where: Prisma.UnitWhereUniqueInput
  create: Prisma.XOR<Prisma.UnitCreateWithoutPaymentsInput, Prisma.UnitUncheckedCreateWithoutPaymentsInput>
}

export type UnitUpsertWithoutPaymentsInput = {
  update: Prisma.XOR<Prisma.UnitUpdateWithoutPaymentsInput, Prisma.UnitUncheckedUpdateWithoutPaymentsInput>
  create: Prisma.XOR<Prisma.UnitCreateWithoutPaymentsInput, Prisma.UnitUncheckedCreateWithoutPaymentsInput>
  where?: Prisma.UnitWhereInput
}

export type UnitUpdateToOneWithWhereWithoutPaymentsInput = {
  where?: Prisma.UnitWhereInput
  data: Prisma.XOR<Prisma.UnitUpdateWithoutPaymentsInput, Prisma.UnitUncheckedUpdateWithoutPaymentsInput>
}

export type UnitUpdateWithoutPaymentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  building?: Prisma.BuildingUpdateOneRequiredWithoutUnitsNestedInput
  owner?: Prisma.UserUpdateOneWithoutOwnedUnitsNestedInput
  resident?: Prisma.UserUpdateOneWithoutResidentUnitsNestedInput
  maintenanceRequests?: Prisma.MaintenanceRequestUpdateManyWithoutUnitNestedInput
  occupancies?: Prisma.UnitOccupancyUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateWithoutPaymentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  residentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maintenanceRequests?: Prisma.MaintenanceRequestUncheckedUpdateManyWithoutUnitNestedInput
  occupancies?: Prisma.UnitOccupancyUncheckedUpdateManyWithoutUnitNestedInput
}

export type UnitCreateWithoutMaintenanceRequestsInput = {
  id?: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  building: Prisma.BuildingCreateNestedOneWithoutUnitsInput
  owner?: Prisma.UserCreateNestedOneWithoutOwnedUnitsInput
  resident?: Prisma.UserCreateNestedOneWithoutResidentUnitsInput
  payments?: Prisma.UnitPaymentCreateNestedManyWithoutUnitInput
  occupancies?: Prisma.UnitOccupancyCreateNestedManyWithoutUnitInput
}

export type UnitUncheckedCreateWithoutMaintenanceRequestsInput = {
  id?: string
  buildingId: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  ownerId?: string | null
  residentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payments?: Prisma.UnitPaymentUncheckedCreateNestedManyWithoutUnitInput
  occupancies?: Prisma.UnitOccupancyUncheckedCreateNestedManyWithoutUnitInput
}

export type UnitCreateOrConnectWithoutMaintenanceRequestsInput = {
  where: Prisma.UnitWhereUniqueInput
  create: Prisma.XOR<Prisma.UnitCreateWithoutMaintenanceRequestsInput, Prisma.UnitUncheckedCreateWithoutMaintenanceRequestsInput>
}

export type UnitUpsertWithoutMaintenanceRequestsInput = {
  update: Prisma.XOR<Prisma.UnitUpdateWithoutMaintenanceRequestsInput, Prisma.UnitUncheckedUpdateWithoutMaintenanceRequestsInput>
  create: Prisma.XOR<Prisma.UnitCreateWithoutMaintenanceRequestsInput, Prisma.UnitUncheckedCreateWithoutMaintenanceRequestsInput>
  where?: Prisma.UnitWhereInput
}

export type UnitUpdateToOneWithWhereWithoutMaintenanceRequestsInput = {
  where?: Prisma.UnitWhereInput
  data: Prisma.XOR<Prisma.UnitUpdateWithoutMaintenanceRequestsInput, Prisma.UnitUncheckedUpdateWithoutMaintenanceRequestsInput>
}

export type UnitUpdateWithoutMaintenanceRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  building?: Prisma.BuildingUpdateOneRequiredWithoutUnitsNestedInput
  owner?: Prisma.UserUpdateOneWithoutOwnedUnitsNestedInput
  resident?: Prisma.UserUpdateOneWithoutResidentUnitsNestedInput
  payments?: Prisma.UnitPaymentUpdateManyWithoutUnitNestedInput
  occupancies?: Prisma.UnitOccupancyUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateWithoutMaintenanceRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  residentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payments?: Prisma.UnitPaymentUncheckedUpdateManyWithoutUnitNestedInput
  occupancies?: Prisma.UnitOccupancyUncheckedUpdateManyWithoutUnitNestedInput
}

export type UnitCreateManyOwnerInput = {
  id?: string
  buildingId: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  residentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UnitCreateManyResidentInput = {
  id?: string
  buildingId: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  ownerId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UnitUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  building?: Prisma.BuildingUpdateOneRequiredWithoutUnitsNestedInput
  resident?: Prisma.UserUpdateOneWithoutResidentUnitsNestedInput
  maintenanceRequests?: Prisma.MaintenanceRequestUpdateManyWithoutUnitNestedInput
  payments?: Prisma.UnitPaymentUpdateManyWithoutUnitNestedInput
  occupancies?: Prisma.UnitOccupancyUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  residentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maintenanceRequests?: Prisma.MaintenanceRequestUncheckedUpdateManyWithoutUnitNestedInput
  payments?: Prisma.UnitPaymentUncheckedUpdateManyWithoutUnitNestedInput
  occupancies?: Prisma.UnitOccupancyUncheckedUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateManyWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  residentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UnitUpdateWithoutResidentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  building?: Prisma.BuildingUpdateOneRequiredWithoutUnitsNestedInput
  owner?: Prisma.UserUpdateOneWithoutOwnedUnitsNestedInput
  maintenanceRequests?: Prisma.MaintenanceRequestUpdateManyWithoutUnitNestedInput
  payments?: Prisma.UnitPaymentUpdateManyWithoutUnitNestedInput
  occupancies?: Prisma.UnitOccupancyUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateWithoutResidentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maintenanceRequests?: Prisma.MaintenanceRequestUncheckedUpdateManyWithoutUnitNestedInput
  payments?: Prisma.UnitPaymentUncheckedUpdateManyWithoutUnitNestedInput
  occupancies?: Prisma.UnitOccupancyUncheckedUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateManyWithoutResidentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UnitCreateManyBuildingInput = {
  id?: string
  unitNumber: string
  unitType?: $Enums.UnitType
  floor?: number | null
  areaSqm?: number | null
  millesimes?: number | null
  ownerId?: string | null
  residentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UnitUpdateWithoutBuildingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneWithoutOwnedUnitsNestedInput
  resident?: Prisma.UserUpdateOneWithoutResidentUnitsNestedInput
  maintenanceRequests?: Prisma.MaintenanceRequestUpdateManyWithoutUnitNestedInput
  payments?: Prisma.UnitPaymentUpdateManyWithoutUnitNestedInput
  occupancies?: Prisma.UnitOccupancyUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateWithoutBuildingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  residentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maintenanceRequests?: Prisma.MaintenanceRequestUncheckedUpdateManyWithoutUnitNestedInput
  payments?: Prisma.UnitPaymentUncheckedUpdateManyWithoutUnitNestedInput
  occupancies?: Prisma.UnitOccupancyUncheckedUpdateManyWithoutUnitNestedInput
}

export type UnitUncheckedUpdateManyWithoutBuildingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitNumber?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  floor?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  areaSqm?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  millesimes?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  residentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type UnitCountOutputType
 */

export type UnitCountOutputType = {
  maintenanceRequests: number
  payments: number
  occupancies: number
}

export type UnitCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  maintenanceRequests?: boolean | UnitCountOutputTypeCountMaintenanceRequestsArgs
  payments?: boolean | UnitCountOutputTypeCountPaymentsArgs
  occupancies?: boolean | UnitCountOutputTypeCountOccupanciesArgs
}

/**
 * UnitCountOutputType without action
 */
export type UnitCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnitCountOutputType
   */
  select?: Prisma.UnitCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UnitCountOutputType without action
 */
export type UnitCountOutputTypeCountMaintenanceRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MaintenanceRequestWhereInput
}

/**
 * UnitCountOutputType without action
 */
export type UnitCountOutputTypeCountPaymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UnitPaymentWhereInput
}

/**
 * UnitCountOutputType without action
 */
export type UnitCountOutputTypeCountOccupanciesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UnitOccupancyWhereInput
}


export type UnitSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buildingId?: boolean
  unitNumber?: boolean
  unitType?: boolean
  floor?: boolean
  areaSqm?: boolean
  millesimes?: boolean
  ownerId?: boolean
  residentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.Unit$ownerArgs<ExtArgs>
  resident?: boolean | Prisma.Unit$residentArgs<ExtArgs>
  maintenanceRequests?: boolean | Prisma.Unit$maintenanceRequestsArgs<ExtArgs>
  payments?: boolean | Prisma.Unit$paymentsArgs<ExtArgs>
  occupancies?: boolean | Prisma.Unit$occupanciesArgs<ExtArgs>
  _count?: boolean | Prisma.UnitCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["unit"]>

export type UnitSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buildingId?: boolean
  unitNumber?: boolean
  unitType?: boolean
  floor?: boolean
  areaSqm?: boolean
  millesimes?: boolean
  ownerId?: boolean
  residentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.Unit$ownerArgs<ExtArgs>
  resident?: boolean | Prisma.Unit$residentArgs<ExtArgs>
}, ExtArgs["result"]["unit"]>

export type UnitSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buildingId?: boolean
  unitNumber?: boolean
  unitType?: boolean
  floor?: boolean
  areaSqm?: boolean
  millesimes?: boolean
  ownerId?: boolean
  residentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.Unit$ownerArgs<ExtArgs>
  resident?: boolean | Prisma.Unit$residentArgs<ExtArgs>
}, ExtArgs["result"]["unit"]>

export type UnitSelectScalar = {
  id?: boolean
  buildingId?: boolean
  unitNumber?: boolean
  unitType?: boolean
  floor?: boolean
  areaSqm?: boolean
  millesimes?: boolean
  ownerId?: boolean
  residentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type UnitOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "buildingId" | "unitNumber" | "unitType" | "floor" | "areaSqm" | "millesimes" | "ownerId" | "residentId" | "createdAt" | "updatedAt", ExtArgs["result"]["unit"]>
export type UnitInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.Unit$ownerArgs<ExtArgs>
  resident?: boolean | Prisma.Unit$residentArgs<ExtArgs>
  maintenanceRequests?: boolean | Prisma.Unit$maintenanceRequestsArgs<ExtArgs>
  payments?: boolean | Prisma.Unit$paymentsArgs<ExtArgs>
  occupancies?: boolean | Prisma.Unit$occupanciesArgs<ExtArgs>
  _count?: boolean | Prisma.UnitCountOutputTypeDefaultArgs<ExtArgs>
}
export type UnitIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.Unit$ownerArgs<ExtArgs>
  resident?: boolean | Prisma.Unit$residentArgs<ExtArgs>
}
export type UnitIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.Unit$ownerArgs<ExtArgs>
  resident?: boolean | Prisma.Unit$residentArgs<ExtArgs>
}

export type $UnitPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Unit"
  objects: {
    building: Prisma.$BuildingPayload<ExtArgs>
    owner: Prisma.$UserPayload<ExtArgs> | null
    resident: Prisma.$UserPayload<ExtArgs> | null
    maintenanceRequests: Prisma.$MaintenanceRequestPayload<ExtArgs>[]
    payments: Prisma.$UnitPaymentPayload<ExtArgs>[]
    occupancies: Prisma.$UnitOccupancyPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    buildingId: string
    unitNumber: string
    unitType: $Enums.UnitType
    floor: number | null
    areaSqm: number | null
    millesimes: number | null
    ownerId: string | null
    residentId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["unit"]>
  composites: {}
}

export type UnitGetPayload<S extends boolean | null | undefined | UnitDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UnitPayload, S>

export type UnitCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UnitFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UnitCountAggregateInputType | true
  }

export interface UnitDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Unit'], meta: { name: 'Unit' } }
  /**
   * Find zero or one Unit that matches the filter.
   * @param {UnitFindUniqueArgs} args - Arguments to find a Unit
   * @example
   * // Get one Unit
   * const unit = await prisma.unit.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UnitFindUniqueArgs>(args: Prisma.SelectSubset<T, UnitFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Unit that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UnitFindUniqueOrThrowArgs} args - Arguments to find a Unit
   * @example
   * // Get one Unit
   * const unit = await prisma.unit.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UnitFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UnitFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Unit that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnitFindFirstArgs} args - Arguments to find a Unit
   * @example
   * // Get one Unit
   * const unit = await prisma.unit.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UnitFindFirstArgs>(args?: Prisma.SelectSubset<T, UnitFindFirstArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Unit that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnitFindFirstOrThrowArgs} args - Arguments to find a Unit
   * @example
   * // Get one Unit
   * const unit = await prisma.unit.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UnitFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UnitFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Units that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnitFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Units
   * const units = await prisma.unit.findMany()
   * 
   * // Get first 10 Units
   * const units = await prisma.unit.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const unitWithIdOnly = await prisma.unit.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UnitFindManyArgs>(args?: Prisma.SelectSubset<T, UnitFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Unit.
   * @param {UnitCreateArgs} args - Arguments to create a Unit.
   * @example
   * // Create one Unit
   * const Unit = await prisma.unit.create({
   *   data: {
   *     // ... data to create a Unit
   *   }
   * })
   * 
   */
  create<T extends UnitCreateArgs>(args: Prisma.SelectSubset<T, UnitCreateArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Units.
   * @param {UnitCreateManyArgs} args - Arguments to create many Units.
   * @example
   * // Create many Units
   * const unit = await prisma.unit.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UnitCreateManyArgs>(args?: Prisma.SelectSubset<T, UnitCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Units and returns the data saved in the database.
   * @param {UnitCreateManyAndReturnArgs} args - Arguments to create many Units.
   * @example
   * // Create many Units
   * const unit = await prisma.unit.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Units and only return the `id`
   * const unitWithIdOnly = await prisma.unit.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UnitCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UnitCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Unit.
   * @param {UnitDeleteArgs} args - Arguments to delete one Unit.
   * @example
   * // Delete one Unit
   * const Unit = await prisma.unit.delete({
   *   where: {
   *     // ... filter to delete one Unit
   *   }
   * })
   * 
   */
  delete<T extends UnitDeleteArgs>(args: Prisma.SelectSubset<T, UnitDeleteArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Unit.
   * @param {UnitUpdateArgs} args - Arguments to update one Unit.
   * @example
   * // Update one Unit
   * const unit = await prisma.unit.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UnitUpdateArgs>(args: Prisma.SelectSubset<T, UnitUpdateArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Units.
   * @param {UnitDeleteManyArgs} args - Arguments to filter Units to delete.
   * @example
   * // Delete a few Units
   * const { count } = await prisma.unit.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UnitDeleteManyArgs>(args?: Prisma.SelectSubset<T, UnitDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Units.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnitUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Units
   * const unit = await prisma.unit.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UnitUpdateManyArgs>(args: Prisma.SelectSubset<T, UnitUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Units and returns the data updated in the database.
   * @param {UnitUpdateManyAndReturnArgs} args - Arguments to update many Units.
   * @example
   * // Update many Units
   * const unit = await prisma.unit.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Units and only return the `id`
   * const unitWithIdOnly = await prisma.unit.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UnitUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UnitUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Unit.
   * @param {UnitUpsertArgs} args - Arguments to update or create a Unit.
   * @example
   * // Update or create a Unit
   * const unit = await prisma.unit.upsert({
   *   create: {
   *     // ... data to create a Unit
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Unit we want to update
   *   }
   * })
   */
  upsert<T extends UnitUpsertArgs>(args: Prisma.SelectSubset<T, UnitUpsertArgs<ExtArgs>>): Prisma.Prisma__UnitClient<runtime.Types.Result.GetResult<Prisma.$UnitPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Units.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnitCountArgs} args - Arguments to filter Units to count.
   * @example
   * // Count the number of Units
   * const count = await prisma.unit.count({
   *   where: {
   *     // ... the filter for the Units we want to count
   *   }
   * })
  **/
  count<T extends UnitCountArgs>(
    args?: Prisma.Subset<T, UnitCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UnitCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Unit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnitAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UnitAggregateArgs>(args: Prisma.Subset<T, UnitAggregateArgs>): Prisma.PrismaPromise<GetUnitAggregateType<T>>

  /**
   * Group by Unit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnitGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UnitGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UnitGroupByArgs['orderBy'] }
      : { orderBy?: UnitGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UnitGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUnitGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Unit model
 */
readonly fields: UnitFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Unit.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UnitClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  building<T extends Prisma.BuildingDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BuildingDefaultArgs<ExtArgs>>): Prisma.Prisma__BuildingClient<runtime.Types.Result.GetResult<Prisma.$BuildingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  owner<T extends Prisma.Unit$ownerArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Unit$ownerArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  resident<T extends Prisma.Unit$residentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Unit$residentArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  maintenanceRequests<T extends Prisma.Unit$maintenanceRequestsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Unit$maintenanceRequestsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaintenanceRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  payments<T extends Prisma.Unit$paymentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Unit$paymentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnitPaymentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  occupancies<T extends Prisma.Unit$occupanciesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Unit$occupanciesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnitOccupancyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Unit model
 */
export interface UnitFieldRefs {
  readonly id: Prisma.FieldRef<"Unit", 'String'>
  readonly buildingId: Prisma.FieldRef<"Unit", 'String'>
  readonly unitNumber: Prisma.FieldRef<"Unit", 'String'>
  readonly unitType: Prisma.FieldRef<"Unit", 'UnitType'>
  readonly floor: Prisma.FieldRef<"Unit", 'Int'>
  readonly areaSqm: Prisma.FieldRef<"Unit", 'Float'>
  readonly millesimes: Prisma.FieldRef<"Unit", 'Float'>
  readonly ownerId: Prisma.FieldRef<"Unit", 'String'>
  readonly residentId: Prisma.FieldRef<"Unit", 'String'>
  readonly createdAt: Prisma.FieldRef<"Unit", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Unit", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Unit findUnique
 */
export type UnitFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * Filter, which Unit to fetch.
   */
  where: Prisma.UnitWhereUniqueInput
}

/**
 * Unit findUniqueOrThrow
 */
export type UnitFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * Filter, which Unit to fetch.
   */
  where: Prisma.UnitWhereUniqueInput
}

/**
 * Unit findFirst
 */
export type UnitFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * Filter, which Unit to fetch.
   */
  where?: Prisma.UnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Units to fetch.
   */
  orderBy?: Prisma.UnitOrderByWithRelationInput | Prisma.UnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Units.
   */
  cursor?: Prisma.UnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Units from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Units.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Units.
   */
  distinct?: Prisma.UnitScalarFieldEnum | Prisma.UnitScalarFieldEnum[]
}

/**
 * Unit findFirstOrThrow
 */
export type UnitFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * Filter, which Unit to fetch.
   */
  where?: Prisma.UnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Units to fetch.
   */
  orderBy?: Prisma.UnitOrderByWithRelationInput | Prisma.UnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Units.
   */
  cursor?: Prisma.UnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Units from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Units.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Units.
   */
  distinct?: Prisma.UnitScalarFieldEnum | Prisma.UnitScalarFieldEnum[]
}

/**
 * Unit findMany
 */
export type UnitFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * Filter, which Units to fetch.
   */
  where?: Prisma.UnitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Units to fetch.
   */
  orderBy?: Prisma.UnitOrderByWithRelationInput | Prisma.UnitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Units.
   */
  cursor?: Prisma.UnitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Units from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Units.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Units.
   */
  distinct?: Prisma.UnitScalarFieldEnum | Prisma.UnitScalarFieldEnum[]
}

/**
 * Unit create
 */
export type UnitCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * The data needed to create a Unit.
   */
  data: Prisma.XOR<Prisma.UnitCreateInput, Prisma.UnitUncheckedCreateInput>
}

/**
 * Unit createMany
 */
export type UnitCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Units.
   */
  data: Prisma.UnitCreateManyInput | Prisma.UnitCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Unit createManyAndReturn
 */
export type UnitCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * The data used to create many Units.
   */
  data: Prisma.UnitCreateManyInput | Prisma.UnitCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Unit update
 */
export type UnitUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * The data needed to update a Unit.
   */
  data: Prisma.XOR<Prisma.UnitUpdateInput, Prisma.UnitUncheckedUpdateInput>
  /**
   * Choose, which Unit to update.
   */
  where: Prisma.UnitWhereUniqueInput
}

/**
 * Unit updateMany
 */
export type UnitUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Units.
   */
  data: Prisma.XOR<Prisma.UnitUpdateManyMutationInput, Prisma.UnitUncheckedUpdateManyInput>
  /**
   * Filter which Units to update
   */
  where?: Prisma.UnitWhereInput
  /**
   * Limit how many Units to update.
   */
  limit?: number
}

/**
 * Unit updateManyAndReturn
 */
export type UnitUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * The data used to update Units.
   */
  data: Prisma.XOR<Prisma.UnitUpdateManyMutationInput, Prisma.UnitUncheckedUpdateManyInput>
  /**
   * Filter which Units to update
   */
  where?: Prisma.UnitWhereInput
  /**
   * Limit how many Units to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Unit upsert
 */
export type UnitUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * The filter to search for the Unit to update in case it exists.
   */
  where: Prisma.UnitWhereUniqueInput
  /**
   * In case the Unit found by the `where` argument doesn't exist, create a new Unit with this data.
   */
  create: Prisma.XOR<Prisma.UnitCreateInput, Prisma.UnitUncheckedCreateInput>
  /**
   * In case the Unit was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UnitUpdateInput, Prisma.UnitUncheckedUpdateInput>
}

/**
 * Unit delete
 */
export type UnitDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
  /**
   * Filter which Unit to delete.
   */
  where: Prisma.UnitWhereUniqueInput
}

/**
 * Unit deleteMany
 */
export type UnitDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Units to delete
   */
  where?: Prisma.UnitWhereInput
  /**
   * Limit how many Units to delete.
   */
  limit?: number
}

/**
 * Unit.owner
 */
export type Unit$ownerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Unit.resident
 */
export type Unit$residentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Unit.maintenanceRequests
 */
export type Unit$maintenanceRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceRequest
   */
  select?: Prisma.MaintenanceRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceRequest
   */
  omit?: Prisma.MaintenanceRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceRequestInclude<ExtArgs> | null
  where?: Prisma.MaintenanceRequestWhereInput
  orderBy?: Prisma.MaintenanceRequestOrderByWithRelationInput | Prisma.MaintenanceRequestOrderByWithRelationInput[]
  cursor?: Prisma.MaintenanceRequestWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MaintenanceRequestScalarFieldEnum | Prisma.MaintenanceRequestScalarFieldEnum[]
}

/**
 * Unit.payments
 */
export type Unit$paymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnitPayment
   */
  select?: Prisma.UnitPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnitPayment
   */
  omit?: Prisma.UnitPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitPaymentInclude<ExtArgs> | null
  where?: Prisma.UnitPaymentWhereInput
  orderBy?: Prisma.UnitPaymentOrderByWithRelationInput | Prisma.UnitPaymentOrderByWithRelationInput[]
  cursor?: Prisma.UnitPaymentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UnitPaymentScalarFieldEnum | Prisma.UnitPaymentScalarFieldEnum[]
}

/**
 * Unit.occupancies
 */
export type Unit$occupanciesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnitOccupancy
   */
  select?: Prisma.UnitOccupancySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnitOccupancy
   */
  omit?: Prisma.UnitOccupancyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitOccupancyInclude<ExtArgs> | null
  where?: Prisma.UnitOccupancyWhereInput
  orderBy?: Prisma.UnitOccupancyOrderByWithRelationInput | Prisma.UnitOccupancyOrderByWithRelationInput[]
  cursor?: Prisma.UnitOccupancyWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UnitOccupancyScalarFieldEnum | Prisma.UnitOccupancyScalarFieldEnum[]
}

/**
 * Unit without action
 */
export type UnitDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Unit
   */
  select?: Prisma.UnitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Unit
   */
  omit?: Prisma.UnitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnitInclude<ExtArgs> | null
}
